Repository nrwl/nx, pull requests merged in 2018-03, with the labels that each got.

#290 fix(lint): windows compatibility, collision of lib names
  packages/schematics/src/tslint/nxEnforceModuleBoundariesRule.spec.ts
  packages/schematics/src/tslint/nxEnforceModuleBoundariesRule.ts
Labels: blocked: needs rebased, type: bug

#346 fix(nx): allow more types of arguments
  e2e/schematics/command-line.test.ts
  package.json
  packages/bazel/package.json
  packages/bazel/src/utils/cli-config-utils.ts
  packages/schematics/bin/create-nx-workspace.ts
  packages/schematics/package.json
  packages/schematics/src/command-line/nx.ts
  packages/schematics/src/utils/cli-config-utils.ts
  yarn-error.log
  yarn.lock
Labels: scope: nx

#349 feat(schematics): add migration for karma app check
  packages/schematics/migrations/20180321-add-karma-app-check.ts
Labels: type: enhancement

#353 fix(nx): fix formatting for paths with space
  packages/schematics/src/command-line/format.ts
Labels: scope: nx
