Repository nrwl/nx, pull requests merged in 2021-08, with the labels that each got.

#6592 fix(core): flush changes using the tree write file options
  packages/tao/src/commands/generate.ts
  packages/tao/src/commands/migrate.ts
Labels: scope: core

#6550 cleanup(repo): remove unused ext from file data and fix ext regex matcher
  packages/angular/src/builders/webpack-browser/webpack-browser.impl.ts
  packages/angular/src/executors/delegate-build/delegate-build.impl.ts
  packages/angular/src/executors/package/package.impl.ts
  packages/angular/src/migrations/update-10-5-0/add-template-support-and-presets-to-eslint.ts
  packages/devkit/src/project-graph/interfaces.ts
  packages/devkit/src/project-graph/project-graph-builder.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin-nx/tests/rules/enforce-module-boundaries.spec.ts
  packages/next/src/executors/export/export.impl.ts
  packages/next/src/executors/server/server.impl.ts
  packages/node/src/executors/package/package.impl.ts
  packages/react/src/migrations/update-9-4-0/babelrc-9-4-0.ts
  packages/web/src/executors/dev-server/dev-server.impl.ts
  packages/web/src/executors/package/package.impl.ts
  packages/web/src/migrations/update-11-5-2/create-babelrc-for-workspace-libs.ts
  packages/workspace/src/command-line/affected.ts
  packages/workspace/src/command-line/dep-graph.ts
  packages/workspace/src/command-line/format.ts
  packages/workspace/src/command-line/lint.ts
  packages/workspace/src/command-line/run-many.ts
  packages/workspace/src/command-line/run-one.ts
  packages/workspace/src/command-line/workspace-integrity-checks.spec.ts
  packages/workspace/src/core/affected-project-graph/affected-project-graph.spec.ts
  packages/workspace/src/core/affected-project-graph/locators/implicit-json-changes.spec.ts
  packages/workspace/src/core/affected-project-graph/locators/npm-packages.spec.ts
  packages/workspace/src/core/affected-project-graph/locators/nx-json-changes.spec.ts
  packages/workspace/src/core/affected-project-graph/locators/tsconfig-json-changes.spec.ts
  packages/workspace/src/core/affected-project-graph/locators/workspace-json-changes.spec.ts
  packages/workspace/src/core/affected-project-graph/locators/workspace-projects.spec.ts
  packages/workspace/src/core/file-graph/file-map.spec.ts
  packages/workspace/src/core/file-utils.ts
  packages/workspace/src/core/hasher/hasher.spec.ts
  packages/workspace/src/core/nx-deps/nx-deps-cache.spec.ts
  packages/workspace/src/core/nx-deps/nx-deps-cache.ts
  packages/workspace/src/core/project-graph/project-graph.spec.ts
  packages/workspace/src/core/project-graph/project-graph.ts
  packages/workspace/src/core/target-project-locator.spec.ts
  packages/workspace/src/executors/tsc/tsc.impl.ts
  packages/workspace/src/generators/remove/lib/check-dependencies.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.spec.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts
  packages/workspace/src/utilities/create-project-graph-from-tree.ts
  packages/workspace/src/utilities/generate-globs.ts
  packages/workspace/src/utilities/project-graph-utils.ts
  packages/workspace/src/utils/ast-utils.ts
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: scope: core, type: bug, type: cleanup

#6598 feat(core): add devkit tree method to change the permissions of a file
  packages/devkit/src/utils/invoke-nx-generator.ts
  packages/tao/src/shared/tree.spec.ts
  packages/tao/src/shared/tree.ts
Labels: scope: core

#6613 fix(core): fix reading nx.json without projects property
  packages/workspace/src/core/file-utils.ts
Labels: scope: core

#6609 fix(nxdev): consolidate border radius on pages
  nx-dev/nx-dev/pages/[...segments].tsx
  nx-dev/nx-dev/pages/community.tsx
  nx-dev/nx-dev/pages/index.tsx
  nx-dev/ui/common/src/lib/inline-command.tsx
  nx-dev/ui/common/src/lib/plugin-card.tsx
Labels: type: enhancement

#6616 fix(misc): read settings in .editorconfig when formatting files in generators
  packages/devkit/src/generators/format-files.ts
Labels: scope: misc

#6625 chore(angular): enable all e2e tests for npm package manager
  e2e/angular-core/src/angular-core.test.ts
  e2e/utils/index.ts
Labels: scope: angular

#6627 chore(repo): add isOsx for e2e tests and include macos to nightly
  .github/workflows/e2e-matrix.yml
  e2e/utils/index.ts
Labels: scope: repo

#6628 chore(repo): enforce fixed version for local packages in e2e tests
  e2e/utils/index.ts
Labels: scope: repo

#6632 fix(core): default run-many to use provided projects order
  packages/workspace/src/command-line/run-many.ts
Labels: scope: core

#6651 fix(core): fix prompt support for enum definitions
  packages/tao/src/shared/params.ts
Labels: scope: core

#6652 fix(angular): init cypress correctly if needed when creating an app
  packages/angular/src/generators/init/init.ts
  packages/angular/src/generators/karma/karma.ts
Labels: scope: angular

#6658 chore(repo): improve e2e test stability
  .github/workflows/e2e-matrix.yml
  e2e/next/src/next.test.ts
  e2e/nx-plugin/src/nx-plugin.test.ts
  e2e/react/src/react-package.test.ts
  e2e/utils/index.ts
  e2e/web/src/file-server.test.ts
  e2e/workspace/src/run-commands.test.ts
Labels: scope: repo

#6667 cleanup(misc): refactor absolute imports to self
  packages/tao/src/commands/ngcli-adapter.ts
  packages/workspace/src/generators/library/library.ts
  packages/workspace/src/tasks-runner/run-command.ts
  packages/workspace/src/utils/rules/rename-package-imports.ts
  packages/workspace/src/utils/testing.ts
Labels: scope: misc

#6666 chore(repo): fix osx failing tests
  e2e/utils/index.ts
  e2e/workspace/src/run-commands.test.ts
  e2e/workspace/src/workspace.test.ts
Labels: scope: repo

#6660 fix(core): fix --with-deps arg support and deprecate its usage
  packages/workspace/src/command-line/run-many.ts
  packages/workspace/src/command-line/run-one.ts
  packages/workspace/src/tasks-runner/run-command.ts
Labels: scope: core

#6680 chore(repo): cleanup & optimize circleci config
  .circleci/config.yml
Labels: scope: repo

#6572 chore(core): opt-in daemon for ProjectGraph creation, refactor hasher
  docs/angular/cli/daemon-start.md
  docs/angular/cli/daemon-stop.md
  docs/map.json
  docs/node/cli/daemon-start.md
  docs/node/cli/daemon-stop.md
  docs/react/cli/daemon-start.md
  docs/react/cli/daemon-stop.md
  e2e/workspace/src/workspace.test.ts
  packages/cli/lib/parse-run-one-options.ts
  packages/workspace/src/command-line/nx-commands.ts
  packages/workspace/src/command-line/run-one.ts
  packages/workspace/src/command-line/supported-nx-commands.ts
  packages/workspace/src/core/file-utils.ts
  packages/workspace/src/core/hasher/file-hasher.ts
  packages/workspace/src/core/hasher/hasher.spec.ts
  packages/workspace/src/core/hasher/hasher.ts
  packages/workspace/src/core/nx-deps/nx-deps-cache.ts
  packages/workspace/src/core/project-graph/daemon/cache.ts
  packages/workspace/src/core/project-graph/daemon/exec/index.ts
  packages/workspace/src/core/project-graph/daemon/exec/start.ts
  packages/workspace/src/core/project-graph/daemon/exec/stop.ts
  packages/workspace/src/core/project-graph/daemon/server.spec.ts
  packages/workspace/src/core/project-graph/daemon/server.ts
  packages/workspace/src/core/project-graph/project-graph.ts
Labels: scope: core

#6698 fix(gatsby): remove npm_config_legacy_peer_deps
  e2e/workspace/src/create-nx-workspace.test.ts
  packages/create-nx-workspace/bin/create-nx-workspace.ts
  packages/gatsby/src/generators/init/init.ts
Labels: scope: core

#6708 chore(repo): enable node 15 and 16 in the nightly runs
  .github/workflows/e2e-matrix.yml
  e2e/jest/src/jest.test.ts
Labels: scope: repo

#6709 chore(repo): make circleci jobs parametrised for running on different environments
  .circleci/config.yml
Labels: scope: repo

#6734 chore(repo): disable osx workspace e2e test for nightly
  .github/workflows/e2e-matrix.yml
Labels: scope: repo

#6677 feat(node): add TS plugins support for build executor
  docs/angular/api-node/executors/build.md
  docs/node/api-node/executors/build.md
  docs/react/api-node/executors/build.md
  e2e/node/src/node.test.ts
  package.json
  packages/node/src/executors/build/schema.json
  packages/node/src/utils/__mocks__/plugin-a.ts
  packages/node/src/utils/__mocks__/plugin-b.ts
  packages/node/src/utils/config.ts
  packages/node/src/utils/load-ts-plugins.spec.ts
  packages/node/src/utils/load-ts-plugins.ts
  packages/node/src/utils/node.config.spec.ts
  packages/node/src/utils/types.ts
  yarn.lock
Labels: scope: node

#6743 fix(core): skip caching output properties missing in options and arguments
  e2e/linter/src/linter.test.ts
  e2e/utils/index.ts
  e2e/workspace/src/run-commands.test.ts
  packages/linter/src/executors/lint/lint.impl.ts
  packages/workspace/src/tasks-runner/task-orchestrator.ts
  packages/workspace/src/tasks-runner/utils.ts
Labels: scope: core

#6765 fix(core): remove .eslintrc double extends update on move
  packages/workspace/src/generators/move/lib/update-eslintrc-json.spec.ts
  packages/workspace/src/generators/move/lib/update-project-root-files.ts
Labels: type: bug, scope: core, scope: linter

#6669 docs(core): improve cli docs
  docs/angular/cli/affected-build.md
  docs/angular/cli/affected-dep-graph.md
  docs/angular/cli/affected-e2e.md
  docs/angular/cli/affected-lint.md
  docs/angular/cli/affected-test.md
  docs/angular/cli/affected.md
  docs/angular/cli/dep-graph.md
  docs/angular/cli/format-check.md
  docs/angular/cli/format-write.md
  docs/angular/cli/migrate.md
  docs/angular/cli/print-affected.md
  docs/angular/cli/run-many.md
  docs/node/cli/affected-build.md
  docs/node/cli/affected-dep-graph.md
  docs/node/cli/affected-e2e.md
  docs/node/cli/affected-lint.md
  docs/node/cli/affected-test.md
  docs/node/cli/affected.md
  docs/node/cli/dep-graph.md
  docs/node/cli/format-check.md
  docs/node/cli/format-write.md
  docs/node/cli/migrate.md
  docs/node/cli/print-affected.md
  docs/node/cli/run-many.md
  docs/react/cli/affected-build.md
  docs/react/cli/affected-dep-graph.md
  docs/react/cli/affected-e2e.md
  docs/react/cli/affected-lint.md
  docs/react/cli/affected-test.md
  docs/react/cli/affected.md
  docs/react/cli/dep-graph.md
  docs/react/cli/format-check.md
  docs/react/cli/format-write.md
  docs/react/cli/migrate.md
  docs/react/cli/print-affected.md
  docs/react/cli/run-many.md
  packages/workspace/src/command-line/nx-commands.ts
  scripts/documentation/generate-cli-data.ts
Labels: scope: docs

#6884 fix(core): use defaultConfiguration in run-many and affected when no configuration is specified
  packages/workspace/src/tasks-runner/run-command.ts
Labels: scope: core
