Repository nrwl/nx, pull requests merged in 2021-11, with the labels that each got.

#7572 fix(core): ensure cache has correct project graph version
  packages/workspace/src/core/project-graph/build-project-graph.ts
Labels: scope: core

#6284 feat(nest): support nest 8
  e2e/node/src/node.test.ts
  package.json
  packages/nest/migrations.json
  packages/nest/package.json
  packages/nest/src/generators/application/application.spec.ts
  packages/nest/src/generators/application/files/main.ts__tmpl__
  packages/nest/src/generators/init/init.spec.ts
  packages/nest/src/generators/init/lib/add-dependencies.ts
  packages/nest/src/migrations/update-10-0-0/update-10-0-0.ts
  packages/nest/src/migrations/update-13-2-0/update-to-nest-8.ts
  packages/nest/src/utils/versions.ts
  packages/workspace/index.ts
  scripts/check-imports.js
  scripts/depcheck/missing.ts
  yarn.lock
Labels: blocked: third-party, scope: node

#7519 fix(storybook): install cypress packages if not installed for e2e apps
  packages/storybook/src/generators/cypress-project/cypress-project.spec.ts
  packages/storybook/src/generators/cypress-project/cypress-project.ts
Labels: scope: storybook

#7622 docs(testing): add clarification for baseUrl when devServerTarget is set
  docs/angular/cli/e2e.md
  docs/node/cli/e2e.md
  docs/react/cli/e2e.md
  docs/shared/cli/e2e.md
  nx-dev/nx-dev/public/documentation/latest/angular/cli/e2e.md
  nx-dev/nx-dev/public/documentation/latest/node/cli/e2e.md
  nx-dev/nx-dev/public/documentation/latest/react/cli/e2e.md
  nx-dev/nx-dev/public/documentation/latest/shared/cli/e2e.md
  nx-dev/nx-dev/public/documentation/previous/angular/cli/e2e.md
  nx-dev/nx-dev/public/documentation/previous/node/cli/e2e.md
  nx-dev/nx-dev/public/documentation/previous/react/cli/e2e.md
  nx-dev/nx-dev/public/documentation/previous/shared/cli/e2e.md
Labels: type: docs, scope: testing tools, scope: docs

#7623 feat(linter): allow wildcards for banning external imports
  docs/shared/monorepo-tags.md
  nx-dev/nx-dev/public/documentation/latest/shared/monorepo-tags.md
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.spec.ts
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: type: feature, scope: linter

#7518 fix(storybook): only match exact component name for Storybook
  packages/angular/src/generators/stories/lib/component-info.ts
Labels: scope: storybook

#7810 fix(linter): fix broken circular deps output
  packages/workspace/src/core/nx-deps/nx-deps-cache.ts
  packages/workspace/src/utils/graph-utils.ts
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: scope: linter

#7887 chore(repo): fix resolution of @cypress/request until its deps are resolved
  package.json
  packages/cypress/src/generators/init/init.ts
  packages/cypress/src/utils/versions.ts
Labels: scope: testing tools

#7902 chore(repo): add hint for skipping build and cleanup on e2e runs
  scripts/e2e-build-package-publish.ts
Labels: scope: repo

#7903 chore(core): cleanup the obsolete graph version check from graph builder
  packages/workspace/src/core/project-graph/build-project-graph.ts
Labels: scope: core

#7906 feat(linter): allow banning of transitive dependencies from imports
  packages/eslint-plugin-nx/package.json
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/workspace/src/utils/runtime-lint-utils.ts
  tsconfig.base.json
Labels: scope: linter

#7932 feat(core): print out directly simple create-nx-workspace exceptions
  packages/create-nx-workspace/bin/create-nx-workspace.ts
Labels: scope: core

#7949 fix(linter): linter utils should respect nx.json folder configuration
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: scope: linter
