Repository nrwl/nx, pull requests merged in 2021-06, with the labels that each got.

#5854 feat(repo): add checks for lock files
  .github/workflows/npm-audit.yml
  .husky/pre-push
  package.json
  scripts/check-lock-files.js
Labels: scope: repo, type: enhancement

#5846 fix(testing): fix failing workspace e2e tests
  e2e/workspace/src/create-nx-workspace.test.ts
Labels: scope: testing tools

#5916 fix(testing): fix buffer issue on e2e test
  e2e/utils/index.ts
Labels: scope: repo

#5799 fix(storybook): generating stories without an existing e2e project
  docs/angular/api-angular/generators/stories.md
  docs/angular/api-react/generators/stories.md
  docs/node/api-angular/generators/stories.md
  docs/node/api-react/generators/stories.md
  docs/react/api-angular/generators/stories.md
  docs/react/api-react/generators/stories.md
  packages/angular/src/schematics/stories/schema.json
  packages/angular/src/schematics/stories/stories.ts
  packages/react/src/generators/stories/schema.json
  packages/react/src/generators/stories/stories.ts
  packages/storybook/src/generators/configuration/configuration.ts
Labels: scope: storybook

#5925 feat(repo): enable prefer offline for yarn install
  .circleci/config.yml
Labels: scope: repo

#5951 fix(storybook): fix broken migration test
  docs/angular/api-angular/generators/storybook-migrate-stories-to-6-2.md
  docs/node/api-angular/generators/storybook-migrate-stories-to-6-2.md
  docs/react/api-angular/generators/storybook-migrate-stories-to-6-2.md
  packages/angular/collection.json
  packages/angular/src/generators/storybook-migrate-defaults-5-to-6/schema.json
  packages/angular/src/generators/storybook-migrate-stories-to-6-2/compat.ts
  packages/angular/src/generators/storybook-migrate-stories-to-6-2/migrate-stories-to-6-2.spec.ts
  packages/angular/src/generators/storybook-migrate-stories-to-6-2/migrate-stories-to-6-2.ts
  packages/angular/src/generators/storybook-migrate-stories-to-6-2/schema.json
  packages/angular/src/schematics/storybook-migrate-stories-to-6-2/migrate-stories-to-6-2.ts
  packages/angular/src/schematics/storybook-migrate-stories-to-6-2/schema.d.ts
Labels: scope: storybook

#5995 fix(nest): fix lint convertor incomplete type
  packages/nest/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts
Labels: scope: repo

#5939 feat(repo): remove obsolete kill commands and check if ports closed
  e2e/angular/src/angular-core.test.ts
  e2e/angular/src/config-compat.test.ts
  e2e/angular/src/ngrx.test.ts
  e2e/angular/src/storybook.test.ts
  e2e/cli/src/cli.test.ts
  e2e/cypress/src/cypress.test.ts
  e2e/gatsby/src/gatsby.test.ts
  e2e/jest/src/jest.test.ts
  e2e/linter/src/linter.test.ts
  e2e/next/src/next.test.ts
  e2e/node/src/node.test.ts
  e2e/nx-plugin/src/nx-plugin.test.ts
  e2e/react/src/react.test.ts
  e2e/storybook/src/storybook.test.ts
  e2e/utils/index.ts
  e2e/web/src/file-server.test.ts
  e2e/web/src/web.test.ts
  e2e/workspace/src/create-nx-workspace.test.ts
  e2e/workspace/src/custom-layout.test.ts
  e2e/workspace/src/plugins.test.ts
  e2e/workspace/src/run-commands.test.ts
  e2e/workspace/src/workspace-aux-commands.test.ts
  e2e/workspace/src/workspace-lib.test.ts
  e2e/workspace/src/workspace.test.ts
  package.json
  yarn.lock
Labels: scope: repo

#6016 feat(repo): notify slack on nightly github actions
  .github/workflows/e2e-matrix.yml
  .github/workflows/npm-audit.yml
Labels: scope: repo

#6047 chore(repo): update pnpm to v6
  .circleci/config.yml
  .github/workflows/e2e-matrix.yml
  e2e/next/src/next.test.ts
  e2e/utils/index.ts
Labels: scope: repo

#5889 chore(repo): enable windows nightly tests
  .github/workflows/e2e-matrix.yml
  e2e/angular/src/storybook.test.ts
  e2e/gatsby/src/gatsby.test.ts
  e2e/next/src/next.test.ts
  e2e/node/src/node.test.ts
  e2e/nx-plugin/src/nx-plugin.test.ts
  e2e/utils/index.ts
  e2e/web/src/web.test.ts
  e2e/workspace/src/workspace-aux-commands.test.ts
  e2e/workspace/src/workspace.test.ts
  package.json
  packages/nest/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts
  packages/nx-plugin/src/generators/e2e-project/files/tests/__pluginName__.spec.ts__tmpl__
Labels: scope: repo

#6079 chore(repo): hide cypress e2e tests behind NX_E2E_CI_NIGHTLY flag
  .github/workflows/e2e-matrix.yml
  e2e/angular/src/angular-core.test.ts
  e2e/next/src/next.test.ts
  e2e/nx-plugin/src/nx-plugin.test.ts
  e2e/utils/index.ts
  e2e/web/src/web.test.ts
Labels: scope: repo

#6083 cleanup(angular): migrate downgrade-module and upgrade-module generators to nx devkit
  docs/angular/api-angular/generators/downgrade-module.md
  docs/angular/api-angular/generators/upgrade-module.md
  docs/node/api-angular/generators/downgrade-module.md
  docs/node/api-angular/generators/upgrade-module.md
  docs/react/api-angular/generators/downgrade-module.md
  docs/react/api-angular/generators/upgrade-module.md
  packages/angular/collection.json
  packages/angular/generators.ts
  packages/angular/src/generators/downgrade-module/__snapshots__/downgrade-module.spec.ts.snap
  packages/angular/src/generators/downgrade-module/compat.ts
  packages/angular/src/generators/downgrade-module/downgrade-module.spec.ts
  packages/angular/src/generators/downgrade-module/downgrade-module.ts
  packages/angular/src/generators/downgrade-module/files/main.ts__tmpl__
  packages/angular/src/generators/downgrade-module/lib/add-entry-components-to-module.ts
  packages/angular/src/generators/downgrade-module/lib/index.ts
  packages/angular/src/generators/downgrade-module/lib/normalize-options.ts
  packages/angular/src/generators/downgrade-module/lib/update-main.ts
  packages/angular/src/generators/downgrade-module/lib/update-module-bootstrap.ts
  packages/angular/src/generators/downgrade-module/schema.d.ts
  packages/angular/src/generators/downgrade-module/schema.json
  packages/angular/src/generators/upgrade-module/__snapshots__/upgrade-module.spec.ts.snap
  packages/angular/src/generators/upgrade-module/compat.ts
  packages/angular/src/generators/upgrade-module/files/__name__-setup.ts__tmpl__
  packages/angular/src/generators/upgrade-module/files/hybrid.spec.ts__tmpl__
  packages/angular/src/generators/upgrade-module/lib/add-imports-to-module.ts
  packages/angular/src/generators/upgrade-module/lib/create-files.ts
  packages/angular/src/generators/upgrade-module/lib/index.ts
  packages/angular/src/generators/upgrade-module/lib/normalize-options.ts
  packages/angular/src/generators/upgrade-module/lib/update-module-bootstrap.ts
  packages/angular/src/generators/upgrade-module/schema.d.ts
  packages/angular/src/generators/upgrade-module/schema.json
  packages/angular/src/generators/upgrade-module/upgrade-module.spec.ts
  packages/angular/src/generators/upgrade-module/upgrade-module.ts
  packages/angular/src/generators/utils/upgrade.ts
  packages/angular/src/schematics/downgrade-module/downgrade-module.spec.ts
  packages/angular/src/schematics/downgrade-module/downgrade-module.ts
  packages/angular/src/schematics/downgrade-module/schema.d.ts
  packages/angular/src/schematics/upgrade-module/schema.d.ts
  packages/angular/src/schematics/upgrade-module/upgrade-module.spec.ts
  packages/angular/src/schematics/upgrade-module/upgrade-module.ts
  packages/angular/src/utils/nx-devkit/testing.ts
  packages/angular/src/utils/testing.ts
  packages/angular/src/utils/upgrade.ts
  packages/workspace/src/utilities/ast-utils.ts
Labels: scope: angular

#6082 chore(repo): fix broken e2e test on workspace
  e2e/workspace/src/workspace.test.ts
Labels: scope: repo

#6092 chore(repo): report actual state of the matrix run
  .github/workflows/e2e-matrix.yml
Labels: scope: repo

#6096 chore(repo): add angular and react to e2e-workspace implicit deps
  nx.json
Labels: scope: repo

#6099 cleanup(angular): deprecate and clean up angular schematics utilities
  packages/angular/src/builders/webpack-browser/webpack-browser.impl.ts
  packages/angular/src/generators/application/application.ts
  packages/angular/src/generators/utils/insert-ngmodule-import.spec.ts
  packages/angular/src/generators/utils/insert-ngmodule-import.ts
  packages/angular/src/utils/ast-utils.ts
  packages/angular/src/utils/testing.ts
  packages/workspace/src/core/hasher/hasher.spec.ts
  packages/workspace/src/generators/preset/preset.ts
Labels: scope: angular

#6106 docs(angular): improve incremental build docs
  docs/angular/guides/setup-incremental-builds.md
  nx-dev/nx-dev/public/documentation/latest/angular/guides/setup-incremental-builds.md
  nx-dev/nx-dev/public/documentation/previous/angular/guides/setup-incremental-builds.md
Labels: scope: angular

#6108 chore(repo): fix storybook to 6.2.9 before 6.3.0 support is ready
  package.json
  packages/storybook/src/generators/init/__snapshots__/init.spec.ts.snap
  packages/storybook/src/utils/versions.ts
  yarn.lock
Labels: scope: repo, scope: storybook

#6103 fix(linter): tslint to eslint conversion should not override existing root config
  packages/angular/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/angular/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.spec.ts
  packages/angular/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts
  packages/cypress/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts
  packages/linter/src/utils/convert-tslint-to-eslint/project-converter.ts
  packages/nest/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts
Labels: scope: linter, type: bug

#6109 fix(angular): fix storybook-configuration not installing deps
  packages/angular/src/generators/storybook-configuration/lib/generate-storybook-configuration.ts
  packages/angular/src/generators/storybook-configuration/storybook-configuration.ts
Labels: scope: angular, scope: storybook

#6105 fix(angular): change tsconfig.worker.json to extend the right path
  docs/angular/api-angular/generators/web-worker.md
  docs/map.json
  docs/node/api-angular/generators/web-worker.md
  docs/react/api-angular/generators/web-worker.md
  packages/angular/collection.json
  packages/angular/src/generators/web-worker/compat.ts
  packages/angular/src/generators/web-worker/lib/index.ts
  packages/angular/src/generators/web-worker/lib/normalize-options.ts
  packages/angular/src/generators/web-worker/lib/update-tsconfig.ts
  packages/angular/src/generators/web-worker/schema.d.ts
  packages/angular/src/generators/web-worker/schema.json
  packages/angular/src/generators/web-worker/web-worker.spec.ts
  packages/angular/src/generators/web-worker/web-worker.ts
Labels: scope: angular

#6104 feat(storybook): upgrade to Storybook v6.3 support
  e2e/angular/src/storybook.test.ts
  package.json
  packages/storybook/migrations.json
  packages/storybook/src/generators/configuration/configuration.spec.ts
  packages/storybook/src/generators/configuration/configuration.ts
  packages/storybook/src/generators/configuration/root-files/.storybook/main.js
  packages/storybook/src/generators/init/__snapshots__/init.spec.ts.snap
  packages/storybook/src/generators/init/init.ts
  packages/storybook/src/migrations/update-12-5-0/migrate-storybook-6-3.spec.ts
  packages/storybook/src/migrations/update-12-5-0/migrate-storybook-6-3.ts
  packages/storybook/src/utils/versions.ts
  yarn.lock
Labels: scope: storybook

#6122 chore(repo): increase timeout for file server serve test
  e2e/web/src/file-server.test.ts
Labels: scope: repo

#6123 chore(angular): fix e2e failing tests caused by angular upgrade
  e2e/angular/src/angular-core.test.ts
  e2e/angular/src/angular-library.test.ts
Labels: scope: angular

#6125 chore(repo): run all cypress e2e tests headless and w/o watch
  e2e/angular/src/storybook.test.ts
  e2e/next/src/next.test.ts
  e2e/nx-plugin/src/nx-plugin.test.ts
  e2e/react/src/react.test.ts
  e2e/web/src/web.test.ts
Labels: scope: repo

#6068 feat(storybook): from addon knobs to controls
  docs/angular/guides/storybook-plugin.md
  docs/react/guides/storybook-plugin.md
  e2e/angular/src/storybook.test.ts
  nx-dev/nx-dev/public/documentation/latest/angular/guides/storybook-plugin.md
  nx-dev/nx-dev/public/documentation/latest/react/guides/storybook-plugin.md
  package.json
  packages/angular/src/generators/component-cypress-spec/__snapshots__/component-cypress-spec.spec.ts.snap
  packages/angular/src/generators/component-cypress-spec/component-cypress-spec.ts
  packages/angular/src/generators/component-cypress-spec/files/__componentFileName__.spec.ts__tmpl__
  packages/angular/src/generators/component-cypress-spec/lib/get-args-default-value.ts
  packages/angular/src/generators/component-story/__snapshots__/component-story.spec.ts.snap
  packages/angular/src/generators/component-story/component-story.ts
  packages/angular/src/generators/component-story/files/__componentFileName__.stories.ts__tmpl__
  packages/angular/src/generators/component-story/lib/get-args-default-value.ts
  packages/angular/src/generators/stories/__snapshots__/stories-lib.spec.ts.snap
  packages/angular/src/generators/storybook-configuration/storybook-configuration.spec.ts
  packages/angular/src/generators/utils/storybook.ts
  packages/react/src/generators/component-cypress-spec/component-cypress-spec.spec.ts
  packages/react/src/generators/component-cypress-spec/component-cypress-spec.ts
  packages/react/src/generators/component-cypress-spec/files/__componentName__.spec.__fileExt__
  packages/react/src/generators/component-story/component-story.spec.ts
  packages/react/src/generators/component-story/component-story.ts
  packages/react/src/generators/component-story/files/__componentFileName__.stories.__fileExt__
  packages/storybook/migrations.json
  packages/storybook/src/executors/build-storybook/build-storybook.impl.spec.ts
  packages/storybook/src/executors/storybook/storybook.impl.spec.ts
  packages/storybook/src/generators/configuration/configuration.spec.ts
  packages/storybook/src/generators/configuration/project-files/.storybook/preview.js__tmpl__
  packages/storybook/src/generators/configuration/root-files/.storybook/main.js
  packages/storybook/src/generators/init/__snapshots__/init.spec.ts.snap
  packages/storybook/src/generators/init/init.spec.ts
  packages/storybook/src/generators/init/init.ts
  packages/storybook/src/migrations/update-11-6-0/update-storybook.spec.ts
  packages/storybook/src/migrations/update-11-6-0/update-storybook.ts
  packages/storybook/src/migrations/update-12-5-0/install-addon-essentials.spec.ts
  packages/storybook/src/migrations/update-12-5-0/install-addon-essentials.ts
  scripts/depcheck/missing.ts
  yarn.lock
Labels: PR status: in-progress, scope: storybook

#6141 chore(repo): disable windows nightly until further investigation
  .github/workflows/e2e-matrix.yml
Labels: scope: repo

#6168 chore(repo): fix preprocessor test wrong import
  packages/cypress/src/plugins/preprocessor.spec.ts
Labels: scope: repo

#6170 fix(angular): check for angular.json when converting config event path
  packages/tao/src/commands/ngcli-adapter.ts
Labels: scope: angular

#6187 feat(repo): mark successful circleci runs with tag
  .circleci/config.yml
  scripts/circleci/get-last-successful-tag.sh
  scripts/circleci/tag-successful-build.sh
Labels: scope: repo

#6186 chore(repo): update pnpm to v6.9.1 and remove duplicate cypress tests
  .circleci/config.yml
  .github/workflows/e2e-matrix.yml
Labels: scope: repo
