Repository nrwl/nx, pull requests merged in 2021-09, with the labels that each got.

#6882 feat(testing): remediate `headless` option for Cypress 8.x
  docs/angular/api-cypress/executors/cypress.md
  docs/node/api-cypress/executors/cypress.md
  docs/react/api-cypress/executors/cypress.md
  packages/cypress/src/executors/cypress/cypress.impl.spec.ts
  packages/cypress/src/executors/cypress/cypress.impl.ts
  packages/cypress/src/executors/cypress/schema.json
Labels: scope: testing tools

#6769 chore(nxdev): improve colours on website according to latest design
  nx-dev/feature-doc-viewer/src/lib/sidebar.tsx
  nx-dev/feature-search/src/lib/algolia-search.global.css
  nx-dev/nx-dev/pages/index.tsx
  nx-dev/nx-dev/pages/node.tsx
  nx-dev/nx-dev/public/documentation/latest/angular/api-workspace/executors/run-script.md
  nx-dev/nx-dev/public/documentation/latest/angular/cli/affected.md
  nx-dev/nx-dev/public/documentation/latest/angular/cli/print-affected.md
  nx-dev/nx-dev/public/documentation/latest/angular/cli/run-many.md
  nx-dev/nx-dev/public/documentation/latest/angular/guides/configuration.md
  nx-dev/nx-dev/public/documentation/latest/angular/guides/modern-angular/karma-to-jest.md
  nx-dev/nx-dev/public/documentation/latest/angular/guides/setup-incremental-builds.md
  nx-dev/nx-dev/public/documentation/latest/node/api-workspace/executors/run-script.md
  nx-dev/nx-dev/public/documentation/latest/node/cli/affected.md
  nx-dev/nx-dev/public/documentation/latest/node/cli/print-affected.md
  nx-dev/nx-dev/public/documentation/latest/node/cli/run-many.md
  nx-dev/nx-dev/public/documentation/latest/node/getting-started/intro.md
  nx-dev/nx-dev/public/documentation/latest/react/api-workspace/executors/run-script.md
  nx-dev/nx-dev/public/documentation/latest/react/cli/affected.md
  nx-dev/nx-dev/public/documentation/latest/react/cli/print-affected.md
  nx-dev/nx-dev/public/documentation/latest/react/cli/run-many.md
  nx-dev/nx-dev/public/documentation/latest/shared/incremental-builds.md
  nx-dev/nx-dev/tailwind.config.js
  nx-dev/ui/common/src/lib/feature-list.tsx
  nx-dev/ui/common/src/lib/footer.tsx
  nx-dev/ui/common/src/lib/inline-command.tsx
  nx-dev/ui/common/src/lib/nx-users-showcase.tsx
Labels: scope: misc

#7060 chore(linter): upgrade typescript-eslint to latest version
  package.json
  packages/angular/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/cypress/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/eslint-plugin-nx/package.json
  packages/linter/migrations.json
  packages/linter/src/utils/versions.ts
  packages/nest/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  yarn.lock
Labels: scope: linter

#7073 docs(testing): add missing cypress.md
  nx-dev/nx-dev/public/documentation/latest/angular/api-cypress/executors/cypress.md
  nx-dev/nx-dev/public/documentation/latest/node/api-cypress/executors/cypress.md
  nx-dev/nx-dev/public/documentation/latest/react/api-cypress/executors/cypress.md
Labels: type: docs

#7075 docs(nxdev): remove CTA for nx conf from index and adapt content
  nx-dev/feature-conf/src/lib/conf-workshop.tsx
  nx-dev/nx-dev/pages/conf.tsx
  nx-dev/nx-dev/pages/index.tsx
Labels: scope: misc

#6735 chore(repo): switch on multiple main jobs on circleci
  .circleci/config.yml
  e2e/web/src/file-server.test.ts
Labels: scope: repo

#6502 fix(storybook): warn if skipping generating files in .storybook folder
  packages/storybook/src/generators/configuration/configuration.ts
Labels: scope: storybook

#7113 feat(linter): show files involved in circular dependency
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.spec.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts
  packages/workspace/src/utils/graph-utils.ts
Labels: scope: linter

#7126 fix(angular): remove extra comma when generating application with --inlineTemplate
  packages/angular/src/generators/application/lib/update-component-template.ts
Labels: scope: angular

#7132 fix(angular): update ng-package.json dest property when moving a library
  packages/angular/src/generators/move/lib/update-ng-package.ts
  packages/angular/src/generators/move/move.spec.ts
  packages/angular/src/generators/move/move.ts
Labels: scope: angular

#7143 fix(linter): improve error message on no matching dependency restriction
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.spec.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts
Labels: scope: linter

#7168 chore(repo): exclude projects running on multiple OSs
  .circleci/config.yml
Labels: scope: repo

#7171 chore(linter): optimize e2e tests
  e2e/linter/src/linter.test.ts
Labels: scope: linter
