Repository nrwl/nx, pull requests merged in 2021-07, with the labels that each got.

#6209 feat(angular): init mfe generator
  docs/angular/api-angular/generators/setup-mfe.md
  docs/angular/api-nx-devkit/index.md
  docs/map.json
  docs/node/api-angular/generators/setup-mfe.md
  docs/node/api-nx-devkit/index.md
  docs/react/api-angular/generators/setup-mfe.md
  docs/react/api-nx-devkit/index.md
  docs/shared/angular-plugin.md
  package.json
  packages/angular/collection.json
  packages/angular/generators.ts
  packages/angular/src/generators/setup-mfe/__snapshots__/setup-mfe.spec.ts.snap
  packages/angular/src/generators/setup-mfe/files/webpack.config.js__tmpl__
  packages/angular/src/generators/setup-mfe/files/webpack.prod.config.js__tmpl__
  packages/angular/src/generators/setup-mfe/lib/add-implicit-deps.ts
  packages/angular/src/generators/setup-mfe/lib/change-build-target.ts
  packages/angular/src/generators/setup-mfe/lib/fix-bootstrap.ts
  packages/angular/src/generators/setup-mfe/lib/generate-config.ts
  packages/angular/src/generators/setup-mfe/lib/get-remotes-with-ports.ts
  packages/angular/src/generators/setup-mfe/lib/index.ts
  packages/angular/src/generators/setup-mfe/lib/setup-serve-target.ts
  packages/angular/src/generators/setup-mfe/schema.d.ts
  packages/angular/src/generators/setup-mfe/schema.json
  packages/angular/src/generators/setup-mfe/setup-mfe.compat.ts
  packages/angular/src/generators/setup-mfe/setup-mfe.spec.ts
  packages/angular/src/generators/setup-mfe/setup-mfe.ts
  packages/devkit/src/generators/project-configuration.ts
Labels: scope: angular

#6226 chore(core): remove reference to parse json with comments
  packages/workspace/src/core/project-graph/build-dependencies/explicit-package-json-dependencies.ts
  packages/workspace/src/core/target-project-locator.ts
  packages/workspace/src/utilities/fileutils.ts
  packages/workspace/src/utils/fileutils.ts
Labels: scope: core

#6225 chore(repo): trigger full check when circleci config changes
  nx.json
Labels: scope: repo

#6244 chore(repo): remove flaky headless param from e2e test
  e2e/nx-plugin/src/nx-plugin.test.ts
Labels: scope: repo

#6241 cleanup(core): replace deprecated usage of appRootPath
  packages/cypress/src/webpack/require-shim.ts
  packages/eslint-plugin-nx/src/configs/typescript.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin-nx/tests/rules/enforce-module-boundaries.spec.ts
  packages/gatsby/plugins/nx-gatsby-ext-plugin/gatsby-node.ts
  packages/jest/src/migrations/update-10-0-0/update-jest-configs.ts
  packages/linter/src/executors/eslint/hasher.ts
  packages/next/plugins/with-nx.ts
  packages/next/src/utils/generate-globs.ts
  packages/node/src/webpack/require-shim.ts
  packages/nx-plugin/src/utils/testing-utils/nx-project.ts
  packages/react/plugins/bundle-babel.ts
  packages/web/src/webpack/require-shim.ts
  packages/workspace/src/command-line/dep-graph.ts
  packages/workspace/src/command-line/format.ts
  packages/workspace/src/command-line/list.ts
  packages/workspace/src/command-line/report.ts
  packages/workspace/src/command-line/workspace-generators.ts
  packages/workspace/src/command-line/workspace-results.ts
  packages/workspace/src/core/affected-project-graph/affected-project-graph.spec.ts
  packages/workspace/src/core/affected-project-graph/locators/tsconfig-json-changes.ts
  packages/workspace/src/core/file-utils.ts
  packages/workspace/src/core/hasher/file-hasher.ts
  packages/workspace/src/core/nx-deps/nx-deps-cache.ts
  packages/workspace/src/core/project-graph/build-dependencies/explicit-package-json-dependencies.spec.ts
  packages/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.spec.ts
  packages/workspace/src/core/project-graph/build-nodes/npm-packages.ts
  packages/workspace/src/core/project-graph/project-graph.spec.ts
  packages/workspace/src/core/project-graph/project-graph.ts
  packages/workspace/src/core/target-project-locator.spec.ts
  packages/workspace/src/core/target-project-locator.ts
  packages/workspace/src/generators/move/lib/update-project-root-files.ts
  packages/workspace/src/generators/move/lib/update-storybook-config.ts
  packages/workspace/src/tasks-runner/batch-worker.ts
  packages/workspace/src/tasks-runner/cache.ts
  packages/workspace/src/tasks-runner/forked-process-task-runner.ts
  packages/workspace/src/tasks-runner/run-command.ts
  packages/workspace/src/tasks-runner/task-orchestrator.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.spec.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts
  packages/workspace/src/utils/app-root.ts
  packages/workspace/src/utils/rules/format-files.spec.ts
  packages/workspace/src/utils/rules/format-files.ts
Labels: scope: core

#6246 fix(nx-plugin): export compatibility e2e builder in a separate file
  e2e/nx-plugin/src/nx-plugin.test.ts
  packages/nx-plugin/executors.json
  packages/nx-plugin/src/executors/e2e/compat.ts
  packages/nx-plugin/src/executors/e2e/e2e.impl.ts
Labels: scope: plugins, type: bug

#6262 chore(repo): run cypress tests on merge to master
  .circleci/config.yml
  .github/workflows/e2e-matrix.yml
  e2e/utils/index.ts
Labels: scope: repo

#6291 fix(repo): remove stale tags
  .circleci/config.yml
  scripts/circleci/tag-successful-build.sh
Labels: scope: repo

#6302 feat(storybook): story generator takes into account actions
  packages/react/src/generators/component-story/component-story.spec.ts
  packages/react/src/generators/component-story/component-story.ts
  packages/react/src/generators/component-story/files/__componentFileName__.stories.__fileExt__
Labels: scope: storybook

#6313 fix(core): update root jest config with move generator
  packages/workspace/src/generators/move/lib/update-jest-config.spec.ts
  packages/workspace/src/generators/move/lib/update-jest-config.ts
Labels: scope: core

#6316 chore(core): refactor createProjectGraph to be async, deprecate sync usage
  packages/angular/src/builders/webpack-browser/webpack-browser.impl.ts
  packages/angular/src/executors/delegate-build/delegate-build.impl.ts
  packages/angular/src/executors/ng-packagr-lite/ng-packagr-lite.impl.spec.ts
  packages/angular/src/executors/package/package.impl.spec.ts
  packages/angular/src/executors/package/package.impl.ts
  packages/angular/src/migrations/update-10-5-0/add-template-support-and-presets-to-eslint.spec.ts
  packages/angular/src/migrations/update-10-5-0/add-template-support-and-presets-to-eslint.ts
  packages/next/src/executors/build/build.impl.ts
  packages/next/src/executors/build/lib/create-package-json.ts
  packages/next/src/executors/export/export.impl.ts
  packages/next/src/executors/server/server.impl.ts
  packages/node/src/executors/build/build.impl.spec.ts
  packages/node/src/executors/build/build.impl.ts
  packages/node/src/executors/package/package.impl.spec.ts
  packages/node/src/executors/package/package.impl.ts
  packages/react/src/migrations/update-9-4-0/babelrc-9-4-0.spec.ts
  packages/react/src/migrations/update-9-4-0/babelrc-9-4-0.ts
  packages/web/src/executors/build/build.impl.ts
  packages/web/src/executors/dev-server/dev-server.impl.ts
  packages/web/src/executors/package/package.impl.ts
  packages/web/src/migrations/update-11-5-2/create-babelrc-for-workspace-libs.spec.ts
  packages/web/src/migrations/update-11-5-2/create-babelrc-for-workspace-libs.ts
  packages/workspace/src/command-line/affected.ts
  packages/workspace/src/command-line/dep-graph.ts
  packages/workspace/src/command-line/format.ts
  packages/workspace/src/command-line/lint.ts
  packages/workspace/src/command-line/run-many.ts
  packages/workspace/src/command-line/run-one.ts
  packages/workspace/src/core/affected-project-graph/affected-project-graph.spec.ts
  packages/workspace/src/core/project-graph/index.ts
  packages/workspace/src/core/project-graph/project-graph.spec.ts
  packages/workspace/src/core/project-graph/project-graph.ts
  packages/workspace/src/generators/remove/lib/check-dependencies.spec.ts
  packages/workspace/src/generators/remove/lib/check-dependencies.ts
  packages/workspace/src/generators/remove/remove.ts
  packages/workspace/src/utilities/create-project-graph-from-tree.ts
  packages/workspace/src/utils/ast-utils.ts
Labels: scope: core

#6371 chore(repo): improve cross package manager testing
  e2e/cypress/src/cypress.test.ts
  e2e/gatsby/src/gatsby.test.ts
  e2e/utils/index.ts
  e2e/workspace/src/create-nx-workspace.test.ts
  e2e/workspace/src/custom-layout.test.ts
Labels: scope: repo

#6372 chore(repo): use tagless approach to finding successful run commit sha
  .circleci/config.yml
  scripts/circleci/find-successful-workflow.js
  scripts/circleci/get-last-successful-tag.sh
  scripts/circleci/get-successful-run.sh
  scripts/circleci/tag-successful-build.sh
Labels: scope: repo

#6416 chore(repo): remove cypress package from e2e default packages
  e2e/utils/index.ts
Labels: scope: repo

#6426 docs(core): fix outdated references to ng in react and angular
  docs/angular/examples/react-and-angular.md
  nx-dev/nx-dev/public/documentation/latest/angular/examples/react-and-angular.md
  nx-dev/nx-dev/public/documentation/previous/angular/examples/react-and-angular.md
Labels: type: docs

#6385 chore(core): add readCachedProjectGraph and deprecate previous utility
  packages/angular/tailwind.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/next/tailwind.ts
  packages/react/tailwind.ts
  packages/workspace/src/core/project-graph/index.ts
  packages/workspace/src/core/project-graph/project-graph.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts
  packages/workspace/src/utilities/generate-globs.ts
  packages/workspace/src/utilities/project-graph-utils.spec.ts
  packages/workspace/src/utilities/project-graph-utils.ts
Labels: scope: core

#6427 fix(core): move generator should respect non-relative extends parts
  packages/workspace/src/generators/move/lib/update-eslintrc-json.spec.ts
  packages/workspace/src/generators/move/lib/update-eslintrc-json.ts
Labels: scope: core

#6428 fix(core): fix wrong create-nx-workspace tutorial link
  packages/create-nx-workspace/bin/create-nx-workspace.ts
Labels: type: bug

#6489 fix(core): ensure cache pathMappings always exist
  packages/workspace/src/core/nx-deps/nx-deps-cache.ts
Labels: scope: core, type: bug

#6490 fix(storybook): when migrating to 12.1 do not throw if project has no targets
  packages/storybook/src/migrations/update-12-1-0/fix-storybook-tsconfig.spec.ts
  packages/storybook/src/migrations/update-12-1-0/fix-storybook-tsconfig.ts
Labels: scope: storybook

#6491 feat(storybook): allow users to init storybook with more frameworks
  docs/angular/api-storybook/executors/storybook.md
  docs/node/api-storybook/executors/storybook.md
  docs/react/api-storybook/executors/storybook.md
  nx-dev/nx-dev/public/documentation/latest/angular/api-storybook/executors/storybook.md
  nx-dev/nx-dev/public/documentation/latest/node/api-storybook/executors/storybook.md
  nx-dev/nx-dev/public/documentation/latest/react/api-storybook/executors/storybook.md
  packages/storybook/src/executors/storybook/schema.json
  packages/storybook/src/executors/storybook/storybook.impl.ts
  packages/storybook/src/executors/utils.ts
  packages/storybook/src/generators/init/init.spec.ts
  packages/storybook/src/generators/init/init.ts
  packages/storybook/src/generators/init/schema.d.ts
  packages/storybook/src/generators/init/schema.json
  packages/storybook/src/utils/utilities.ts
Labels: scope: storybook

#6505 chore(repo): switch to using nx orb on circleci workflows
  .circleci/config.yml
  scripts/circleci/find-successful-workflow.js
  scripts/circleci/get-successful-run.sh
Labels: scope: repo

#6527 cleanup(core): remove last references to workspace appRootPath
  packages/node/src/utils/node.config.spec.ts
  packages/workspace/src/utilities/app-root.ts
  packages/workspace/src/utilities/plugins/plugin-capabilities.ts
  packages/workspace/src/utilities/typescript.ts
Labels: scope: core, type: cleanup

#6530 chore(repo): add missing members of the nx core team
  README.md
Labels: scope: repo, type: docs

#6522 cleanup(core): use isNpmProject and cleanup project graph utils
  packages/angular/src/migrations/update-10-5-0/add-template-support-and-presets-to-eslint.ts
  packages/react/src/migrations/update-9-4-0/babelrc-9-4-0.ts
  packages/workspace/src/core/affected-project-graph/locators/npm-packages.ts
  packages/workspace/src/core/file-graph/project-file-map.ts
  packages/workspace/src/core/normalize-nx-json.ts
  packages/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.ts
  packages/workspace/src/utilities/buildable-libs-utils.ts
  packages/workspace/src/utilities/create-package-json.ts
  packages/workspace/src/utilities/project-graph-utils.ts
  packages/workspace/src/utils/buildable-libs-utils.spec.ts
  packages/workspace/src/utils/buildable-libs-utils.ts
Labels: scope: core, type: cleanup

#6446 chore(core): refactor executors to always read from cached project graph
  packages/angular/src/builders/webpack-browser/webpack-browser.impl.ts
  packages/angular/src/executors/delegate-build/delegate-build.impl.ts
  packages/angular/src/executors/package/package.impl.ts
  packages/next/src/executors/build/build.impl.ts
  packages/next/src/executors/build/lib/create-package-json.ts
  packages/next/src/executors/export/export.impl.ts
  packages/next/src/executors/server/server.impl.ts
  packages/node/src/executors/build/build.impl.spec.ts
  packages/node/src/executors/build/build.impl.ts
  packages/node/src/executors/package/package.impl.spec.ts
  packages/node/src/executors/package/package.impl.ts
  packages/web/src/executors/build/build.impl.ts
  packages/web/src/executors/dev-server/dev-server.impl.ts
  packages/web/src/executors/package/package.impl.ts
Labels: scope: core

#6528 fix(core): target project locator should handle tsconfig paths fully
  packages/workspace/src/core/target-project-locator.spec.ts
  packages/workspace/src/core/target-project-locator.ts
Labels: scope: repo, type: enhancement
