Repository nrwl/nx, pull requests merged in 2021-05, with the labels that each got.

#4903 feat(angular): add support for a custom builder
  docs/angular/api-angular/executors/webpack-browser.md
  docs/node/api-angular/executors/webpack-browser.md
  docs/react/api-angular/executors/webpack-browser.md
  packages/angular/src/builders/webpack-browser/schema.json
  packages/angular/src/builders/webpack-browser/webpack-browser.impl.ts
Labels: scope: angular

#5359 fix(storybook): migration to update @storybook/* packages version
  packages/storybook/migrations.json
  packages/storybook/src/generators/init/__snapshots__/init.spec.ts.snap
  packages/storybook/src/migrations/update-11-6-0/update-storybook.spec.ts
  packages/storybook/src/migrations/update-11-6-0/update-storybook.ts
  packages/storybook/src/utils/versions.ts
Labels: scope: storybook

#5634 fix(core): add description to commands schema help
  docs/angular/api-workspace/executors/run-commands.md
  docs/node/api-workspace/executors/run-commands.md
  docs/react/api-workspace/executors/run-commands.md
  packages/workspace/src/executors/run-commands/schema.json
Labels: scope: core, type: bug

#5698 chore(misc): temporarily disable node 15 on matrix actions
  .github/workflows/e2e-matrix.yml
Labels: scope: misc

#5684 Revert "feat(angular): add support for a target Builder (#4903)"
  docs/angular/api-angular/executors/webpack-browser.md
  docs/node/api-angular/executors/webpack-browser.md
  docs/react/api-angular/executors/webpack-browser.md
  e2e/angular/src/storybook.test.ts
  packages/angular/src/builders/webpack-browser/schema.json
  packages/angular/src/builders/webpack-browser/webpack-browser.impl.ts
Labels: scope: angular

#5700 chore(misc): upgrade verdaccio and handle sigkill
  package.json
  scripts/local-registry.sh
  yarn.lock
Labels: scope: misc

#5510 feat(nextjs): allow custom server to be written in TypeScript
  e2e/next/src/next.test.ts
  e2e/utils/index.ts
  packages/next/package.json
  packages/next/src/executors/server/lib/custom-server.ts
  packages/next/src/executors/server/lib/tsnode-register.ts
Labels: scope: nextjs

#5576 feat(linter): optimize lint performance. resolves #5210
  packages/devkit/src/project-graph/interfaces.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin-nx/tests/rules/enforce-module-boundaries.spec.ts
  packages/workspace/src/command-line/affected.ts
  packages/workspace/src/command-line/run-many.ts
  packages/workspace/src/core/file-utils.ts
  packages/workspace/src/core/project-graph/operators.ts
  packages/workspace/src/core/target-project-locator.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.spec.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts
  packages/workspace/src/utilities/fileutils.ts
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: scope: linter, type: enhancement

#5609 feat(angular): allow custom webpack config support for webpack-browse…
  packages/angular/ng-package.json
  packages/angular/package.json
  packages/angular/src/builders/webpack-browser/schema.json
  packages/angular/src/builders/webpack-browser/webpack-browser.impl.ts
  scripts/depcheck/discrepancies.ts
  scripts/depcheck/index.ts
Labels: scope: angular

#5703 chore(misc): updated verdaccio config files and local registry scripts
  .verdaccio/config.yml
  package.json
  scripts/e2e-build-package-publish.ts
  scripts/e2e-start-local-registry.js
  scripts/local-registry.sh
  scripts/local-registry/config.yml
Labels: scope: misc

#5714 fix(core): update project's eslintrc and readme on move
  packages/workspace/src/generators/move/lib/update-eslintrc-json.spec.ts
  packages/workspace/src/generators/move/lib/update-eslintrc-json.ts
  packages/workspace/src/generators/move/lib/update-readme.spec.ts
  packages/workspace/src/generators/move/lib/update-readme.ts
  packages/workspace/src/generators/move/move.ts
Labels: scope: core, type: bug

#5721 fix(linter): improve error message for circular reference
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin-nx/tests/rules/enforce-module-boundaries.spec.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.spec.ts
  packages/workspace/src/tslint/nxEnforceModuleBoundariesRule.ts
Labels: scope: linter, type: bug

#5725 feat(repo): revert i/o functions to fs-extra
  scripts/e2e-build-package-publish.ts
Labels: scope: repo

#5727 feat(repo): cleanup storage for matrix tests
  .github/workflows/e2e-matrix.yml
Labels: scope: repo

#5788 fix(angular): disable double module update on move
  packages/angular/src/generators/move/lib/update-module-name.spec.ts
  packages/angular/src/generators/move/lib/update-module-name.ts
Labels: scope: angular, type: bug

#5782 feat(repo): fix failing yarn and pnpm
  .github/workflows/e2e-matrix.yml
  e2e/utils/index.ts
  package.json
  scripts/e2e-build-package-publish.ts
Labels: scope: repo, type: bug

#5711 fix(testing): enable and fix several disabled unit and e2e tests
  e2e/angular/src/ng-add.test.ts
  e2e/angular/src/storybook.test.ts
  e2e/node/src/node.test.ts
  e2e/storybook/src/storybook.test.ts
  e2e/utils/index.ts
  e2e/workspace/src/workspace-aux-commands.test.ts
  packages/angular/spec/testing-utils.spec.ts
  packages/angular/src/schematics/application/application.spec.ts
  packages/react/src/generators/stories/stories-lib.spec.ts
  packages/storybook/jest.config.js
  packages/storybook/src/executors/build-storybook/build-storybook.impl.spec.ts
  packages/storybook/src/executors/storybook/storybook.impl.spec.ts
Labels: scope: repo
