Repository nrwl/nx, pull requests merged in 2022-05, with the labels that each got.

#10095 docs(core): update getting-started links to caching section
  docs/shared/getting-started/nx-and-angular.md
  docs/shared/getting-started/nx-and-react.md
Labels: type: docs

#10007 feat(core): switch cnw ci option to be single-select
  docs/generated/cli/create-nx-workspace.md
  e2e/utils/index.ts
  e2e/workspace-create/src/create-nx-workspace.test.ts
  packages/create-nx-workspace/bin/create-nx-workspace.ts
Labels: scope: core

#10104 docs(nxdev): bump algolia hits displayed
  nx-dev/feature-search/src/lib/algolia-search.tsx
Labels: type: docs

#10105 docs(nxdev): remove nx conf lite banner announcement
  nx-dev/nx-dev/pages/_app.tsx
Labels: type: docs

#10108 docs(nxdev): add nx conf lite video replay link
  nx-dev/nx-dev/pages/conf.tsx
Labels: type: docs

#10109 docs(nxdev): remove pulsating dots for conf on header
  nx-dev/ui-common/src/lib/header.tsx
Labels: type: docs

#10139 docs(nxdev): display specific nx package name exception
  nx-dev/feature-package-schema-viewer/src/lib/get-public-package-name.ts
  nx-dev/feature-package-schema-viewer/src/lib/get-schema-view-model.ts
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-list.tsx
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-viewer.tsx
  scripts/documentation/open-graph/generate-images.ts
Labels: type: docs

#10180 fix(testing): 14.0.0 jest migration errors when additional configurations are specified
  packages/jest/src/migrations/update-14-0-0/update-jest-config-ext.spec.ts
  packages/jest/src/migrations/update-14-0-0/update-jest-config-ext.ts
Labels: scope: testing tools

#10189 docs(nxdev): show overview on package list view
  docs/generated/packages/add-nx-to-monorepo.json
  docs/generated/packages/angular.json
  docs/generated/packages/cli.json
  docs/generated/packages/cra-to-nx.json
  docs/generated/packages/create-nx-plugin.json
  docs/generated/packages/create-nx-workspace.json
  docs/generated/packages/cypress.json
  docs/generated/packages/detox.json
  docs/generated/packages/devkit.json
  docs/generated/packages/eslint-plugin-nx.json
  docs/generated/packages/express.json
  docs/generated/packages/jest.json
  docs/generated/packages/js.json
  docs/generated/packages/linter.json
  docs/generated/packages/make-angular-cli-faster.json
  docs/generated/packages/nest.json
  docs/generated/packages/next.json
  docs/generated/packages/node.json
  docs/generated/packages/nx-plugin.json
  docs/generated/packages/nx.json
  docs/generated/packages/react-native.json
  docs/generated/packages/react.json
  docs/generated/packages/storybook.json
  docs/generated/packages/tao.json
  docs/generated/packages/web.json
  docs/generated/packages/workspace.json
  docs/map.json
  docs/shared/angular-plugin.md
  docs/shared/cypress-plugin.md
  docs/shared/detox-plugin.md
  docs/shared/eslint-plugin-nx.md
  docs/shared/express-plugin.md
  docs/shared/guides/storybook/plugin-overview.md
  docs/shared/jest-plugin.md
  docs/shared/js-plugin.md
  docs/shared/linter-plugin.md
  docs/shared/nest-plugin.md
  docs/shared/next-plugin.md
  docs/shared/node-plugin.md
  docs/shared/nx-plugin.md
  docs/shared/react-native-plugin.md
  docs/shared/react-plugin.md
  docs/shared/web-plugin.md
  docs/shared/workspace-plugin.md
  nx-dev/feature-package-schema-viewer/src/lib/get-schema-view-model.ts
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-list.tsx
  nx-dev/feature-package-schema-viewer/src/lib/ui/markdown/markdown.tsx
  nx-dev/feature-package-schema-viewer/src/lib/ui/markdown/renderers/transform-image-path.ts
  nx-dev/models-package/src/lib/package.models.ts
  scripts/documentation/package-schemas/package-metadata.ts
Labels: type: docs

#10190 docs(nxdev): add redirect for overview urls
  nx-dev/nx-dev/next.config.js
  nx-dev/nx-dev/redirect-rules.config.js
Labels: type: docs

#10155 fix(core): list only changed files on format:write log
  packages/nx/src/command-line/format.ts
Labels: scope: core

#10247 docs(nxdev): support older generic paths
  nx-dev/nx-dev/next.config.js
Labels: type: docs

#10267 docs(nxdev): change header plugins link to community
  nx-dev/ui-common/src/lib/header.tsx
Labels: type: docs

#10272 docs(nxdev): generate menu api
  docs/generated/packages/angular.json
  docs/generated/packages/cli.json
  docs/generated/packages/cypress.json
  docs/generated/packages/detox.json
  docs/generated/packages/eslint-plugin-nx.json
  docs/generated/packages/express.json
  docs/generated/packages/jest.json
  docs/generated/packages/js.json
  docs/generated/packages/linter.json
  docs/generated/packages/nest.json
  docs/generated/packages/next.json
  docs/generated/packages/node.json
  docs/generated/packages/nx-plugin.json
  docs/generated/packages/react-native.json
  docs/generated/packages/react.json
  docs/generated/packages/storybook.json
  docs/generated/packages/web.json
  docs/generated/packages/workspace.json
  docs/map.json
  nx-dev/data-access-documents/src/lib/documents.api.ts
  nx-dev/data-access-documents/src/lib/menu.api.ts
  nx-dev/data-access-documents/src/node.index.ts
  nx-dev/data-access-menu/.babelrc
  nx-dev/data-access-menu/.eslintrc.json
  nx-dev/data-access-menu/README.md
  nx-dev/data-access-menu/jest.config.ts
  nx-dev/data-access-menu/project.json
  nx-dev/data-access-menu/src/index.ts
  nx-dev/data-access-menu/src/lib/menu.api.ts
  nx-dev/data-access-menu/src/lib/menu.utils.ts
  nx-dev/data-access-menu/tsconfig.json
  nx-dev/data-access-menu/tsconfig.lib.json
  nx-dev/data-access-menu/tsconfig.spec.json
  nx-dev/data-access-packages/src/lib/packages.api.ts
  nx-dev/models-document/src/lib/documents.models.ts
  nx-dev/models-package/src/lib/package.models.ts
  nx-dev/nx-dev/lib/api.ts
  scripts/documentation/map-link-checker.ts
  scripts/documentation/open-graph/generate-images.ts
  scripts/documentation/package-schemas/package-metadata.ts
  tsconfig.base.json
  workspace.json
Labels: type: docs

#10273 docs(nxdev): update packages documentation
  docs/generated/packages/cli.json
Labels: type: docs

#10283 docs(nxdev): add nx conf lite youtube links
  nx-dev/ui-conference/src/lib/conf-schedule-short.tsx
Labels: type: docs

#10288 docs(nxdev): update nx-plugin redirect rule
  nx-dev/nx-dev/redirect-rules.config.js
Labels: type: docs

#10372 docs(nxdev): add e2e tests on packages & additional references pages
  nx-dev/nx-dev-e2e/project.json
  nx-dev/nx-dev-e2e/src/integration/additional-api-references.spec.ts
  nx-dev/nx-dev-e2e/src/integration/helpers.ts
  nx-dev/nx-dev-e2e/src/integration/packages.spec.ts
Labels: type: docs

#10378 docs(nxdev): rename api references to official plugins in sidebar
  nx-dev/data-access-menu/src/lib/menu.utils.ts
Labels: type: docs

#10289 docs(nxdev): add nx-cloud documentation content
  docs/map.json
  docs/nx-cloud/account/access-tokens.md
  docs/nx-cloud/account/billing.md
  docs/nx-cloud/account/encryption.md
  docs/nx-cloud/account/google-auth.md
  docs/nx-cloud/account/google_oauth.png
  docs/nx-cloud/account/require_google_signin.png
  docs/nx-cloud/account/scenarios.md
  docs/nx-cloud/account/users.md
  docs/nx-cloud/intro/distributed-caching.md
  docs/nx-cloud/intro/distributed-task-execution.md
  docs/nx-cloud/intro/nx-cloud.md
  docs/nx-cloud/private/advanced-config.md
  docs/nx-cloud/private/auth-github.md
  docs/nx-cloud/private/auth-gitlab.md
  docs/nx-cloud/private/auth-single-admin.md
  docs/nx-cloud/private/deploy-aws.md
  docs/nx-cloud/private/deploy-azure.md
  docs/nx-cloud/private/deploy-kubernetes.md
  docs/nx-cloud/private/get-started.md
  docs/nx-cloud/private/github.md
  docs/nx-cloud/private/images/admin_hidden_login.png
  docs/nx-cloud/private/images/github-username.png
  docs/nx-cloud/private/images/github_auth_step_1.png
  docs/nx-cloud/private/images/github_auth_step_2.png
  docs/nx-cloud/private/images/github_auth_step_3.png
  docs/nx-cloud/private/images/github_auth_step_4.png
  docs/nx-cloud/private/images/github_auth_step_5.png
  docs/nx-cloud/private/images/github_auth_step_6.png
  docs/nx-cloud/private/images/github_auth_step_7.png
  docs/nx-cloud/private/images/gitlab-username.png
  docs/nx-cloud/private/images/gitlab_step_1.png
  docs/nx-cloud/private/images/gitlab_step_2.png
  docs/nx-cloud/private/images/gitlab_step_3.png
  docs/nx-cloud/private/images/gitlab_step_4.png
  docs/nx-cloud/private/images/gitlab_step_5.png
  docs/nx-cloud/private/images/invite_members.png
  docs/nx-cloud/private/images/main_user_login.png
  docs/nx-cloud/private/images/private-cloud-github-integration-add-webhook.png
  docs/nx-cloud/private/images/private-cloud-github-integration-generate-token.png
  docs/nx-cloud/private/images/webhook-trigger-events.png
  docs/nx-cloud/private/images/webhook-trigger-pull-requests.png
  docs/nx-cloud/reference/access-tokens.png
  docs/nx-cloud/reference/config.md
  docs/nx-cloud/reference/env-vars.md
  docs/nx-cloud/reference/release-notes.md
  docs/nx-cloud/reference/server-api.md
  docs/nx-cloud/reference/swagger-preview.png
  docs/nx-cloud/set-up/github.md
  docs/nx-cloud/set-up/record-commands.md
  docs/nx-cloud/set-up/record-hello-world.png
  docs/nx-cloud/set-up/record-report.png
  docs/nx-cloud/set-up/record-workspace-lint.png
  docs/nx-cloud/set-up/set-up-caching.md
  docs/nx-cloud/set-up/set-up-dte.md
Labels: type: docs

#10379 docs(nxdev): do some cleanup on the feature-doc-viewer lib
  nx-dev/feature-doc-viewer/src/lib/content.tsx
  nx-dev/feature-doc-viewer/src/lib/doc-viewer.tsx
  nx-dev/feature-doc-viewer/src/lib/sidebar.tsx
Labels: type: docs

#10381 docs(nxdev): harmonize jest config between libs
  nx-dev/data-access-documents/jest.config.ts
  nx-dev/data-access-documents/src/test-setup.ts
  nx-dev/data-access-packages/jest.config.ts
  nx-dev/data-access-packages/src/test-setup.ts
  nx-dev/feature-analytics/jest.config.ts
  nx-dev/feature-doc-viewer/jest.config.ts
  nx-dev/feature-doc-viewer/src/test-setup.ts
  nx-dev/feature-package-schema-viewer/jest.config.ts
  nx-dev/feature-search/jest.config.ts
  nx-dev/models-document/jest.config.ts
  nx-dev/models-menu/jest.config.ts
  nx-dev/models-package/jest.config.ts
  nx-dev/nx-dev/jest.config.ts
  nx-dev/ui-commands/jest.config.ts
  nx-dev/ui-common/jest.config.ts
  nx-dev/ui-community/jest.config.ts
  nx-dev/ui-conference/jest.config.ts
  nx-dev/ui-home/jest.config.ts
  nx-dev/ui-member-card/jest.config.ts
  nx-dev/ui-sponsor-card/jest.config.ts
Labels: type: docs

#10371 fix(linter): do not remap paths that cannot be matched on fix
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
Labels: scope: linter

#10365 fix(linter): make entry point check for ts paths more specific
  packages/eslint-plugin-nx/src/utils/ast-utils.ts
Labels: scope: linter

#10401 docs(nxdev): add nx console redirect rule
  nx-dev/nx-dev/next.config.js
Labels: type: docs

#10388 fix(core): include types/node in deps when adding workspace-generator
  packages/workspace/src/generators/workspace-generator/workspace-generator.ts
Labels: scope: core

#10456 docs(nxdev): add nx workshop event banner
  nx-dev/nx-dev/pages/_app.tsx
  nx-dev/ui-common/src/lib/announcement-banner.tsx
Labels: type: docs

#10471 docs(nxdev): add some vertical spacing on home buttons in mobile
  lerna.json
  nx-dev/nx-dev/pages/index.tsx
Labels: type: docs

#10425 fix(nx-plugin): handle nx.json without npmScope during plugin generation
  packages/nx-plugin/src/generators/plugin/plugin.spec.ts
  packages/nx-plugin/src/generators/plugin/plugin.ts
Labels: scope: plugins

#10522 fix(core): ensure pnpm v7 install when peer deps are missing
  e2e/utils/index.ts
  packages/workspace/src/generators/workspace/workspace.ts
Labels: scope: repo
