Repository nrwl/nx, pull requests merged in 2022-10, with the labels that each got.

#12372 docs(nxdev): add /docs redirect rule
  nx-dev/nx-dev/next.config.js
Labels: type: docs

#12373 docs(core): update banner image
  README.md
  images/nx-dark.svg
  images/nx-light.svg
Labels: type: docs

#12374 docs(nxdev): add new social banner
  nx-dev/nx-dev/pages/_app.tsx
  nx-dev/nx-dev/pages/community.tsx
  nx-dev/nx-dev/pages/index.tsx
  nx-dev/nx-dev/pages/packages.tsx
  nx-dev/nx-dev/public/images/nx-media.jpg
Labels: type: docs

#12396 docs(nxdev): remove unused card list component
  nx-dev/ui-markdoc/src/index.ts
  nx-dev/ui-markdoc/src/lib/tags/card-list.component.tsx
  nx-dev/ui-markdoc/src/lib/tags/card-list.schema.ts
Labels: type: docs

#12399 docs(nxdev): add install nx console button
  docs/shared/core-features/integrate-with-editors.md
  nx-dev/ui-markdoc/src/index.ts
  nx-dev/ui-markdoc/src/lib/tags/install-nx-console.component.tsx
  nx-dev/ui-markdoc/src/lib/tags/install-nx-console.schema.ts
  nx-dev/ui-markdoc/src/lib/tags/vs-code-ad.component.tsx
  nx-dev/ui-markdoc/src/lib/tags/vs-code-ad.schema.ts
Labels: type: docs

#12404 docs(nxdev): add video type on card markdown component
  nx-dev/ui-markdoc/src/lib/tags/cards.component.tsx
Labels: type: docs

#12405 docs(nxdev): add title attributed as required for callouts
  nx-dev/ui-markdoc/src/lib/tags/callout.schema.ts
Labels: type: docs

#12410 docs(nxdev): update links in plugins tab
  nx-dev/ui-home/src/lib/extensible-and-integrated/plugins-tab.tsx
Labels: type: docs

#12409 docs(core): remove logo images
  docs/generated/packages/angular.json
  docs/generated/packages/cypress.json
  docs/generated/packages/detox.json
  docs/generated/packages/esbuild.json
  docs/generated/packages/eslint-plugin-nx.json
  docs/generated/packages/express.json
  docs/generated/packages/jest.json
  docs/generated/packages/linter.json
  docs/generated/packages/nest.json
  docs/generated/packages/next.json
  docs/generated/packages/react-native.json
  docs/generated/packages/react.json
  docs/generated/packages/storybook.json
  docs/shared/angular-logo.png
  docs/shared/angular-plugin.md
  docs/shared/cypress-logo.png
  docs/shared/cypress-plugin.md
  docs/shared/detox-logo.png
  docs/shared/detox-plugin.md
  docs/shared/esbuild-logo.png
  docs/shared/esbuild-plugin.md
  docs/shared/eslint-logo.png
  docs/shared/eslint-plugin-nx.md
  docs/shared/express-logo.png
  docs/shared/express-plugin.md
  docs/shared/guides/storybook/plugin-angular.md
  docs/shared/guides/storybook/plugin-overview.md
  docs/shared/guides/storybook/plugin-react.md
  docs/shared/jest-logo.png
  docs/shared/jest-plugin.md
  docs/shared/nest-logo.png
  docs/shared/nest-plugin.md
  docs/shared/next-plugin.md
  docs/shared/nextjs-logo.png
  docs/shared/prettier-logo.png
  docs/shared/react-logo.png
  docs/shared/react-native-plugin.md
  docs/shared/react-plugin.md
  docs/shared/storybook-logo.png
Labels: type: docs

#12411 docs(nxdev): update code fences style
  nx-dev/ui-markdoc/src/lib/nodes/fence.component.tsx
Labels: type: docs

#12422 docs(nxdev): use current theme for monaco editor
  nx-dev/feature-package-schema-viewer/src/lib/schema-editor.tsx
  nx-dev/nx-dev/pages/_app.tsx
  nx-dev/ui-theme/src/lib/theme.provider.tsx
Labels: type: docs

#12427 docs(core): add new mental model schemas
  docs/shared/concepts/how-caching-works.md
  docs/shared/core-features/explore-graph.md
  docs/shared/mental-model.md
  docs/shared/mental-model/affected.png
  docs/shared/mental-model/affected.svg
  docs/shared/mental-model/cache.png
  docs/shared/mental-model/cache.svg
  docs/shared/mental-model/computation-hashing-v2.png
  docs/shared/mental-model/computation-hashing.svg
  docs/shared/mental-model/dte.png
  docs/shared/mental-model/dte.svg
  docs/shared/mental-model/project-graph-import.png
  docs/shared/mental-model/project-graph-updated.png
  docs/shared/mental-model/project-graph-updated.svg
  docs/shared/mental-model/project-graph.png
  docs/shared/mental-model/project-graph.svg
  docs/shared/mental-model/task-graph-big.png
  docs/shared/mental-model/task-graph-big.svg
  docs/shared/mental-model/task-graph-creation.png
  docs/shared/mental-model/task-graph-creation.svg
  docs/shared/mental-model/task-graph-execution.png
  docs/shared/mental-model/task-graph-execution.svg
  docs/shared/mental-model/task-graph-run.png
  docs/shared/mental-model/task-graph-run.svg
  docs/shared/mental-model/task-graph.png
  docs/shared/mental-model/task-graph.svg
  docs/shared/using-nx/affected.md
  scripts/documentation/internal-link-checker.ts
Labels: type: docs

#12430 chore(graph): enable dark mode for scrollbars
  graph/client/src/styles.scss
Labels: type: docs

#12185 feat(core): map lock file data to external dependencies
  e2e/js/src/js.test.ts
  e2e/node/src/node.test.ts
  packages/js/src/utils/versions.ts
  packages/nx/src/command-line/print-affected.ts
  packages/nx/src/config/project-graph.ts
  packages/nx/src/hasher/hasher.spec.ts
  packages/nx/src/hasher/hasher.ts
  packages/nx/src/project-graph/affected/affected-project-graph.spec.ts
  packages/nx/src/project-graph/affected/locators/workspace-projects.ts
  packages/nx/src/project-graph/build-project-graph.spec.ts
  packages/nx/src/project-graph/build-project-graph.ts
  packages/nx/src/project-graph/nx-deps-cache.spec.ts
  packages/nx/src/project-graph/nx-deps-cache.ts
  packages/nx/src/project-graph/project-graph.ts
  packages/nx/src/utils/lock-file/__snapshots__/lock-file.spec.ts.snap
  packages/nx/src/utils/lock-file/__snapshots__/npm.spec.ts.snap
  packages/nx/src/utils/lock-file/__snapshots__/pnpm.spec.ts.snap
  packages/nx/src/utils/lock-file/__snapshots__/yarn.spec.ts.snap
  packages/nx/src/utils/lock-file/lock-file-type.ts
  packages/nx/src/utils/lock-file/lock-file.spec.ts
  packages/nx/src/utils/lock-file/lock-file.ts
  packages/nx/src/utils/lock-file/npm.spec.ts
  packages/nx/src/utils/lock-file/npm.ts
  packages/nx/src/utils/lock-file/pnpm.spec.ts
  packages/nx/src/utils/lock-file/pnpm.ts
  packages/nx/src/utils/lock-file/utils.ts
  packages/nx/src/utils/lock-file/yarn.spec.ts
  packages/nx/src/utils/lock-file/yarn.ts
  packages/webpack/src/utils/versions.ts
Labels: type: feature, scope: core

#12443 docs(core): update pnpm command line
  docs/generated/cli/affected-apps.md
  docs/generated/cli/affected-graph.md
  docs/generated/cli/affected-libs.md
  docs/generated/cli/affected.md
  docs/generated/cli/connect-to-nx-cloud.md
  docs/generated/cli/daemon.md
  docs/generated/cli/format-check.md
  docs/generated/cli/format-write.md
  docs/generated/cli/graph.md
  docs/generated/cli/init.md
  docs/generated/cli/list.md
  docs/generated/cli/migrate.md
  docs/generated/cli/print-affected.md
  docs/generated/cli/repair.md
  docs/generated/cli/report.md
  docs/generated/cli/reset.md
  docs/generated/cli/run-many.md
  docs/generated/cli/workspace-generator.md
  docs/generated/cli/workspace-lint.md
  docs/generated/packages/nx.json
  scripts/documentation/generate-cli-data.ts
Labels: type: docs

#12445 docs(detox): add tab layout for detox install section
  docs/generated/packages/detox.json
  docs/shared/detox-plugin.md
Labels: type: docs

#12449 docs(express): add tab layout for express install section
  docs/generated/packages/express.json
  docs/shared/express-plugin.md
Labels: type: docs

#11594 feat(core): add workspace integrity check for package alignment
  packages/nx/src/command-line/lint.ts
  packages/nx/src/command-line/workspace-integrity-checks.spec.ts
  packages/nx/src/command-line/workspace-integrity-checks.ts
Labels: type: feature, scope: core

#12469 docs(nxdev): enable link on non collapsible section title
  nx-dev/ui-common/src/lib/sidebar.tsx
Labels: type: docs

#11443 feat(devkit): restrict addDependenciesToPackageJson to update versions only if greater than existing
  docs/generated/devkit/index.md
  docs/generated/packages/devkit.json
  packages/devkit/package.json
  packages/devkit/src/utils/package-json.spec.ts
  packages/devkit/src/utils/package-json.ts
Labels: target: next major version

#12476 docs(nxdev): improve sidebar category links resolution
  nx-dev/data-access-menu/src/lib/menu.utils.ts
  nx-dev/ui-common/src/lib/sidebar.tsx
Labels: type: docs

#12527 docs(nxdev): make nx conf date more prominent on agenda section
  nx-dev/ui-conference/src/lib/conf-schedule-short.tsx
Labels: type: docs

#12530 docs(nxdev): optimize doc template
  nx-dev/feature-doc-viewer/src/lib/doc-viewer.tsx
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-list.tsx
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-viewer.tsx
  nx-dev/nx-dev/pages/[...segments].tsx
Labels: type: docs

#12531 docs(nxdev): add documentation on front matter support
  docs/README.md
Labels: type: docs

#12534 feat(core): add support for npm v1 lock file parsing
  packages/nx/src/utils/lock-file/__fixtures__/npm.lock.ts
  packages/nx/src/utils/lock-file/__snapshots__/lock-file.spec.ts.snap
  packages/nx/src/utils/lock-file/__snapshots__/npm.spec.ts.snap
  packages/nx/src/utils/lock-file/lock-file.spec.ts
  packages/nx/src/utils/lock-file/npm.spec.ts
  packages/nx/src/utils/lock-file/npm.ts
Labels: type: feature, scope: core

#12258 fix(core): custom generators help should print relevant information
  e2e/nx-misc/src/workspace.test.ts
  packages/nx/src/command-line/nx-commands.ts
  packages/nx/src/command-line/workspace-generators.ts
Labels: type: bug, scope: core

#12536 chore(repo): cache cypress on windows nightly
  .github/workflows/e2e-windows.yml
Labels: scope: repo

#12539 docs(nxdev): update conf information
  nx-dev/ui-conference/src/lib/conf-schedule-short.tsx
  nx-dev/ui-conference/src/lib/conf-speakers.tsx
Labels: type: docs

#12537 chore(repo): bump underscore due to vulnerability
  package.json
  yarn.lock
Labels: scope: repo

#12515 fix(linter): check for all .eslintrc.* files when generating a package
  packages/linter/src/generators/utils/eslint-file.spec.ts
  packages/linter/src/generators/utils/eslint-file.ts
  packages/linter/src/migrations/update-15-0-0/add-eslint-inputs.spec.ts
  packages/linter/src/migrations/update-15-0-0/add-eslint-inputs.ts
Labels: type: bug, scope: linter

#12273 fix(testing): move to using cy.mount
  e2e/angular-extensions/src/cypress-component-tests.test.ts
  e2e/react/src/cypress-component-tests.test.ts
  packages/angular/src/generators/component-test/__snapshots__/component-test.spec.ts.snap
  packages/angular/src/generators/component-test/component-test.spec.ts
  packages/angular/src/generators/component-test/files/__componentFileName__.cy.ts__tpl__
  packages/angular/src/generators/cypress-component-configuration/__snapshots__/cypress-component-configuration.spec.ts.snap
  packages/angular/src/generators/cypress-component-configuration/files/cypress/support/commands.ts__tpl__
  packages/cypress/migrations.json
  packages/cypress/src/migrations/update-15-0-0/__snapshots__/update-cy-mount-usage.spec.ts.snap
  packages/cypress/src/migrations/update-15-0-0/update-cy-mount-usage.spec.ts
  packages/cypress/src/migrations/update-15-0-0/update-cy-mount-usage.ts
  packages/cypress/src/utils/ct-helpers.ts
  packages/react/src/generators/component-test/__snapshots__/component-test.spec.ts.snap
  packages/react/src/generators/component-test/files/__fileName__.cy__ext__
  packages/react/src/generators/cypress-component-configuration/__snapshots__/cypress-component-configuration.spec.ts.snap
  packages/react/src/generators/cypress-component-configuration/files/cypress/support/commands.ts__tpl__
Labels: scope: testing tools

#12574 docs(nxdev): add more contrast to light mode for fences
  nx-dev/ui-markdoc/src/lib/nodes/fence.component.tsx
Labels: type: docs

#12580 docs(nxdev): add redirect rule for add-to-monorepo recipe
  nx-dev/nx-dev/next.config.js
  nx-dev/nx-dev/redirect-rules.config.js
Labels: type: docs

#12581 docs(core): reformat doc with better code fences
  docs/shared/concepts/customizing-inputs.md
  docs/shared/concepts/how-caching-works.md
  docs/shared/concepts/how-project-graph-is-built.md
  docs/shared/concepts/task-pipeline-configuration.md
  docs/shared/core-features/cache-task-results.md
  docs/shared/core-features/enforce-project-boundaries.md
  docs/shared/core-features/run-tasks.md
  docs/shared/extending-nx/project-graph-plugins.md
  docs/shared/extending-nx/project-inference-plugins.md
  docs/shared/generators/creating-files.md
  docs/shared/generators/generator-options.md
  docs/shared/migration/adding-to-monorepo.md
  docs/shared/migration/lerna-and-nx.md
  docs/shared/migration/manual.md
  docs/shared/migration/migration-angular.md
  docs/shared/migration/migration-angularjs.md
  docs/shared/migration/migration-cra.md
  docs/shared/plugin-features/use-task-executors.md
Labels: type: docs

#12585 docs(core): reformat doc with better code fences
  docs/generated/packages/storybook.json
  docs/shared/guides/browser-support.md
  docs/shared/guides/customize-webpack.md
  docs/shared/guides/integrated-repo-folder-structure.md
  docs/shared/guides/misc-ngrx.md
  docs/shared/guides/module-federation/dynamic-mfe-angular.md
  docs/shared/guides/module-federation/faster-builds.md
  docs/shared/guides/module-federation/micro-frontend-architecture.md
  docs/shared/guides/react-native.md
  docs/shared/guides/setup-incremental-builds-angular.md
  docs/shared/guides/storybook/angular-browser-target.md
  docs/shared/guides/storybook/angular-configuring-styles.md
  docs/shared/guides/storybook/angular-storybook-compodoc.md
  docs/shared/guides/storybook/best-practices.md
  docs/shared/guides/storybook/migrate-webpack-final-angular.md
  docs/shared/guides/storybook/migrate-webpack-final-react.md
  docs/shared/guides/storybook/plugin-angular.md
  docs/shared/guides/storybook/plugin-overview.md
  docs/shared/guides/storybook/plugin-react.md
  docs/shared/guides/storybook/storybook-composition-setup.md
  docs/shared/guides/storybook/storybook-v6-angular.md
  docs/shared/guides/storybook/storybook-v6-react.md
  docs/shared/guides/use-environment-variables-in-angular.md
  docs/shared/guides/use-environment-variables-in-react.md
  docs/shared/guides/using-tailwind-css-in-react.md
  docs/shared/guides/using-tailwind-css-with-angular-projects.md
  docs/shared/guides/webpack-5.md
Labels: type: docs

#12588 docs(nxdev): optimize fence copy button
  nx-dev/ui-markdoc/src/lib/nodes/fence.component.tsx
  nx-dev/ui-markdoc/src/lib/nodes/fences/codeOutput.component.tsx
Labels: type: docs

#12611 docs(core): update react tutorial schemas
  docs/shared/react-tutorial/1-code-generation.md
  docs/shared/react-tutorial/2-project-graph.md
  docs/shared/react-tutorial/3-task-running.md
  docs/shared/react-tutorial/generator-syntax.png
  docs/shared/react-tutorial/generator-syntax.svg
  docs/shared/react-tutorial/requirements-diagram.png
  docs/shared/react-tutorial/requirements-diagram.svg
  docs/shared/react-tutorial/run-target-syntax.png
  docs/shared/react-tutorial/run-target-syntax.svg
Labels: type: docs

#12620 docs(core): update node tutorial schemas
  docs/shared/node-tutorial/requirements-diagram.svg
Labels: type: docs

#12622 docs(nxdev): add href for mobile menu sidebar
  nx-dev/ui-common/src/lib/sidebar.tsx
Labels: type: docs

#12623 docs(core): update node tutorial schemas
  docs/shared/node-tutorial/generator-syntax.svg
  docs/shared/node-tutorial/run-target-syntax.svg
  docs/shared/react-tutorial/run-target-syntax.svg
Labels: type: docs

#12625 docs(core): fix markup node tutorial
  docs/shared/node-tutorial/4-workspace-optimization.md
Labels: type: docs

#12626 docs(core): fix markup react tutorial
  docs/shared/react-tutorial/4-workspace-optimization.md
Labels: type: docs

#12552 fix(testing): run init generator in cypress-project when cypress is n…
  packages/cypress/src/generators/cypress-project/cypress-project.spec.ts
  packages/cypress/src/generators/cypress-project/cypress-project.ts
Labels: scope: testing tools

#12704 fix(core): bump nrwl/ci to 0.8
  docs/shared/monorepo-ci-github-actions.md
  packages/workspace/src/generators/ci-workflow/__snapshots__/ci-workflow.spec.ts.snap
  packages/workspace/src/generators/ci-workflow/files/github/.github/workflows/__workflowFileName__.yml__tmpl__
Labels: scope: core

#12629 docs(testing): add docs for cypress ct in angular and react packages
  docs/generated/packages/angular.json
  docs/generated/packages/react.json
  packages/angular/docs/component-test-examples.md
  packages/angular/docs/cypress-component-configuration-examples.md
  packages/angular/src/generators/component-test/schema.json
  packages/angular/src/generators/cypress-component-configuration/schema.json
  packages/react/docs/component-test-examples.md
  packages/react/docs/cypress-component-configuration-examples.md
  packages/react/src/generators/component-test/schema.json
  packages/react/src/generators/cypress-component-configuration/schema.json
Labels: scope: testing tools

#12747 fix(testing): make sure jest-environment-jsdom is always installed
  packages/jest/migrations.json
Labels: scope: testing tools

#12695 fix(testing): default export ng component-test generator
  packages/angular/src/generators/component-test/component-test.ts
Labels: scope: testing tools

#12763 docs(nxdev): remove nx conf banner
  nx-dev/nx-dev/pages/index.tsx
  nx-dev/ui-common/src/lib/header.tsx
Labels: type: docs

#12752 feat(nxdev): redirects to send legacy tutorial links to new locations
  nx-dev/nx-dev/next.config.js
  nx-dev/nx-dev/redirect-rules.config.js
  nx-dev/nx-dev/redirect-rules.config.spec.js
Labels: type: docs

#12785 docs(nxdev): move mobile search to top bar
  nx-dev/feature-search/src/lib/algolia-search.tsx
  nx-dev/ui-common/src/lib/documentation-header.tsx
  nx-dev/ui-common/src/lib/sidebar.tsx
Labels: type: docs

#12753 fix(expo): fixing broken tutorial link
  packages/expo/src/generators/application/files/src/app/App.tsx.template
Labels: type: docs

#12793 docs(nxdev): add breadcrumbs index key
  nx-dev/ui-common/src/lib/breadcrumbs.tsx
Labels: type: docs

#12794 chore(js): set init generator to hidden
  docs/generated/packages/js.json
  packages/js/generators.json
Labels: scope: js

#12792 docs(nxdev): add internal schema label
  nx-dev/feature-package-schema-viewer/src/lib/content.tsx
  nx-dev/feature-package-schema-viewer/src/lib/get-schema-view-model.ts
  nx-dev/feature-package-schema-viewer/src/lib/ui/package-reference.tsx
Labels: type: docs

#12810 docs(core): add new how caching works schema
  docs/shared/concepts/how-caching-works.md
  docs/shared/images/caching/nx-hashing.svg
Labels: type: docs

#12811 docs(core): cleanup & sort documentation images
  docs/shared/affected.png
  docs/shared/all-cache-inputs.png
  docs/shared/caching-example.png
  docs/shared/ci-graph-everything-affected.png
  docs/shared/ci-graph-one-affected.png
  docs/shared/ci-graph.png
  docs/shared/core-features/integrate-with-editors.md
  docs/shared/dependency-graph.png
  docs/shared/github.png
  docs/shared/images/nx-cloud/github-nxcloud.webp
  docs/shared/images/nx-cloud/nx-cloud-logo-horizontal-white.svg
  docs/shared/images/nx-cloud/nx-cloud-logo.svg
  docs/shared/images/nx-console/continue-light.svg
  docs/shared/images/nx-console/folder-light.svg
  docs/shared/images/nx-console/nx-console-add-dependency-codelens.png
  docs/shared/images/nx-console/nx-console-logo.png
  docs/shared/images/nx-console/nx-console-logo.svg
  docs/shared/images/nx-console/nx-console-screenshot.webp
  docs/shared/images/nx-console/refresh-light.svg
  docs/shared/images/nx-console/vscode-schematics-debug.png
  docs/shared/nx-console-logo.png
  docs/shared/nx-console-screenshot.png
  docs/shared/recipes/console-add-dependency-command.md
  docs/shared/recipes/console-project-pane.md
  docs/shared/recipes/local-generators.md
Labels: type: docs

#12813 docs(nxdev): create custom event for 404s
  nx-dev/nx-dev/pages/404.tsx
Labels: type: docs

#12824 docs(nxdev): fix search input spacing
  nx-dev/feature-search/src/lib/algolia-search.tsx
Labels: type: docs

#12833 docs(nxdev): cleanup & optimize svg images
  nx-dev/nx-dev/public/images/background/background.svg
  nx-dev/nx-dev/public/images/background/hero-bg-large-2.svg
  nx-dev/nx-dev/public/images/background/hero-bg-large-3.svg
  nx-dev/nx-dev/public/images/background/hero-bg-large.svg
  nx-dev/nx-dev/public/images/background/hero-bg.jpg
  nx-dev/nx-dev/public/images/background/hero-bg.svg
  nx-dev/nx-dev/public/images/background/waves-background-final.svg
  nx-dev/nx-dev/public/images/background/waves-background.svg
  nx-dev/nx-dev/public/images/background/waves-background2.svg
  nx-dev/nx-dev/public/images/lerna-logo.svg
  nx-dev/nx-dev/public/images/nx-playbook-banner.svg
  nx-dev/ui-common/src/lib/header.tsx
Labels: type: docs

#12851 fix(core): skip transitive deps on package json creation
  packages/workspace/src/utilities/create-package-json.ts
Labels: scope: core

#12036 fix(testing): cypress 10 migration supports more configuration setups
  docs/generated/packages/cypress.json
  docs/shared/guides/cypress/cypress-v10-migration.md
  packages/cypress/src/generators/migrate-to-cypress-ten/__snapshots__/migrate-to-cypress-ten.spec.ts.snap
  packages/cypress/src/generators/migrate-to-cypress-ten/conversion.util.ts
  packages/cypress/src/generators/migrate-to-cypress-ten/migrate-to-cypress-ten.spec.ts
  packages/cypress/src/generators/migrate-to-cypress-ten/migrate-to-cypress-ten.ts
Labels: scope: testing tools

#12764 fix(testing): update jest batch mode
  packages/jest/src/executors/jest/jest.impl.ts
Labels: scope: testing tools

#12877 fix(linter): improve wildcard import parsing to allow full regex
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: scope: linter

#12878 fix(linter): project with empty onlyDependsOn can only depend on tagless project
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
Labels: scope: linter

#12614 fix(testing): use @swc/jest if being used as transformer
  packages/react/plugins/jest.ts
Labels: scope: testing tools

#12882 docs(misc): Updates and Fixes to Package-Based tutorial
  docs/shared/npm-tutorial/package-based.md
Labels: type: docs

#12887 fix(core): support npm lock file v3
  packages/nx/src/utils/lock-file/__fixtures__/npm.lock.ts
  packages/nx/src/utils/lock-file/__snapshots__/lock-file.spec.ts.snap
  packages/nx/src/utils/lock-file/__snapshots__/npm.spec.ts.snap
  packages/nx/src/utils/lock-file/lock-file.spec.ts
  packages/nx/src/utils/lock-file/npm.spec.ts
  packages/nx/src/utils/lock-file/npm.ts
  packages/nx/src/utils/lock-file/utils.ts
Labels: type: bug, scope: core

#12889 cleanup(linter): remove deprecated lint executor
  docs/generated/packages/linter.json
  docs/packages.json
  nx-dev/nx-dev-e2e/src/integration/packages.spec.ts
  packages/linter/executors.json
  packages/linter/src/executors/lint/compat.ts
  packages/linter/src/executors/lint/lint.impl.ts
  packages/linter/src/executors/lint/schema.json
Labels: scope: linter
