Repository nrwl/nx, pull requests merged in 2022-04, with the labels that each got.

#9651 feat(storybook): use build-storybook as a build target for all libs
  packages/storybook/src/executors/utils.ts
  packages/storybook/src/generators/configuration/configuration.spec.ts
Labels: scope: storybook

#9654 docs(nxdev): add animation background fallback
  nx-dev/nx-dev/pages/index.tsx
  nx-dev/nx-dev/public/images/background/hero-bg.jpg
Labels: type: docs

#9690 docs(core): add core-tutorial link on intro
  docs/shared/getting-started/intro.md
Labels: type: docs

#9710 fix(core): preset core should remove workspace.json
  packages/workspace/src/generators/preset/preset.spec.ts
  packages/workspace/src/generators/preset/preset.ts
Labels: type: bug

#9708 chore(linter): update eslint version
  package.json
  packages/angular/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/cypress/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/eslint-plugin-nx/package.json
  packages/linter/migrations.json
  packages/linter/src/executors/eslint/lint.impl.spec.ts
  packages/linter/src/utils/versions.ts
  packages/nest/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/nx/src/utils/versions.ts
  packages/workspace/src/utils/versions.ts
  yarn.lock
Labels: scope: linter

#9730 docs(nxdev): remove nxdevkit redirect rule
  nx-dev/nx-dev/redirect-rules.config.js
Labels: type: docs

#9483 docs(core): Add example of using global scripts for jest and nx libraries
  docs/shared/jest-plugin.md
  e2e/jest/src/jest.test.ts
Labels: scope: testing tools

#9540 fix(js): ignore .test. and test tsx files with buildable swc libraries
  packages/js/migrations.json
  packages/js/src/migrations/update-13-10-1/__snapshots__/update-lib-swcrc-exclude.spec.ts.snap
  packages/js/src/migrations/update-13-10-1/update-lib-swcrc-exclude.spec.ts
  packages/js/src/migrations/update-13-10-1/update-lib-swcrc-exclude.ts
  packages/js/src/utils/swc/add-swc-config.ts
Labels: scope: testing tools, scope: js

#9803 docs(nxdev): lookup to package.json version for vercel script
  scripts/vercel/ignore-build.sh
Labels: type: docs

#9796 docs(nxdev): move conference components to ui
  dep-graph/client/project.json
  nx-dev/feature-conf/README.md
  nx-dev/nx-dev/pages/conf.tsx
  nx-dev/ui-conference/.eslintrc.json
  nx-dev/ui-conference/README.md
  nx-dev/ui-conference/jest.config.js
  nx-dev/ui-conference/project.json
  nx-dev/ui-conference/src/index.ts
  nx-dev/ui-conference/src/lib/conf-schedule-short.tsx
  nx-dev/ui-conference/src/lib/conf-schedule.tsx
  nx-dev/ui-conference/src/lib/conf-speakers.tsx
  nx-dev/ui-conference/src/lib/conf-sponsors.tsx
  nx-dev/ui-conference/src/lib/conf-workshop.tsx
  nx-dev/ui-conference/test-setup.ts
  nx-dev/ui-conference/tsconfig.json
  nx-dev/ui-conference/tsconfig.lib.json
  nx-dev/ui-conference/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: type: docs

#9808 docs(core): update mfe guide link
  docs/shared/guides/dynamic-mfe-angular.md
Labels: type: docs

#9810 docs(nxdev): add jason jean nx conf lite talk
  nx-dev/ui-conference/src/lib/conf-schedule-short.tsx
Labels: type: docs

#9807 docs(nxdev): add noreferrer for _blank links
  CONTRIBUTING.md
  README.md
  dep-graph/client/src/app/sidebar/sidebar.tsx
  nx-dev/feature-package-schema-viewer/src/lib/types/type.tsx
  nx-dev/ui-common/src/lib/footer.tsx
  nx-dev/ui-common/src/lib/npx-create-nx-workspace.tsx
  nx-dev/ui-conference/src/lib/conf-schedule-short.tsx
  nx-dev/ui-conference/src/lib/conf-schedule.tsx
  nx-dev/ui-home/src/lib/egghead-courses.tsx
  nx-dev/ui-home/src/lib/event-banner.tsx
  nx-dev/ui-home/src/lib/nx-playbook.tsx
  nx-dev/ui-home/src/lib/open-source-projects.tsx
  nx-dev/ui-home/src/lib/youtube-channel.tsx
  nx-dev/ui-member-card/src/lib/member-card.tsx
  nx-dev/ui-sponsor-card/src/lib/sponsor-card.tsx
  scripts/readme-fragments/content.md
  scripts/readme-fragments/resources.md
Labels: type: docs

#9795 fix(testing): provide descriptive message when project is missing targets for cypress-project generator
  packages/cypress/src/generators/cypress-project/cypress-project.spec.ts
  packages/cypress/src/generators/cypress-project/cypress-project.ts
Labels: scope: testing tools

#9824 chore(repo): update pnpm action version
  .github/workflows/e2e-matrix.yml
Labels: scope: repo

#9842 chore(repo): replace manual package cache with orb
  .circleci/config.yml
Labels: scope: repo

#9841 chore(repo): remove outdated immer resolution from package.json
  package.json
  yarn.lock
Labels: scope: repo

#9812 fix(core): allow parsing dot notation cli args
  packages/nx/src/command-line/nx-commands.spec.ts
  packages/nx/src/command-line/nx-commands.ts
Labels: scope: testing tools, scope: core

#9762 chore(dep-graph): clean-up dark mode and remove feature flag
  dep-graph/client/src/app/dark-theme-styles.tsx
  dep-graph/client/src/app/debugger-panel.tsx
  dep-graph/client/src/app/edge-tooltip.tsx
  dep-graph/client/src/app/hooks/use-interval-when.ts
  dep-graph/client/src/app/icons/flag.tsx
  dep-graph/client/src/app/icons/map-marker.tsx
  dep-graph/client/src/app/icons/x-circle-outline.tsx
  dep-graph/client/src/app/machines/custom-selected.state.ts
  dep-graph/client/src/app/machines/dep-graph.spec.ts
  dep-graph/client/src/app/machines/graph.service.ts
  dep-graph/client/src/app/machines/graph.ts
  dep-graph/client/src/app/machines/match-media-mock.spec.ts
  dep-graph/client/src/app/machines/route-listener.actor.ts
  dep-graph/client/src/app/machines/tracing.state.ts
  dep-graph/client/src/app/machines/unselected.state.ts
  dep-graph/client/src/app/project-node-tooltip.tsx
  dep-graph/client/src/app/shell.tsx
  dep-graph/client/src/app/sidebar/collapse-edges-panel.tsx
  dep-graph/client/src/app/sidebar/focused-project-panel.tsx
  dep-graph/client/src/app/sidebar/group-by-folder-panel.tsx
  dep-graph/client/src/app/sidebar/modal.tsx
  dep-graph/client/src/app/sidebar/project-list.tsx
  dep-graph/client/src/app/sidebar/search-depth.tsx
  dep-graph/client/src/app/sidebar/show-hide-projects.tsx
  dep-graph/client/src/app/sidebar/sidebar.tsx
  dep-graph/client/src/app/sidebar/text-filter-panel.tsx
  dep-graph/client/src/app/sidebar/theme-icons.tsx
  dep-graph/client/src/app/sidebar/theme-panel.tsx
  dep-graph/client/src/app/sidebar/tracing-panel.tsx
  dep-graph/client/src/app/styles-graph/nodes.ts
  dep-graph/client/src/app/theme-resolver.tsx
  dep-graph/client/src/app/tooltip-service.ts
  dep-graph/client/src/index.html
  dep-graph/client/src/styles.scss
  dep-graph/client/tailwind.config.js
Labels: type: feature

#9757 docs(nx-plugin): add documentation for project inference plugins
  docs/map.json
  docs/shared/extending-nx/project-inference-plugins.md
  nx-dev/data-access-documents/src/lib/menu.utils.ts
Labels: type: docs, scope: plugins

#9880 fix(js): enable hidden files as assets
  packages/js/src/utils/copy-assets-handler.ts
Labels: type: bug, scope: js

#9883 fix(core): make CNW preset property open for custom presets
  docs/generated/cli/create-nx-workspace.md
  packages/create-nx-workspace/bin/create-nx-workspace.ts
Labels: type: bug, scope: core

#9899 docs(nxdev): add time slots for nx conf agenda
  nx-dev/ui-conference/src/lib/conf-schedule-short.tsx
Labels: type: docs

#9904 feat(testing): support extra jest cli args
  packages/jest/src/executors/jest/jest.impl.spec.ts
  packages/jest/src/executors/jest/jest.impl.ts
Labels: scope: testing tools

#9905 docs(nxdev): update conference speaker list
  nx-dev/ui-conference/src/lib/conf-speakers.tsx
Labels: type: docs

#9611 feat(core): add CI generation to create-nx-workspace
  docs/generated/cli/create-nx-workspace.md
  docs/generated/packages/workspace.json
  docs/map.json
  docs/packages.json
  docs/shared/monorepo-ci-azure.md
  docs/shared/monorepo-ci-circle-ci.md
  docs/shared/monorepo-ci-github-actions.md
  packages/create-nx-workspace/bin/ci.ts
  packages/create-nx-workspace/bin/create-nx-workspace.ts
  packages/nx/src/utils/package-manager.ts
  packages/workspace/generators.json
  packages/workspace/src/generators/ci-workflow/__snapshots__/ci-workflow.spec.ts.snap
  packages/workspace/src/generators/ci-workflow/ci-workflow.spec.ts
  packages/workspace/src/generators/ci-workflow/ci-workflow.ts
  packages/workspace/src/generators/ci-workflow/files/azure/azure-pipelines.yml__tmpl__
  packages/workspace/src/generators/ci-workflow/files/circleci/.circleci/config.yml__tmpl__
  packages/workspace/src/generators/ci-workflow/files/github/.github/workflows/__workflowFileName__.yml__tmpl__
  packages/workspace/src/generators/ci-workflow/schema.json
Labels: type: feature, scope: core

#9916 docs(nxdev): bump github stars header counter
  nx-dev/ui-common/src/lib/header.tsx
Labels: type: docs

#9931 fix(core): fix writing partial files to disk
  packages/nx/src/utils/fileutils.ts
Labels: scope: core

#9792 feat(testing): update to latest jest version
  packages/jest/migrations.json
  packages/jest/package.json
  packages/jest/src/utils/versions.ts
Labels: scope: testing tools

#9969 fix(testing): fix migration path error on windows
  packages/jest/src/migrations/update-14-0-0/update-jest-config-ext.ts
Labels: scope: testing tools

#9996 docs(nxdev): fix internal module federation link
  docs/shared/angular-plugin.md
  docs/shared/guides/module-federation/dynamic-mfe-angular.md
Labels: type: docs

#10012 docs(nxdev): add miro to nx conf lite speakers list
  nx-dev/nx-dev/public/images/conf/miroslav-jonas.webp
  nx-dev/ui-conference/src/lib/conf-schedule-short.tsx
  nx-dev/ui-conference/src/lib/conf-speakers.tsx
Labels: type: docs

#10033 docs(core): update contributors
  README.md
Labels: type: docs

#10050 docs(nxdev): remove deprecated schemaViewModel GitHub property
  nx-dev/feature-package-schema-viewer/src/lib/get-schema-view-model.ts
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-viewer.tsx
Labels: type: docs
