Repository nrwl/nx, pull requests merged in 2022-06, with the labels that each got.

#10546 docs(nxdev): consolidate documentats consumption
  docs/map.json
  nx-dev/data-access-documents/src/lib/documents.api.ts
  nx-dev/data-access-menu/src/lib/menu.api.ts
  nx-dev/nx-dev/lib/api.ts
  nx-dev/nx-dev/pages/[...segments].tsx
  scripts/documentation/open-graph/generate-images.ts
Labels: type: docs

#10568 fix(storybook): ignore addon-notes from version update
  packages/storybook/src/migrations/update-14-0-0/migrate-defaults-5-to-6/migrate-defaults-5-to-6.spec.ts
  packages/storybook/src/migrations/update-14-0-0/migrate-defaults-5-to-6/migrate-defaults-5-to-6.ts
Labels: scope: storybook

#10416 fix(js): semver regex update
  packages/js/src/utils/minimal-publish-script.ts
Labels: PR status: LGTM, scope: js

#10618 fix(testing): update @nrw/cypress peer deps
  packages/cypress/package.json
  scripts/depcheck/discrepancies.ts
Labels: scope: testing tools

#10551 feat(storybook): Custom .babelrc in Storybook
  docs/generated/packages/storybook.json
  packages/react/plugins/storybook/index.ts
  packages/storybook/src/executors/storybook/schema.json
Labels: scope: storybook

#10229 fix(node): use webpack compilation hooks to emit package.json
  packages/node/src/executors/webpack/webpack.impl.ts
  packages/node/src/utils/generate-package-json-webpack-plugin.ts
  packages/node/src/utils/generate-package-json.ts
  packages/node/src/utils/node.config.spec.ts
  packages/node/src/utils/node.config.ts
Labels: PR status: in-progress

#10510 docs(storybook): update storybook-composition-setup.md
  docs/generated/packages/storybook.json
  docs/shared/guides/storybook/storybook-composition-setup.md
Labels: scope: storybook

#10690 docs(nxdev): add nx cloud docs
  docs/map.json
  docs/nx-cloud/intro/distributed-caching.md
  docs/nx-cloud/intro/distributed-task-execution.md
  docs/nx-cloud/intro/nx-cloud.md
  docs/nx-cloud/private/auth-github.md
  docs/nx-cloud/private/auth-gitlab.md
  docs/nx-cloud/private/auth-single-admin.md
  docs/nx-cloud/private/get-started.md
  docs/nx-cloud/private/github.md
  docs/nx-cloud/reference/release-notes.md
  docs/nx-cloud/reference/server-api.md
  docs/nx-cloud/set-up/github.md
  docs/nx-cloud/set-up/set-up-dte.md
  docs/shared/distributed-builds.md
  docs/shared/monorepo-ci-azure.md
  docs/shared/monorepo-ci-bitbucket-pipelines.md
  docs/shared/monorepo-ci-circle-ci.md
  docs/shared/monorepo-ci-github-actions.md
  docs/shared/monorepo-ci-gitlab.md
  docs/shared/monorepo-ci-jenkins.md
  docs/shared/nx-cloud-logo-horizontal-white.svg
  docs/shared/using-nx/caching.md
  docs/shared/using-nx/dte.md
  nx-dev/data-access-menu/src/lib/menu.api.ts
  nx-dev/data-access-menu/src/lib/menu.utils.ts
  nx-dev/feature-doc-viewer/src/lib/content.tsx
  nx-dev/nx-dev-e2e/src/integration/nx-cloud-documentation.spec.ts
  nx-dev/nx-dev/lib/api.ts
  nx-dev/nx-dev/pages/[...segments].tsx
  nx-dev/nx-dev/styles/main.css
  nx-dev/ui-common/src/lib/header.tsx
  nx-dev/ui-common/src/lib/sidebar.tsx
  package.json
  yarn.lock
Labels: type: docs

#10715 docs(nxdev): add 13k to github stars counter
  nx-dev/ui-common/src/lib/header.tsx
Labels: type: docs

#10720 docs(nxdev): fix header docs highlights
  nx-dev/ui-common/src/lib/header.tsx
Labels: type: docs

#10732 chore(repo): remove husky call to missing file
  .husky/pre-push
Labels: scope: repo

#10695 docs(core): correct typo in `ci-workflow` generator description
  docs/generated/packages/workspace.json
  packages/workspace/generators.json
Labels: type: docs

#10782 docs(nxdev): add projects using nx on homepage
  nx-dev/ui-home/src/lib/open-source-projects.tsx
Labels: scope: docs

#10795 docs(nxdev): enable partytown offloading script strategy
  nx-dev/nx-dev/next.config.js
  nx-dev/nx-dev/pages/_app.tsx
  package.json
  yarn.lock
Labels: type: docs

#10817 docs(core): fix misc content on project graph plugins
  docs/shared/extending-nx/project-graph-plugins.md
Labels: type: docs

#10837 fix(storybook): pass tsConfiguration option from framework generators
  packages/angular/src/generators/storybook-configuration/lib/generate-storybook-configuration.ts
  packages/react-native/src/generators/storybook-configuration/configuration.ts
  packages/react/src/generators/storybook-configuration/configuration.ts
Labels: scope: storybook

#10849 chore(repo): set agent count in circle ci config
  .circleci/config.yml
Labels: scope: repo

#10018 feat(core): make npmScope optional
  docs/generated/devkit/index.md
  docs/generated/packages/devkit.json
  e2e/nx-misc/src/workspace.test.ts
  e2e/utils/index.ts
  packages/angular/src/generators/library/lib/normalize-options.ts
  packages/angular/src/generators/ng-add/__snapshots__/migrate-from-angular-cli.spec.ts.snap
  packages/angular/src/generators/ng-add/utilities/normalize-options.ts
  packages/angular/src/generators/ng-add/utilities/workspace.ts
  packages/devkit/index.ts
  packages/devkit/src/utils/get-workspace-layout.ts
  packages/js/src/generators/library/library.ts
  packages/node/src/generators/library/library.ts
  packages/nx-plugin/src/generators/plugin/utils/normalize-schema.ts
  packages/nx/src/hasher/hasher.spec.ts
  packages/nx/src/hasher/hasher.ts
  packages/nx/src/project-graph/build-dependencies/explicit-package-json-dependencies.ts
  packages/nx/src/utils/path.ts
  packages/react-native/src/generators/library/lib/normalize-options.ts
  packages/react/src/generators/library/library.ts
  packages/web/src/generators/application/application.ts
  packages/workspace/src/generators/library/library.ts
  packages/workspace/src/generators/move/lib/normalize-schema.ts
  packages/workspace/src/generators/move/lib/update-imports.ts
  packages/workspace/src/generators/npm-package/npm-package.ts
  packages/workspace/src/generators/preset/preset.ts
  packages/workspace/src/generators/remove/lib/update-tsconfig.ts
Labels: type: feature, scope: core

#10863 feat(core): update github action workflow to latest version
  docs/shared/monorepo-ci-github-actions.md
  packages/workspace/src/generators/ci-workflow/__snapshots__/ci-workflow.spec.ts.snap
  packages/workspace/src/generators/ci-workflow/files/github/.github/workflows/__workflowFileName__.yml__tmpl__
Labels: scope: core

#10828 fix(storybook): fix support for nextjs and swc
  packages/angular/src/generators/storybook-configuration/__snapshots__/storybook-configuration.spec.ts.snap
  packages/react-native/src/generators/stories/stories.ts
  packages/react/src/generators/stories/stories.ts
  packages/storybook/src/generators/change-storybook-targets/change-storybook-targets.ts
  packages/storybook/src/generators/configuration/__snapshots__/configuration.spec.ts.snap
  packages/storybook/src/generators/configuration/configuration.spec.ts
  packages/storybook/src/generators/configuration/configuration.ts
  packages/storybook/src/generators/configuration/project-files-ts/.storybook/main.ts__tmpl__
  packages/storybook/src/generators/configuration/project-files-ts/.storybook/tsconfig.json__tmpl__
  packages/storybook/src/generators/configuration/project-files/.storybook/main.js__tmpl__
  packages/storybook/src/generators/configuration/project-files/.storybook/tsconfig.json__tmpl__
  packages/storybook/src/generators/configuration/test-configs/workspace-conifiguration.json
  packages/storybook/src/generators/configuration/util-functions.ts
  packages/storybook/src/migrations/update-13-4-6/set-project-build-config.ts
  packages/storybook/src/migrations/update-14-0-0/migrate-defaults-5-to-6/migrate-defaults-5-to-6.ts
  packages/storybook/src/utils/test-configs/different-target-variations.json
  packages/storybook/src/utils/testing.ts
  packages/storybook/src/utils/utilities.spec.ts
  packages/storybook/src/utils/utilities.ts
  packages/storybook/src/utils/versions.ts
Labels: scope: storybook

#10860 feat(core): move workspace configuration computation to daemon
  docs/generated/devkit/index.md
  docs/generated/packages/devkit.json
  packages/angular/src/builders/module-federation-dev-server/module-federation-dev-server.impl.ts
  packages/angular/src/builders/webpack-server/webpack-server.impl.ts
  packages/angular/src/utils/mfe/with-module-federation.ts
  packages/next/src/executors/build/lib/create-package-json.ts
  packages/nx/src/adapter/compat.ts
  packages/nx/src/command-line/affected.ts
  packages/nx/src/command-line/format.ts
  packages/nx/src/command-line/generate.ts
  packages/nx/src/command-line/print-affected.ts
  packages/nx/src/command-line/read-environment.ts
  packages/nx/src/command-line/run-many.ts
  packages/nx/src/command-line/run-one.ts
  packages/nx/src/command-line/run.ts
  packages/nx/src/config/configuration.ts
  packages/nx/src/config/workspaces.ts
  packages/nx/src/daemon/client/client.ts
  packages/nx/src/project-graph/affected/affected-project-graph-models.ts
  packages/nx/src/project-graph/affected/affected-project-graph.spec.ts
  packages/nx/src/project-graph/affected/affected-project-graph.ts
  packages/nx/src/project-graph/affected/locators/workspace-json-changes.spec.ts
  packages/nx/src/project-graph/affected/locators/workspace-json-changes.ts
  packages/nx/src/project-graph/affected/locators/workspace-projects.spec.ts
  packages/nx/src/project-graph/affected/locators/workspace-projects.ts
  packages/nx/src/project-graph/build-project-graph.ts
  packages/nx/src/project-graph/file-utils.ts
  packages/nx/src/project-graph/project-graph.ts
  packages/nx/src/tasks-runner/batch/run-batch.ts
  packages/nx/src/tasks-runner/task-orchestrator.ts
  packages/nx/src/tasks-runner/tasks-schedule.spec.ts
  packages/nx/src/tasks-runner/tasks-schedule.ts
  packages/nx/src/tasks-runner/utils.ts
  packages/nx/src/utils/command-line-utils.ts
  packages/react/src/module-federation/with-module-federation.ts
Labels: scope: core

#10823 fix(storybook): storybook tsconfig - only include stories and .storybook files
  packages/storybook/src/generators/configuration/__snapshots__/configuration.spec.ts.snap
  packages/storybook/src/generators/configuration/project-files/.storybook/tsconfig.json__tmpl__
Labels: scope: storybook

#10907 chore(repo): update nx orb version to 1.5.1
  .circleci/config.yml
  docs/shared/monorepo-ci-circle-ci.md
  packages/workspace/src/generators/ci-workflow/__snapshots__/ci-workflow.spec.ts.snap
  packages/workspace/src/generators/ci-workflow/files/circleci/.circleci/config.yml__tmpl__
Labels: scope: repo

#10947 docs(nxdev): update algolia dns id
  nx-dev/feature-search/src/lib/algolia-search.tsx
Labels: type: docs

#10961 docs(nxdev): set gtag script to afterInteractive
  nx-dev/nx-dev/pages/_app.tsx
Labels: type: docs

#10962 docs(nxdev): set hotjar tag script to afterInteractive
  nx-dev/nx-dev/pages/_app.tsx
Labels: type: docs
