Repository nrwl/nx, pull requests merged in 2022-08, with the labels that each got.

#11394 docs(testing): update docs to use correct filenames for cypress and jest
  docs/generated/packages/angular.json
  docs/generated/packages/react.json
  docs/generated/packages/storybook.json
  docs/shared/angular-tutorial/01-create-application.md
  docs/shared/angular-tutorial/02-add-e2e-test.md
  docs/shared/angular-tutorial/05-add-node-app.md
  docs/shared/angular-tutorial/07-share-code.md
  docs/shared/angular-tutorial/08-create-libs.md
  docs/shared/generators/creating-files.md
  docs/shared/guides/react-native.md
  docs/shared/guides/storybook/plugin-angular.md
  docs/shared/guides/storybook/plugin-react.md
  docs/shared/node-tutorial/01-create-application.md
  docs/shared/node-tutorial/04-create-libs.md
  docs/shared/react-tutorial/01-create-application.md
  docs/shared/react-tutorial/02-add-e2e-test.md
  docs/shared/react-tutorial/05-add-node-app.md
  docs/shared/react-tutorial/07-share-code.md
  docs/shared/react-tutorial/08-create-libs.md
  packages/angular/src/generators/storybook-configuration/schema.json
  packages/react/src/generators/storybook-configuration/schema.json
Labels: type: docs, scope: testing tools

#11402 docs(nxdev): upgrade nextseo dependency
  package.json
  packages/angular/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/cypress/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/linter/src/utils/convert-tslint-to-eslint/__snapshots__/convert-to-eslint-config.spec.ts.snap
  packages/nest/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  yarn.lock
Labels: type: docs

#11432 docs(nxdev): update package schema list link
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-list.tsx
  nx-dev/feature-package-schema-viewer/src/lib/ui/package-reference.tsx
Labels: type: docs

#11433 docs(ci): add gitlab dte example
  docs/shared/monorepo-ci-gitlab.md
Labels: type: docs

#11468 fix(testing): exclude jest.config.ts in angular project tsconfigs
  packages/angular/src/generators/application/application.spec.ts
  packages/angular/src/generators/application/lib/update-config-files.ts
  packages/angular/src/generators/library/lib/update-tsconfig.ts
  packages/angular/src/generators/library/library.spec.ts
  packages/jest/migrations.json
  packages/jest/src/migrations/update-14-0-0/__snapshots__/update-jest-config-ext.spec.ts.snap
  packages/jest/src/migrations/update-14-0-0/update-jest-config-ext.spec.ts
  packages/jest/src/migrations/update-14-0-0/update-jest-config-ext.ts
Labels: scope: testing tools, scope: angular

#11427 fix(testing): install ts-node when migrating to ts jest config files
  packages/jest/src/migrations/update-14-1-5/update-exports-jest-config.spec.ts
  packages/jest/src/migrations/update-14-1-5/update-exports-jest-config.ts
Labels: scope: testing tools

#11457 fix(testing): restore path in update-jestconfig
  packages/jest/src/generators/jest-project/lib/update-jestconfig.ts
Labels: scope: testing tools

#11523 docs(nxdev): update github header info
  nx-dev/ui-common/src/lib/header.tsx
Labels: type: docs

#11538 cleanup(core): remove unused addGlobal from package manager commands
  packages/nx/src/utils/package-manager.ts
Labels: scope: core, type: cleanup

#11544 docs(nxdev): simplify link map checker script
  scripts/documentation/map-link-checker.ts
Labels: type: docs

#11542 fix(linter): skip prettier config if prettier is missing
  packages/eslint-plugin-nx/src/configs/javascript.ts
  packages/eslint-plugin-nx/src/configs/typescript.ts
  packages/eslint-plugin-nx/src/utils/config-utils.ts
Labels: scope: linter

#11551 docs(nxdev): clean up link map checker script
  scripts/documentation/map-link-checker.ts
Labels: type: docs

#11528 feat(core): support yarn berry in CNW
  CONTRIBUTING.md
  packages/create-nx-workspace/bin/create-nx-workspace.ts
  packages/create-nx-workspace/bin/package-manager.ts
  packages/linter/src/utils/convert-tslint-to-eslint/project-converter.spec.ts
  packages/nx/src/utils/package-manager.ts
  packages/workspace/src/generators/ci-workflow/__snapshots__/ci-workflow.spec.ts.snap
  packages/workspace/src/generators/workspace/workspace.ts
Labels: scope: core

#11561 docs(nxdev): cleanup imports
  nx-dev/data-access-menu/src/lib/menu.api.ts
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-list.tsx
  nx-dev/ui-common/src/lib/selector.tsx
  nx-dev/ui-markdoc/src/lib/tags/callout.component.tsx
Labels: type: docs

#11563 docs(nxdev): cleanup imports
  scripts/documentation/generate-cli-data.ts
  scripts/documentation/generate-cnw-documentation.ts
  scripts/documentation/generate-devkit-documentation.ts
  scripts/documentation/map-link-checker.ts
  scripts/documentation/nx-dev-docs-latest-sync.ts
  scripts/documentation/open-graph/generate-images.ts
  scripts/documentation/package-schemas/generatePackageSchemas.ts
  scripts/documentation/utils.ts
Labels: type: docs

#11539 chore(core): release canary version for e2e tests to avoid version overlap
  scripts/e2e-build-package-publish.ts
  scripts/nx-release.ts
Labels: scope: core

#11564 feat(core): format additional flags values for logging
  packages/nx/src/tasks-runner/life-cycles/formatting-utils.spec.ts
  packages/nx/src/tasks-runner/life-cycles/formatting-utils.ts
Labels: scope: core

#11569 chore(testing): add e2e tests for cypress environment variables
  docs/generated/packages/cypress.json
  docs/shared/cypress-plugin.md
  e2e/cypress/src/cypress.test.ts
Labels: scope: testing tools

#11597 docs(nx-cloud): add agent definitions for DTE with Jenkins
  docs/shared/monorepo-ci-jenkins.md
Labels: type: docs

#11603 fix(linter): use more performant way to check for package existance
  packages/eslint-plugin-nx/src/utils/config-utils.ts
Labels: type: bug, scope: linter

#11619 chore(repo): release major version on e2e runs
  scripts/e2e-build-package-publish.ts
  scripts/nx-release.ts
Labels: scope: repo

#11555 fix(linter): add jest to root .eslintrc if selected as unit test runner
  packages/angular/src/generators/add-linting/add-linting.ts
  packages/angular/src/generators/add-linting/schema.d.ts
  packages/angular/src/generators/application/lib/add-e2e.ts
  packages/angular/src/generators/application/lib/add-linting.ts
  packages/angular/src/generators/library/library.ts
  packages/angular/src/generators/ng-add/migrate-from-angular-cli.ts
  packages/angular/src/generators/ng-add/utilities/e2e.migrator.ts
  packages/angular/src/generators/ng-add/utilities/workspace.ts
  packages/cypress/src/generators/cypress-project/cypress-project.ts
  packages/js/src/generators/library/library.ts
  packages/linter/src/generators/init/init.ts
  packages/linter/src/generators/lint-project/lint-project.ts
  packages/next/src/generators/application/lib/add-linting.ts
  packages/node/src/generators/application/application.ts
  packages/react-native/src/generators/application/application.ts
  packages/react-native/src/generators/library/library.ts
  packages/react-native/src/utils/add-linting.spec.ts
  packages/react-native/src/utils/add-linting.ts
  packages/react/src/generators/application/application.ts
  packages/react/src/generators/library/library.ts
  packages/web/src/generators/application/application.ts
  packages/workspace/src/generators/library/library.ts
Labels: type: bug, scope: core, scope: linter

#11638 docs(nxdev): remove unused css wobble animation
  nx-dev/nx-dev/styles/constellation-wobble.animation.css
  nx-dev/nx-dev/styles/main.css
Labels: type: docs

#11639 docs(nxdev): add nxcloud e2e test links
  nx-dev/nx-dev-e2e/src/integration/nx-cloud-documentation.spec.ts
Labels: type: docs

#10857 feat(testing): support jest 28
  packages/angular/migrations.json
  packages/angular/src/utils/versions.ts
  packages/jest/migrations.json
  packages/jest/package.json
  packages/jest/preset/jest-preset.ts
  packages/jest/src/generators/init/init.ts
  packages/jest/src/migrations/update-14-6-0/update-configs-jest-28.spec.ts
  packages/jest/src/migrations/update-14-6-0/update-configs-jest-28.ts
  packages/jest/src/migrations/update-14-6-0/update-tests-jest-28.spec.ts
  packages/jest/src/migrations/update-14-6-0/update-tests-jest-28.ts
  packages/jest/src/utils/versions.ts
  packages/js/jest.config.ts
  packages/react-native/migrations.json
  packages/react-native/src/generators/application/files/app/babel.config.json.template
  packages/react-native/src/generators/library/files/lib/babel.config.json.template
  packages/react-native/src/generators/library/files/lib/tsconfig.lib.json__tmpl__
  packages/react-native/src/migrations/update-14-6-0/remove-jest-transform.spec.ts
  packages/react-native/src/migrations/update-14-6-0/remove-jest-transform.ts
  packages/react-native/src/utils/add-jest.ts
  packages/react/migrations.json
  packages/react/plugins/jest.ts
  packages/react/src/migrations/update-14-6-0/add-preset-jest-config.spec.ts
  packages/react/src/migrations/update-14-6-0/add-preset-jest-config.ts
  packages/react/src/utils/jest-utils.ts
  scripts/patched-jest-resolver.js
Labels: scope: testing tools

#11633 feat(core): move git commit from generators to create-nx-workspace
  docs/generated/cli/create-nx-workspace.md
  docs/generated/packages/nx.json
  docs/generated/packages/workspace.json
  e2e/workspace-create/src/create-nx-plugin.test.ts
  packages/create-nx-plugin/bin/create-nx-plugin.ts
  packages/create-nx-plugin/bin/shared.ts
  packages/create-nx-workspace/bin/create-nx-workspace.ts
  packages/create-nx-workspace/bin/git.spec.ts
  packages/create-nx-workspace/bin/git.ts
  packages/workspace/src/generators/new/new.spec.ts
  packages/workspace/src/generators/new/new.ts
  packages/workspace/src/generators/new/schema.json
  packages/workspace/src/generators/workspace/schema.json
  packages/workspace/src/utilities/default-base.spec.ts
  packages/workspace/src/utilities/default-base.ts
Labels: scope: core

#11651 docs(nxdev): add transformer for code fence
  docs/shared/core-tutorial/01-create-blog.md
  nx-dev/ui-markdoc/src/lib/nodes/fence.component.tsx
  nx-dev/ui-markdoc/src/lib/nodes/fence.schema.ts
  package.json
  yarn.lock
Labels: type: docs

#10989 fix(docs): fix typo in github actions setup
  docs/shared/monorepo-ci-github-actions.md
Labels: type: docs

#11709 docs(nxdev): update twitter handle speakerlist
  nx-dev/ui-conference/src/lib/conf-speakers.tsx
Labels: type: docs

#11719 feat(core): stop agents after build task on CI generated workflows
  packages/workspace/src/generators/ci-workflow/__snapshots__/ci-workflow.spec.ts.snap
  packages/workspace/src/generators/ci-workflow/files/azure/azure-pipelines.yml__tmpl__
  packages/workspace/src/generators/ci-workflow/files/circleci/.circleci/config.yml__tmpl__
  packages/workspace/src/generators/ci-workflow/files/github/.github/workflows/__workflowFileName__.yml__tmpl__
Labels: scope: core

#11741 docs(nxdev): add external paths
  nx-dev/data-access-documents/src/lib/documents.api.ts
  nx-dev/models-document/src/lib/documents.models.ts
  scripts/documentation/map-link-checker.ts
Labels: type: docs

#11743 docs(nxdev): remove unused scripts
  scripts/documentation/in-progress.ts
  scripts/documentation/nx-dev-docs-latest-sync.ts
Labels: type: docs

#11757 docs(nxdev): add new sitemap index pointer
  scripts/documentation/internal-link-checker.ts
Labels: type: docs

#11760 chore(nxdev): clean up api imports
  docs/nx-cloud/intro/nx-cloud.md
  nx-dev/nx-dev/lib/api.ts
  scripts/documentation/internal-link-checker.ts
Labels: type: docs

#11725 fix(testing): handle more complex projects for react component testing
  docs/generated/packages/react.json
  e2e/react/src/cypress-component-tests.test.ts
  packages/angular/src/generators/ng-add/utilities/e2e.migrator.spec.ts
  packages/angular/src/generators/ng-add/utilities/e2e.migrator.ts
  packages/cypress/migrations.json
  packages/cypress/plugins/cypress-preset.ts
  packages/cypress/src/executors/cypress/cypress.impl.ts
  packages/cypress/src/generators/cypress-component-project/cypress-component-project.spec.ts
  packages/cypress/src/generators/cypress-component-project/cypress-component-project.ts
  packages/cypress/src/migrations/update-14-6-1/update-cypress-configs-presets.spec.ts
  packages/cypress/src/migrations/update-14-6-1/update-cypress-configs-presets.ts
  packages/cypress/src/utils/find-target-options.ts
  packages/react/plugins/component-testing/index.ts
  packages/react/plugins/component-testing/webpack-fallback.ts
  packages/react/src/generators/component-test/component-test.spec.ts
  packages/react/src/generators/component-test/component-test.ts
  packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.spec.ts
  packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.ts
  packages/react/src/generators/cypress-component-configuration/files/cypress.config.ts__tpl__
  packages/react/src/generators/cypress-component-configuration/lib/add-files.ts
  packages/react/src/generators/cypress-component-configuration/lib/update-configs.ts
  packages/react/src/generators/cypress-component-configuration/schema.d.ts
  packages/react/src/generators/cypress-component-configuration/schema.json
Labels: scope: testing tools

#11803 docs(nxdev): rename script functions
  scripts/documentation/documentation.ts
  scripts/documentation/generate-cli-data.ts
  scripts/documentation/generate-cnw-documentation.ts
Labels: type: docs
