Repository nrwl/nx, pull requests merged in 2022-11, with the labels that each got.

#12925 docs(nxdev): remove unused create-nx-workspace component
  nx-dev/ui-common/src/index.ts
  nx-dev/ui-common/src/lib/npx-create-nx-workspace.tsx
Labels: type: docs

#12926 docs(nxdev): remove unused custom tailwindcss theme colours
  nx-dev/feature-doc-viewer/src/lib/doc-viewer.tsx
  nx-dev/feature-package-schema-viewer/src/lib/content.tsx
  nx-dev/feature-package-schema-viewer/src/lib/ui/package-reference.tsx
  nx-dev/nx-dev/styles/main.css
  nx-dev/nx-dev/tailwind.config.js
  nx-dev/ui-common/src/lib/plugin-card.tsx
  nx-dev/ui-conference/src/index.ts
  nx-dev/ui-conference/src/lib/conf-schedule.tsx
  nx-dev/ui-home/src/lib/extensible-and-integrated/plugins-tab.tsx
Labels: type: docs

#12927 docs(nxdev): remove unused custom css
  nx-dev/nx-dev/styles/main.css
Labels: type: docs

#12931 docs(nxdev): simplify app template
  nx-dev/nx-dev/pages/_app.tsx
  nx-dev/nx-dev/pages/_document.tsx
Labels: type: docs

#12933 docs(nxdev): rename next-sitemap to next-sitemap.config
  nx-dev/nx-dev/next-sitemap.config.js
  nx-dev/nx-dev/project.json
Labels: type: docs

#12934 docs(nxdev): clean up 500 from deprecated component attributes
  nx-dev/nx-dev/pages/500.tsx
Labels: type: docs

#12906 docs(linter): add executor examples
  docs/generated/packages/linter.json
  packages/linter/docs/eslint-examples.md
  packages/linter/src/executors/eslint/schema.json
Labels: type: docs, scope: linter

#12940 docs(nxdev): optimize theme imports
  nx-dev/ui-theme/src/lib/theme-switcher.component.tsx
  nx-dev/ui-theme/src/lib/theme.provider.tsx
Labels: type: docs

#12946 docs(nxdev): add loader & style to graph component
  nx-dev/ui-markdoc/src/lib/tags/graph.component.tsx
Labels: type: docs

#12949 docs(nxdev): remove code fence overrides in main.css
  nx-dev/nx-dev/styles/main.css
Labels: type: docs

#12953 fix(linter): ensure fs operations run on full path
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin-nx/src/utils/ast-utils.ts
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: type: bug, scope: linter

#12954 fix(linter): do not remap namespace import specifiers as import specifiers
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
Labels: scope: linter

#12955 fix(core): workspace-generator errors should be propagated to nx
  packages/nx/src/command-line/nx-commands.ts
Labels: scope: core

#12979 docs(nxdev): extract dynamic loading for lazy component
  docs/shared/core-features/explore-graph.md
  nx-dev/ui-markdoc/src/lib/tags/graph.component.tsx
Labels: type: docs

#12995 docs(nxdev): remove nrwl logo from header
  nx-dev/ui-common/src/lib/documentation-header.tsx
Labels: type: docs

#12997 docs(nxdev): change link wording on nx conf
  nx-dev/nx-dev/pages/conf.tsx
Labels: type: docs

#12863 fix(testing): handle path offsets for angular component testing
  e2e/angular-extensions/src/cypress-component-tests.test.ts
  packages/angular/plugins/component-testing.ts
Labels: scope: testing tools

#13002 docs(nxdev): add module federation icon
  nx-dev/nx-dev/public/images/icons/module-federation.svg
  nx-dev/ui-references/src/lib/icons-map.ts
Labels: type: docs

#12886 fix(testing): provide better error messages around component test --build-target
  packages/angular/src/generators/cypress-component-configuration/cypress-component-configuration.spec.ts
  packages/cypress/src/utils/find-target-options.ts
  packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.spec.ts
  packages/react/src/generators/cypress-component-configuration/lib/update-configs.ts
Labels: scope: testing tools

#12996 fix(core): improve external node dependency mapping
  packages/nx/src/utils/lock-file/__fixtures__/npm.lock.ts
  packages/nx/src/utils/lock-file/__snapshots__/lock-file.spec.ts.snap
  packages/nx/src/utils/lock-file/__snapshots__/npm.spec.ts.snap
  packages/nx/src/utils/lock-file/lock-file.spec.ts
  packages/nx/src/utils/lock-file/lock-file.ts
  packages/nx/src/utils/lock-file/npm.spec.ts
  packages/nx/src/utils/lock-file/npm.ts
  packages/nx/src/utils/lock-file/pnpm.ts
  packages/nx/src/utils/lock-file/utils.ts
  packages/nx/src/utils/lock-file/yarn.ts
Labels: scope: core

#13056 docs(nxdev): add light & dark theme to 500
  nx-dev/nx-dev/pages/500.tsx
Labels: type: docs

#13119 docs(nxdev): add packages link to flyout menu
  nx-dev/ui-common/src/lib/header.tsx
Labels: scope: docs

#13120 feat(core): add prune lock file support for npm 2 and 3
  packages/nx/src/utils/lock-file/__fixtures__/npm.lock.ts
  packages/nx/src/utils/lock-file/__fixtures__/pnpm.lock.ts
  packages/nx/src/utils/lock-file/__snapshots__/lock-file.spec.ts.snap
  packages/nx/src/utils/lock-file/__snapshots__/npm.spec.ts.snap
  packages/nx/src/utils/lock-file/__snapshots__/pnpm.spec.ts.snap
  packages/nx/src/utils/lock-file/lock-file.spec.ts
  packages/nx/src/utils/lock-file/lock-file.ts
  packages/nx/src/utils/lock-file/npm.spec.ts
  packages/nx/src/utils/lock-file/npm.ts
  packages/nx/src/utils/lock-file/pnpm.spec.ts
  packages/nx/src/utils/lock-file/pnpm.ts
  packages/nx/src/utils/lock-file/utils.ts
  packages/nx/src/utils/lock-file/yarn.ts
Labels: scope: core

#13161 docs(nxdev): add nxcloud dte and cache icons
  nx-dev/ui-markdoc/src/lib/tags/personas.component.tsx
Labels: type: docs

#13167 feat(core): add prune lock file hashing based on the input
  packages/nx/src/utils/lock-file/npm.ts
  packages/nx/src/utils/lock-file/pnpm.ts
  packages/nx/src/utils/lock-file/utils.ts
  packages/nx/src/utils/lock-file/yarn.ts
Labels: scope: core

#13170 feat(core): handle yarn workspace packages when pruning
  packages/nx/src/utils/lock-file/yarn.spec.ts
  packages/nx/src/utils/lock-file/yarn.ts
Labels: scope: core

#13175 fix(testing): add babel-jest transform options for react libraries
  packages/react/src/generators/application/application.spec.ts
  packages/react/src/generators/library/library.spec.ts
  packages/react/src/generators/library/library.ts
Labels: scope: testing tools

#13218 feat(core): support npm v1 lock file pruning with disclaimer
  e2e/vite/src/vite.test.ts
  packages/nx/src/utils/lock-file/__fixtures__/npm.lock.ts
  packages/nx/src/utils/lock-file/npm.spec.ts
  packages/nx/src/utils/lock-file/npm.ts
Labels: scope: core

#13201 feat(core): prune pnpm workspaces and meta settings
  docs/generated/devkit/index.md
  docs/generated/packages/devkit.json
  packages/nx/src/utils/lock-file/__fixtures__/pnpm.lock.ts
  packages/nx/src/utils/lock-file/__snapshots__/lock-file.spec.ts.snap
  packages/nx/src/utils/lock-file/pnpm.spec.ts
  packages/nx/src/utils/lock-file/pnpm.ts
  packages/nx/src/utils/lock-file/utils.ts
Labels: scope: core

#13249 feat(core): optimize project graph file mapping
  packages/angular/plugins/component-testing.ts
  packages/cypress/plugins/cypress-preset.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin-nx/src/rules/nx-plugin-checks.ts
  packages/eslint-plugin-nx/src/utils/project-graph-utils.ts
  packages/eslint-plugin-nx/src/utils/runtime-lint-utils.ts
  packages/nx/src/utils/target-project-locator.ts
Labels: scope: core

#13268 feat(core): use createProjectFileMappings in TargetProjectLocator
  packages/angular/plugins/component-testing.ts
  packages/cypress/plugins/cypress-preset.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin-nx/src/utils/project-graph-utils.ts
  packages/nx/src/project-graph/affected/locators/workspace-projects.spec.ts
  packages/nx/src/project-graph/affected/locators/workspace-projects.ts
  packages/nx/src/utils/nx-plugin.ts
  packages/nx/src/utils/target-project-locator.spec.ts
  packages/nx/src/utils/target-project-locator.ts
Labels: scope: core

#13383 docs(nxdev): remove twitter handle info
  nx-dev/nx-dev/pages/_app.tsx
Labels: type: docs

#13386 docs(nxdev): update favicons images
  nx-dev/feature-doc-viewer/src/lib/doc-viewer.tsx
  nx-dev/nx-dev/pages/_document.tsx
  nx-dev/nx-dev/pages/index.tsx
  nx-dev/nx-dev/pages/packages.tsx
  nx-dev/nx-dev/public/favicon.ico
  nx-dev/nx-dev/public/favicon/android-chrome-192x192.png
  nx-dev/nx-dev/public/favicon/android-chrome-512x512.png
  nx-dev/nx-dev/public/favicon/apple-touch-icon.png
  nx-dev/nx-dev/public/favicon/favicon-16x16.png
  nx-dev/nx-dev/public/favicon/favicon-32x32.png
  nx-dev/nx-dev/public/favicon/favicon.ico
  nx-dev/nx-dev/public/favicon/mstile-150x150.png
  nx-dev/nx-dev/public/favicon/safari-pinned-tab.svg
  nx-dev/nx-dev/public/images/apple-touch-icon.png
  nx-dev/nx-dev/public/images/favicon-16x16.png
  nx-dev/nx-dev/public/images/favicon-32x32.png
  nx-dev/nx-dev/public/images/nx-media.jpg
  nx-dev/nx-dev/public/images/safari-pinned-tab.svg
  nx-dev/nx-dev/public/socials/nx-media-monorepo.jpg
  nx-dev/nx-dev/public/socials/nx-media.png
Labels: type: docs

#13387 docs(nxdev): copy documentation files in sync
  nx-dev/nx-dev/next.config.js
Labels: type: docs

#13389 docs(nxdev): update nx cloud logo
  nx-dev/ui-markdoc/src/lib/tags/nx-cloud-section.component.tsx
Labels: type: docs

#13391 docs(nxdev): add banner announcement on documentation side
  nx-dev/ui-common/src/lib/announcement-banner.tsx
  nx-dev/ui-common/src/lib/documentation-header.tsx
Labels: type: docs

#13347 feat(core): enable linter on root projects
  e2e/linter/src/linter.test.ts
  packages/cypress/src/generators/cypress-project/cypress-project.ts
  packages/linter/package.json
  packages/linter/src/generators/init/global-eslint-config.ts
  packages/linter/src/generators/init/init-migration.ts
  packages/linter/src/generators/init/init.ts
  packages/linter/src/generators/lint-project/lint-project.ts
  packages/linter/src/generators/utils/eslint-file.ts
  packages/react/src/generators/application/application.ts
  packages/react/src/generators/application/lib/add-cypress.ts
  packages/react/src/utils/lint.ts
  packages/workspace/src/generators/preset/preset.ts
  tsconfig.base.json
Labels: scope: core

#13417 docs(nxdev): add 500 page illustration
  nx-dev/nx-dev/pages/500.tsx
  nx-dev/nx-dev/public/images/illustrations/500.svg
Labels: type: docs

#13418 docs(nxdev): add 404 page illustrations
  nx-dev/nx-dev/pages/404.tsx
  nx-dev/nx-dev/public/images/illustrations/404-1.svg
  nx-dev/nx-dev/public/images/illustrations/404-2.svg
  nx-dev/nx-dev/public/images/illustrations/404-3.svg
  nx-dev/nx-dev/public/images/illustrations/404-4.svg
Labels: type: docs

#13420 docs(nxdev): change -gray- usage for -slate-
  nx-dev/feature-doc-viewer/src/lib/doc-viewer.tsx
  nx-dev/ui-commands/src/lib/inline-command.tsx
  nx-dev/ui-common/src/lib/nx-users-showcase.tsx
  nx-dev/ui-common/src/lib/selector.tsx
  nx-dev/ui-community/src/lib/connect-with-us.tsx
  nx-dev/ui-community/src/lib/plugin-directory.tsx
  nx-dev/ui-conference/src/lib/conf-sponsors.tsx
  nx-dev/ui-home/src/lib/extensible-and-integrated.tsx
  nx-dev/ui-home/src/lib/extensible-and-integrated/graph-tab.tsx
  nx-dev/ui-home/src/lib/extensible-and-integrated/plugins-tab.tsx
  nx-dev/ui-home/src/lib/extensible-and-integrated/vscode-integration-tab.tsx
  nx-dev/ui-home/src/lib/migrations-and-code-generation.tsx
  nx-dev/ui-home/src/lib/monorepo-styles.tsx
  nx-dev/ui-home/src/lib/newsletter.tsx
  nx-dev/ui-home/src/lib/nx-is-fast.tsx
  nx-dev/ui-home/src/lib/nx-statistics.tsx
  nx-dev/ui-home/src/lib/testimonials.tsx
  nx-dev/ui-home/src/lib/why-is-nx-fast.tsx
  nx-dev/ui-sponsor-card/src/lib/sponsor-card.tsx
  nx-dev/ui-theme/src/lib/theme-switcher.component.tsx
Labels: type: docs

#13431 feat(linter): replace createReactEslintJson with extendReactEslintJson
  e2e/react-native/src/react-native.test.ts
  packages/detox/src/generators/application/lib/add-linting.ts
  packages/expo/src/utils/add-linting.ts
  packages/next/src/generators/application/lib/add-linting.ts
  packages/react-native/src/utils/add-linting.ts
  packages/react/index.ts
  packages/react/src/generators/library/library.ts
  packages/react/src/utils/lint.ts
Labels: scope: linter

#13432 fix(linter): ensure projectRootMappings exist when running eslint directly
  packages/eslint-plugin-nx/src/utils/project-graph-utils.ts
Labels: scope: linter

#13438 fix(core): generated package.json should not include duplicates and optional peer deeps
  e2e/node/src/node.test.ts
  packages/nx/package.json
  packages/nx/src/utils/create-package-json.ts
Labels: scope: core

#13480 docs(nxdev): add svg favicon for light & dark themes
  nx-dev/nx-dev/pages/_document.tsx
  nx-dev/nx-dev/public/favicon/favicon.svg
Labels: type: docs

#13482 docs(nxdev): remove title from document
  nx-dev/nx-dev/pages/_document.tsx
  nx-dev/ui-common/src/lib/header.tsx
  nx-dev/ui-home/src/lib/extensible-and-integrated/github-intergration-tab.tsx
  nx-dev/ui-home/src/lib/extensible-and-integrated/vscode-integration-tab.tsx
  nx-dev/ui-member-card/src/lib/member-card.tsx
Labels: type: docs

#13353 feat(testing): support root project generation for jest
  docs/generated/packages/jest.json
  e2e/jest/src/jest-root.test.ts
  e2e/jest/src/jest.test.ts
  e2e/linter/src/linter.test.ts
  packages/angular/src/generators/application/lib/add-unit-test-runner.ts
  packages/jest/index.ts
  packages/jest/src/generators/init/init.spec.ts
  packages/jest/src/generators/init/init.ts
  packages/jest/src/generators/init/schema.d.ts
  packages/jest/src/generators/init/schema.json
  packages/jest/src/generators/jest-project/files-angular/jest.config.ts__tmpl__
  packages/jest/src/generators/jest-project/files/jest.config.ts__tmpl__
  packages/jest/src/generators/jest-project/jest-project.spec.ts
  packages/jest/src/generators/jest-project/jest-project.ts
  packages/jest/src/generators/jest-project/lib/check-for-test-target.ts
  packages/jest/src/generators/jest-project/lib/create-files.ts
  packages/jest/src/generators/jest-project/lib/update-jestconfig.ts
  packages/jest/src/generators/jest-project/schema.d.ts
  packages/jest/src/generators/jest-project/schema.json
  packages/jest/src/utils/config/get-jest-projects.ts
  packages/react/src/generators/application/lib/add-jest.ts
  packages/react/src/generators/init/init.ts
  packages/workspace/src/generators/preset/preset.ts
Labels: scope: testing tools

#13485 docs(nxdev): externalize related documentation links into its own section
  nx-dev/data-access-documents/src/lib/documents.api.ts
  nx-dev/feature-doc-viewer/src/lib/content.tsx
  nx-dev/feature-package-schema-viewer/src/lib/content.tsx
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-list.tsx
  nx-dev/feature-package-schema-viewer/src/lib/parameter-view.tsx
  nx-dev/feature-package-schema-viewer/src/lib/ui/package-reference.tsx
  nx-dev/models-document/src/lib/documents.models.ts
  nx-dev/ui-markdoc/src/index.ts
  nx-dev/ui-markdoc/src/lib/nodes/helpers/transform-image-path.spec.ts
  nx-dev/ui-markdoc/src/lib/nodes/helpers/transform-image-path.ts
  nx-dev/ui-markdoc/src/lib/nodes/image.schema.ts
Labels: type: docs

#13523 docs(nxdev): fix layout on 404 & 500
  nx-dev/nx-dev/pages/404.tsx
  nx-dev/nx-dev/pages/500.tsx
Labels: type: docs
