Repository nrwl/nx, pull requests merged in 2022-09, with the labels that each got.

#11830 docs(nxdev): update home page links
  nx-dev/nx-dev/pages/index.tsx
  nx-dev/ui-home/src/lib/affected-command.tsx
  nx-dev/ui-home/src/lib/dependency-graph.tsx
  nx-dev/ui-home/src/lib/ecosystem-features.tsx
  nx-dev/ui-home/src/lib/experience-features.tsx
  nx-dev/ui-home/src/lib/getting-started.tsx
  nx-dev/ui-home/src/lib/monorepo-features.tsx
  nx-dev/ui-home/src/lib/vscode-plugin.tsx
Labels: type: docs

#11837 docs(core): add new nx cloud iframe sources
  docs/nx-cloud/intro/nx-cloud.md
Labels: type: docs

#11838 docs(nxdev): apply custom css for nxcloud iframes
  nx-dev/nx-dev/styles/main.css
Labels: scope: docs

#11850 docs(nxdev): add redirections for diataxis restructure
  nx-dev/nx-dev/next.config.js
  nx-dev/nx-dev/redirect-rules.config.js
  nx-dev/nx-dev/redirect-rules.config.spec.js
Labels: type: docs, scope: docs

#11851 docs(core): add free course playlist on youtube
  docs/shared/angular-tutorial/12-summary.md
  docs/shared/core-tutorial/06-summary.md
  docs/shared/node-tutorial/08-summary.md
  docs/shared/react-tutorial/12-summary.md
Labels: type: docs

#11852 docs(nxdev): remove unused nxconf assets
  nx-dev/nx-dev/public/images/conf/brainlylogo.svg
  nx-dev/nx-dev/public/images/conf/briebuglogo.svg
  nx-dev/nx-dev/public/images/conf/ciscologo.webp
  nx-dev/nx-dev/public/images/conf/herodevslogo.svg
  nx-dev/nx-dev/public/images/conf/ioniclogo.svg
  nx-dev/nx-dev/public/images/conf/kirils-ladovs.webp
  nx-dev/nx-dev/public/images/conf/oasisdigitallogo.svg
  nx-dev/nx-dev/public/images/conf/thinksterlogo.webp
  nx-dev/nx-dev/public/images/conf/vmwarelogo.svg
  nx-dev/nx-dev/public/images/conf/webrushlogo.svg
  nx-dev/nx-dev/public/images/conf/xltslogo.webp
  nx-dev/nx-dev/public/images/conf/yvonne-allen.webp
Labels: type: docs

#11952 fix(testing): add component-test target to namedInputs
  packages/angular/src/generators/cypress-component-configuration/cypress-component-configuration.ts
  packages/cypress/src/generators/cypress-component-project/cypress-component-project.spec.ts
  packages/cypress/src/generators/cypress-component-project/cypress-component-project.ts
  packages/cypress/src/generators/cypress-component-project/files/cypress/tsconfig.cy.json
  packages/cypress/src/generators/cypress-component-project/files/tsconfig.cy.json
  packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.spec.ts
  packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.ts
  packages/react/src/generators/cypress-component-configuration/lib/update-configs.ts
Labels: scope: testing tools

#11961 fix(testing): change import to not include angular
  packages/cypress/src/migrations/update-14-7-0/update-cypress-version-if-10.ts
Labels: scope: testing tools

#11974 fix(linter): handle missing task graph in hasher on print-affected
  packages/linter/src/executors/eslint/hasher.ts
Labels: scope: linter

#11963 fix(testing): normalize paths for component-testing
  docs/generated/packages/angular.json
  docs/generated/packages/react.json
  e2e/angular-extensions/src/cypress-component-tests.test.ts
  packages/angular/plugins/component-testing.ts
  packages/angular/src/generators/component-test/schema.json
  packages/angular/src/generators/cypress-component-configuration/schema.json
  packages/cypress/plugins/cypress-preset.ts
  packages/react/src/generators/component-test/schema.json
  packages/react/src/generators/cypress-component-configuration/schema.json
Labels: scope: testing tools

#11998 docs(core): add description property on packages.json
  docs/packages.json
  scripts/documentation/package-schemas/generatePackageSchemas.ts
Labels: type: docs

#11999 docs(nxdev): rename plugins section into community & reference into packages
  nx-dev/ui-common/src/lib/header.tsx
Labels: type: docs

#12000 docs(nxdev): redirect executors and generators to current package
  nx-dev/ui-common/src/lib/breadcrumbs.tsx
Labels: type: docs

#12014 fix(testing): use cypress generated tsconfig for angular ct
  e2e/angular-extensions/src/cypress-component-tests.test.ts
  packages/angular/plugins/component-testing.ts
Labels: scope: testing tools

#12017 docs(nxdev): add auto-generated category/index page with custom content if needed
  docs/map.json
  nx-dev/data-access-documents/src/lib/documents.api.ts
  nx-dev/models-document/src/lib/documents.models.ts
  nx-dev/nx-dev/pages/[...segments].tsx
  nx-dev/ui-markdoc/src/index.ts
  nx-dev/ui-markdoc/src/lib/tags/card-list.component.tsx
  nx-dev/ui-markdoc/src/lib/tags/card-list.schema.ts
  scripts/documentation/map-link-checker.ts
  scripts/documentation/open-graph/generate-images.ts
  scripts/documentation/package-schemas/package-metadata.ts
Labels: type: docs

#11994 docs(nxdev): automatic related docs
  docs/generated/packages/nx.json
  docs/map.json
  docs/shared/concepts/how-project-graph-is-built.md
  docs/shared/core-features/automate-updating-dependencies.md
  docs/shared/core-features/cache-task-results.md
  docs/shared/core-features/distribute-task-execution.md
  docs/shared/core-features/enforce-project-boundaries.md
  docs/shared/core-features/explore-graph.md
  docs/shared/core-features/integrate-with-editors.md
  docs/shared/core-features/run-tasks.md
  docs/shared/plugin-features/create-your-own-plugin.md
  docs/shared/plugin-features/use-code-generators.md
  docs/shared/plugin-features/use-task-executors.md
  docs/shared/reference/environment-variables.md
  nx-dev/data-access-documents/src/lib/documents.api.ts
  nx-dev/models-document/src/lib/documents.models.ts
Labels: type: docs

#12039 docs(misc): update package descriptions to be more consistent
  docs/generated/packages/detox.json
  docs/generated/packages/devkit.json
  docs/generated/packages/eslint-plugin-nx.json
  docs/generated/packages/express.json
  docs/generated/packages/js.json
  docs/generated/packages/linter.json
  docs/generated/packages/nest.json
  docs/generated/packages/next.json
  docs/generated/packages/node.json
  docs/generated/packages/nx-plugin.json
  docs/generated/packages/nx.json
  docs/generated/packages/react-native.json
  docs/generated/packages/react.json
  docs/generated/packages/rollup.json
  docs/generated/packages/storybook.json
  docs/generated/packages/webpack.json
  docs/generated/packages/workspace.json
  docs/packages.json
  packages/detox/package.json
  packages/devkit/package.json
  packages/eslint-plugin-nx/package.json
  packages/express/package.json
  packages/js/package.json
  packages/linter/package.json
  packages/nest/package.json
  packages/next/package.json
  packages/node/package.json
  packages/nx-plugin/package.json
  packages/nx/package.json
  packages/react-native/package.json
  packages/react/package.json
  packages/rollup/package.json
  packages/storybook/package.json
  packages/webpack/package.json
  packages/workspace/package.json
Labels: type: docs

#12079 docs(nxdev): enable back categories/index lookup resolution
  nx-dev/nx-dev/pages/[...segments].tsx
Labels: type: docs

#12080 docs(core): update internal link path reference
  docs/shared/concepts/dte-guide.md
  docs/shared/core-features/distribute-task-execution.md
  docs/shared/core-features/run-tasks.md
Labels: type: docs

#12084 docs(misc): add or modify various package descriptions
  docs/generated/packages/cra-to-nx.json
  docs/generated/packages/create-nx-plugin.json
  docs/generated/packages/expo.json
  docs/packages.json
  packages/cra-to-nx/package.json
  packages/create-nx-plugin/package.json
  packages/expo/package.json
Labels: type: docs

#12085 docs(nxdev): make sure category/index returns null if nothing is found
  nx-dev/data-access-documents/src/lib/documents.api.ts
  nx-dev/nx-dev/pages/[...segments].tsx
Labels: type: docs

#12086 docs(nxdev): add expo package icon
  nx-dev/nx-dev/public/images/icons/expo.svg
  nx-dev/ui-references/src/lib/icons-map.ts
Labels: type: docs

#12081 docs(nxdev): show package description as fallback
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-list.tsx
Labels: type: docs

#12088 docs(nxdev): convert callout html markup to use spans
  nx-dev/ui-markdoc/src/lib/tags/callout.component.tsx
Labels: type: docs

#12083 docs(nxdev): update internal reference links
  README.md
  docs/generated/packages/storybook.json
  docs/shared/guides/storybook/storybook-composition-setup.md
  docs/shared/migration/migration-cra.md
  nx-dev/feature-package-schema-viewer/src/lib/content.tsx
  nx-dev/nx-dev/redirect-rules.config.js
  nx-dev/ui-home/src/lib/experience-features.tsx
  packages/add-nx-to-monorepo/README.md
  packages/add-nx-to-monorepo/src/add-nx-to-monorepo.ts
  packages/angular/README.md
  packages/react-native/README.md
  packages/react/README.md
  packages/web/README.md
  packages/workspace/src/generators/workspace/files/README.md__tmpl__
  packages/workspace/src/migrations/update-12-5-0/add-target-dependencies.ts
  packages/workspace/src/utilities/buildable-libs-utils.ts
  scripts/readme-fragments/content.md
  scripts/readme-fragments/resources.md
Labels: type: docs

#11811 fix(linter): consider the default public API filename when checking for secondary entrypoints
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: scope: linter

#12040 fix(testing): improve return type of getJestProjects
  packages/jest/src/utils/config/get-jest-projects.ts
Labels: scope: testing tools

#12121 docs(nx-cloud): update no-helm repository link
  docs/nx-cloud/private/get-started.md
Labels: type: docs

#11981 chore(repo): start and cleanup daemon after every e2e test
  .circleci/config.yml
  packages/nx/src/daemon/client/client.ts
Labels: scope: repo

#11817 chore(repo): update dependency `jsonc-parser` to v3.2.0
  package.json
  packages/nx/package.json
Labels: scope: repo

#11953 feat(core): add package manager parsers and stringifiers
  package.json
  packages/angular/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/cypress/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/linter/src/utils/convert-tslint-to-eslint/__snapshots__/convert-to-eslint-config.spec.ts.snap
  packages/nest/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/nx/package.json
  packages/nx/src/utils/lock-file/__fixtures__/npm.lock.ts
  packages/nx/src/utils/lock-file/__fixtures__/pnpm.lock.ts
  packages/nx/src/utils/lock-file/__fixtures__/yarn.lock.ts
  packages/nx/src/utils/lock-file/__snapshots__/npm.spec.ts.snap
  packages/nx/src/utils/lock-file/__snapshots__/pnpm.spec.ts.snap
  packages/nx/src/utils/lock-file/__snapshots__/yarn.spec.ts.snap
  packages/nx/src/utils/lock-file/lock-file-type.ts
  packages/nx/src/utils/lock-file/lock-file.ts
  packages/nx/src/utils/lock-file/npm.spec.ts
  packages/nx/src/utils/lock-file/npm.ts
  packages/nx/src/utils/lock-file/pnpm.spec.ts
  packages/nx/src/utils/lock-file/pnpm.ts
  packages/nx/src/utils/lock-file/utils.ts
  packages/nx/src/utils/lock-file/yarn.spec.ts
  packages/nx/src/utils/lock-file/yarn.ts
  packages/nx/tsconfig.lib.json
  yarn.lock
Labels: type: feature, scope: core

#12105 feat(core): add yarn lock file pruning
  packages/nx/src/utils/lock-file/__fixtures__/npm.lock.ts
  packages/nx/src/utils/lock-file/__fixtures__/pnpm.lock.ts
  packages/nx/src/utils/lock-file/__fixtures__/yarn.lock.ts
  packages/nx/src/utils/lock-file/__snapshots__/pnpm.spec.ts.snap
  packages/nx/src/utils/lock-file/lock-file-type.ts
  packages/nx/src/utils/lock-file/lock-file.ts
  packages/nx/src/utils/lock-file/npm.ts
  packages/nx/src/utils/lock-file/pnpm.ts
  packages/nx/src/utils/lock-file/yarn.spec.ts
  packages/nx/src/utils/lock-file/yarn.ts
Labels: type: feature, scope: core

#11764 docs(nxdev): add a custom 500 page
  nx-dev/nx-dev/pages/500.tsx
Labels: type: docs

#12206 docs(core): fix core tutorial 03 part interpolation error
  docs/shared/core-tutorial/03-share-assets.md
Labels: type: docs

#12205 docs(nxdev): enable scroll restoration
  nx-dev/nx-dev/next.config.js
Labels: type: docs

#12211 docs(nxdev): remove duplicated example data on generator page
  nx-dev/feature-package-schema-viewer/src/lib/content.tsx
Labels: type: docs

#12215 docs(web): fix create-nx-workspace command in example
  docs/generated/packages/web.json
  docs/shared/web-plugin.md
Labels: type: docs

#12209 docs(testing): add cypress example docs
  docs/generated/packages/cypress.json
  packages/cypress/docs/cypress-component-project-examples.md
  packages/cypress/docs/cypress-examples.md
  packages/cypress/docs/cypress-project-examples.md
  packages/cypress/src/executors/cypress/schema.json
  packages/cypress/src/generators/cypress-component-project/schema.json
  packages/cypress/src/generators/cypress-project/schema.json
Labels: type: docs, scope: testing tools

#12210 docs(testing): add jest example docs
  docs/generated/packages/jest.json
  packages/jest/docs/jest-examples.md
  packages/jest/src/executors/jest/schema.json
Labels: type: docs, scope: testing tools

#12214 docs(bundling): add examples for esbuild executor
  docs/generated/packages/esbuild.json
  packages/esbuild/docs/esbuild-examples.md
  packages/esbuild/src/executors/esbuild/schema.json
  packages/esbuild/src/generators/esbuild-project/esbuild-project.ts
Labels: type: docs

#12149 fix(testing): include cypress commands in tsconfig
  packages/cypress/src/generators/cypress-component-project/cypress-component-project.spec.ts
  packages/cypress/src/generators/cypress-component-project/files/cypress/tsconfig.cy.json
Labels: scope: testing tools

#12284 docs(nxdev): add new Nx conf lightning speaker
  nx-dev/nx-dev/public/images/conf/kennie-davis.webp
  nx-dev/ui-conference/src/lib/conf-schedule-short.tsx
  nx-dev/ui-conference/src/lib/conf-speakers.tsx
Labels: type: docs

#11896 fix(angular): switch to using jasmine-marbles for certain symbols
  packages/angular/migrations.json
  packages/angular/ng-package.json
  packages/angular/package.json
  packages/angular/src/migrations/update-15-0-0/switch-to-jasmine-marbles.spec.ts
  packages/angular/src/migrations/update-15-0-0/switch-to-jasmine-marbles.ts
  packages/angular/src/utils/versions.ts
  packages/angular/testing/index.ts
Labels: target: next major version

#11930 feat(angular): create routes file pattern
  docs/generated/packages/angular.json
  packages/angular/src/generators/application/__snapshots__/application.spec.ts.snap
  packages/angular/src/generators/application/application.spec.ts
  packages/angular/src/generators/application/files/src/app/app.routes.ts__tpl__
  packages/angular/src/generators/application/lib/convert-to-standalone-app.ts
  packages/angular/src/generators/application/lib/create-files.ts
  packages/angular/src/generators/application/lib/root-router-config.ts
  packages/angular/src/generators/host/__snapshots__/host.spec.ts.snap
  packages/angular/src/generators/host/host.ts
  packages/angular/src/generators/library/__snapshots__/library.spec.ts.snap
  packages/angular/src/generators/library/lib/add-children.ts
  packages/angular/src/generators/library/lib/add-lazy-loaded-router-configuration.ts
  packages/angular/src/generators/library/lib/add-load-children.ts
  packages/angular/src/generators/library/lib/add-module.ts
  packages/angular/src/generators/library/lib/add-router-configuration.ts
  packages/angular/src/generators/library/lib/add-standalone-component.ts
  packages/angular/src/generators/library/lib/normalized-schema.ts
  packages/angular/src/generators/library/library.spec.ts
  packages/angular/src/generators/library/schema.d.ts
  packages/angular/src/generators/library/schema.json
  packages/angular/src/generators/remote/__snapshots__/remote.spec.ts.snap
  packages/angular/src/generators/remote/remote.spec.ts
  packages/angular/src/generators/setup-mf/__snapshots__/setup-mf.spec.ts.snap
  packages/angular/src/generators/setup-mf/files/entry-module-files/entry.module.ts__tmpl__
  packages/angular/src/generators/setup-mf/files/entry-module-files/entry.routes.ts__tmpl__
  packages/angular/src/generators/setup-mf/files/standalone-entry-component-files/entry.routes.ts__tmpl__
  packages/angular/src/generators/setup-mf/files/webpack/module-federation.config.js__tmpl__
  packages/angular/src/generators/setup-mf/lib/add-remote-entry.ts
  packages/angular/src/generators/setup-mf/lib/add-remote-to-host.ts
  packages/angular/src/generators/setup-mf/lib/fix-bootstrap.ts
  packages/angular/src/generators/setup-mf/setup-mf.spec.ts
  packages/angular/src/utils/nx-devkit/ast-utils.ts
  packages/angular/src/utils/nx-devkit/route-utils.spec.ts
  packages/angular/src/utils/nx-devkit/route-utils.ts
  packages/angular/src/utils/nx-devkit/standalone-utils.spec.ts
  packages/angular/src/utils/nx-devkit/standalone-utils.ts
Labels: target: next major version

#12293 chore(repo): improve commit lint script to allow breaking change syntax
  scripts/commit-lint.js
Labels: scope: repo

#11989 cleanup(angular): rename webpack-server executor to webpack-dev-server
  docs/generated/packages/angular.json
  docs/packages.json
  docs/shared/guides/module-federation/dynamic-mfe-angular.md
  docs/shared/guides/use-environment-variables-in-angular.md
  nx-dev/nx-dev-e2e/src/integration/packages.spec.ts
  nx-dev/nx-dev/redirect-rules.config.js
  packages/angular/docs/webpack-dev-server-examples.md
  packages/angular/executors.json
  packages/angular/executors.ts
  packages/angular/migrations.json
  packages/angular/src/builders/module-federation-dev-server/module-federation-dev-server.impl.ts
  packages/angular/src/builders/webpack-dev-server/lib/index.ts
  packages/angular/src/builders/webpack-dev-server/lib/normalize-options.ts
  packages/angular/src/builders/webpack-dev-server/schema.d.ts
  packages/angular/src/builders/webpack-dev-server/schema.json
  packages/angular/src/builders/webpack-dev-server/webpack-dev-server.impl.ts
  packages/angular/src/generators/setup-mf/lib/setup-serve-target.ts
  packages/angular/src/generators/setup-mf/setup-mf.spec.ts
  packages/angular/src/migrations/update-13-2-0/update-angular-config.ts
  packages/angular/src/migrations/update-14-8-0/rename-webpack-server.spec.ts
  packages/angular/src/migrations/update-14-8-0/rename-webpack-server.ts
Labels: target: next major version

#10708 fix(core): Trailing slash in outputs array prevents correct caching
  e2e/nx-misc/src/extras.test.ts
  packages/nx/src/tasks-runner/cache.ts
Labels: scope: core
