Repository nrwl/nx, pull requests merged in 2022-01, with the labels that each got.

#8434 fix(testing): support cypress `--tag` arg
  docs/default/api-cypress/executors/cypress.md
  packages/cypress/src/executors/cypress/cypress.impl.ts
  packages/cypress/src/executors/cypress/schema.json
Labels: scope: testing tools

#7816 fix(testing): Create root babel config if one isn't present
  e2e/jest/src/jest.test.ts
  packages/jest/migrations.json
  packages/jest/src/generators/init/init.ts
  packages/jest/src/generators/jest-project/jest-project.spec.ts
  packages/jest/src/generators/jest-project/lib/create-files.ts
  packages/jest/src/migrations/update-13-4-4/add-missing-root-babel-config.spec.ts
  packages/jest/src/migrations/update-13-4-4/add-missing-root-babel-config.ts
Labels: scope: node, scope: testing tools

#8542 fix(core): add version field to npm-package generator
  packages/workspace/src/generators/npm-package/npm-package.spec.ts
  packages/workspace/src/generators/npm-package/npm-package.ts
Labels: scope: core

#8494 fix(storybook): handle defaultProject issues with projectBuildConfig flag
  packages/storybook/migrations.json
  packages/storybook/src/executors/build-storybook/build-storybook.impl.spec.ts
  packages/storybook/src/executors/storybook/storybook.impl.spec.ts
  packages/storybook/src/executors/utils.ts
  packages/storybook/src/generators/configuration/configuration.spec.ts
  packages/storybook/src/generators/configuration/configuration.ts
  packages/storybook/src/migrations/update-13-4-6/__snapshots__/set-project-build-config.spec.ts.snap
  packages/storybook/src/migrations/update-13-4-6/set-project-build-config.spec.ts
  packages/storybook/src/migrations/update-13-4-6/set-project-build-config.ts
  packages/storybook/src/migrations/update-13-4-6/test-configs/custom-names-config.json
  packages/storybook/src/migrations/update-13-4-6/test-configs/default-config.json
  packages/storybook/src/migrations/update-13-4-6/test-configs/non-angular.json
Labels: scope: storybook

#8147 fix(linter): remove @typescript-eslint/no-unused-vars override
  e2e/react-native/src/react-native.test.ts
  packages/eslint-plugin-nx/src/configs/typescript.ts
  packages/react/src/generators/application/files/css-module/src/app/__fileName__.tsx__tmpl__
Labels: scope: linter

#8668 feat(linter): add warning to nx rule when project graph is unavailable
  e2e/utils/index.ts
  packages/eslint-plugin-nx/package.json
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
Labels: scope: linter

#8708 fix(linter): handle missing project tslint during conversion
  packages/linter/src/utils/convert-tslint-to-eslint/__snapshots__/project-converter.spec.ts.snap
  packages/linter/src/utils/convert-tslint-to-eslint/project-converter.spec.ts
  packages/linter/src/utils/convert-tslint-to-eslint/project-converter.ts
Labels: scope: linter
