Repository nrwl/nx, pull requests merged in 2022-07, with the labels that each got.

#10969 docs(core): enhance markdown markup
  docs/shared/angular-tutorial/01-create-application.md
  docs/shared/angular-tutorial/05-add-node-app.md
  docs/shared/angular-tutorial/10-computation-caching.md
  docs/shared/configuration/packagejson.md
  docs/shared/configuration/projectjson.md
  docs/shared/core-tutorial/01-create-blog.md
  docs/shared/core-tutorial/03-share-assets.md
  docs/shared/daemon.md
  docs/shared/eslint.md
  docs/shared/extending-nx/devkit-and-nx-plugins.md
  docs/shared/extending-nx/project-graph-plugins.md
  docs/shared/extending-nx/project-inference-plugins.md
  docs/shared/generators/creating-files.md
  docs/shared/generators/workspace-generators.md
  docs/shared/getting-started/nx-and-angular.md
  docs/shared/getting-started/nx-and-react.md
  docs/shared/guides/environment-variables.md
  docs/shared/guides/misc-ngrx.md
  docs/shared/guides/module-federation/dynamic-mfe-angular.md
  docs/shared/guides/module-federation/faster-builds.md
  docs/shared/guides/module-federation/micro-frontend-architecture.md
  docs/shared/guides/nx-and-ts.md
  docs/shared/guides/nx-devkit-angular-devkit.md
  docs/shared/guides/setup-incremental-builds-angular.md
  docs/shared/guides/turbo-and-nx.md
  docs/shared/guides/using-tailwind-css-with-angular-projects.md
  docs/shared/guides/why-monorepos.md
  docs/shared/incremental-builds.md
  docs/shared/migration/adding-to-monorepo.md
  docs/shared/migration/lerna-and-nx.md
  docs/shared/migration/manual.md
  docs/shared/migration/migration-angular.md
  docs/shared/migration/migration-angularjs.md
  docs/shared/migration/migration-cra.md
  docs/shared/monorepo-nx-enterprise.md
  docs/shared/monorepo-tags.md
  docs/shared/node-tutorial/01-create-application.md
  docs/shared/node-tutorial/02-display-todos.md
  docs/shared/node-tutorial/04-create-libs.md
  docs/shared/react-tutorial/01-create-application.md
  docs/shared/react-tutorial/05-add-node-app.md
  docs/shared/react-tutorial/08-create-libs.md
  docs/shared/tools-workspace-builders.md
  docs/shared/update.md
  docs/shared/using-executors.md
  docs/shared/using-nx/affected.md
  docs/shared/using-nx/caching.md
  docs/shared/using-nx/dte.md
  docs/shared/using-nx/nx-cli.md
  docs/shared/workspace/applications-and-libraries.md
  docs/shared/workspace/buildable-and-publishable-libraries.md
  docs/shared/workspace/grouping-libraries.md
  nx-dev/ui-markdoc/src/lib/tags/callout.component.tsx
  nx-dev/ui-markdoc/src/lib/tags/nx-cloud-section.component.tsx
  nx-dev/ui-markdoc/src/lib/tags/tabs.component.tsx
Labels: type: docs

#10966 chore(core): clean up unused dependencies
  nx-dev/data-access-documents/src/lib/documents.api.ts
  package.json
  yarn.lock
Labels: type: cleanup

#11060 docs(nxdev): set default shallow link prop to false
  nx-dev/ui-markdoc/src/lib/nodes/link.schema.ts
Labels: type: docs

#11067 docs(nxdev): update GitHub workflow to v0.6
  docs/shared/monorepo-ci-github-actions.md
Labels: scope: docs

#11068 feat(core): update GitHub CI workflow generator to v0.6
  packages/workspace/src/generators/ci-workflow/__snapshots__/ci-workflow.spec.ts.snap
  packages/workspace/src/generators/ci-workflow/files/github/.github/workflows/__workflowFileName__.yml__tmpl__
Labels: scope: core

#11071 feat(repo): add lock file linting to commit check, PR and nightly
  .circleci/config.yml
  .github/workflows/npm-audit.yml
  package.json
  scripts/check-lock-files.js
  yarn.lock
Labels: scope: repo

#11082 docs(testing): update screenshot/video paths to correct location
  docs/generated/packages/cypress.json
  docs/shared/cypress-component-testing.md
  docs/shared/cypress-plugin.md
Labels: scope: testing tools

#11099 chore(repo): add better status notification to audit run
  .github/workflows/npm-audit.yml
Labels: scope: repo

#11123 fix(repo): explicitly stop all agents on failure
  .circleci/config.yml
Labels: scope: repo

#11085 docs(nxdev): move cli content into nx
  docs/generated/packages/cli.json
  docs/generated/packages/nx.json
  docs/map.json
  docs/packages.json
  nx-dev/nx-dev-e2e/src/integration/packages.spec.ts
  nx-dev/nx-dev/next.config.js
  nx-dev/nx-dev/redirect-rules.config.js
  scripts/documentation/documentation.ts
  scripts/documentation/package-schemas/generatePackageSchemas.ts
  scripts/documentation/package-schemas/package-metadata.ts
Labels: type: docs

#11133 docs(nxdev): add press kit link in footer
  nx-dev/ui-common/src/lib/footer.tsx
Labels: type: docs

#11142 docs(nxdev): upgrade next-sitemap dependency
  package.json
  yarn.lock
Labels: type: docs

#11147 docs(nxdev): internal link checker now supports indexes
  scripts/documentation/internal-link-checker.ts
Labels: type: docs

#11150 docs(nxdev): remove gray-matter dependency
  nx-dev/data-access-documents/src/lib/documents.api.ts
  nx-dev/feature-doc-viewer/src/lib/content.tsx
  nx-dev/feature-doc-viewer/src/lib/doc-viewer.tsx
  nx-dev/models-document/src/lib/documents.models.ts
  nx-dev/ui-markdoc/src/index.ts
  nx-dev/ui-markdoc/src/lib/nodes/heading.schema.ts
  nx-dev/ui-markdoc/src/lib/nodes/image.schema.ts
  package.json
  yarn.lock
Labels: type: docs

#11200 fix(testing): correctly migrate plugins file if present
  packages/cypress/src/generators/migrate-to-cypress-ten/__snapshots__/migrate-to-cypress-ten.spec.ts.snap
  packages/cypress/src/generators/migrate-to-cypress-ten/conversion.util.ts
  packages/cypress/src/generators/migrate-to-cypress-ten/migrate-to-cypress-ten.spec.ts
  packages/cypress/src/generators/migrate-to-cypress-ten/migrate-to-cypress-ten.ts
Labels: scope: testing tools

#11226 feat(core): improve graph utils matrix generation
  packages/workspace/src/utils/graph-utils.ts
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: scope: core, scope: linter

#11112 fix(linter): update typescript eslint dependency
  package.json
  packages/eslint-plugin-nx/package.json
  packages/eslint-plugin-nx/src/resolve-workspace-rules.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin-nx/src/utils/create-eslint-rule.ts
  packages/linter/migrations.json
  packages/linter/src/generators/workspace-rule/__snapshots__/workspace-rule.spec.ts.snap
  packages/linter/src/generators/workspace-rule/files/__name__.spec.ts__tmpl__
  packages/linter/src/generators/workspace-rule/files/__name__.ts__tmpl__
  packages/linter/src/migrations/update-14-4-4/__snapshots__/experimental-to-utils-deps.spec.ts.snap
  packages/linter/src/migrations/update-14-4-4/experimental-to-utils-deps.spec.ts
  packages/linter/src/migrations/update-14-4-4/experimental-to-utils-deps.ts
  packages/linter/src/migrations/update-14-4-4/experimental-to-utils-rules.spec.ts
  packages/linter/src/migrations/update-14-4-4/experimental-to-utils-rules.ts
  tools/eslint-rules/rules/valid-schema-description.spec.ts
  tools/eslint-rules/rules/valid-schema-description.ts
  yarn.lock
Labels: scope: linter

#11232 docs(nxdev): convert notes into callouts
  docs/generated/packages/angular.json
  docs/generated/packages/react-native.json
  docs/generated/packages/storybook.json
  docs/generated/packages/web.json
  docs/nx-cloud/private/get-started.md
  docs/shared/guides/environment-variables.md
  docs/shared/guides/react-18.md
  docs/shared/guides/react-native.md
  docs/shared/guides/storybook/extra-topics-for-angular-projects.md
  docs/shared/guides/storybook/migrate-webpack-final-angular.md
  docs/shared/guides/storybook/migrate-webpack-final-react.md
  docs/shared/guides/webpack-5.md
  docs/shared/react-native-plugin.md
  docs/shared/web-plugin.md
  packages/angular/generators.json
  packages/angular/src/generators/convert-to-with-mf/schema.json
Labels: type: docs

#11061 docs(nxdev): add references page
  nx-dev/data-access-menu/src/lib/menu.api.ts
  nx-dev/data-access-menu/src/lib/menu.utils.ts
  nx-dev/feature-package-schema-viewer/src/lib/content.tsx
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-list.tsx
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-viewer.tsx
  nx-dev/feature-search/src/lib/algolia-search.tsx
  nx-dev/nx-dev/pages/[...segments].tsx
  nx-dev/nx-dev/pages/packages.tsx
  nx-dev/nx-dev/public/images/icons/angular.svg
  nx-dev/nx-dev/public/images/icons/cypress.svg
  nx-dev/nx-dev/public/images/icons/eslint.svg
  nx-dev/nx-dev/public/images/icons/express.svg
  nx-dev/nx-dev/public/images/icons/html5.svg
  nx-dev/nx-dev/public/images/icons/javascript.svg
  nx-dev/nx-dev/public/images/icons/jest.svg
  nx-dev/nx-dev/public/images/icons/nestjs.svg
  nx-dev/nx-dev/public/images/icons/nextdotjs.svg
  nx-dev/nx-dev/public/images/icons/nodedotjs.svg
  nx-dev/nx-dev/public/images/icons/nx.svg
  nx-dev/nx-dev/public/images/icons/react.svg
  nx-dev/nx-dev/public/images/icons/storybook.svg
  nx-dev/ui-common/src/lib/breadcrumbs.tsx
  nx-dev/ui-common/src/lib/header.tsx
  nx-dev/ui-references/.babelrc
  nx-dev/ui-references/.eslintrc.json
  nx-dev/ui-references/README.md
  nx-dev/ui-references/jest.config.ts
  nx-dev/ui-references/project.json
  nx-dev/ui-references/src/index.ts
  nx-dev/ui-references/src/lib/icons-map.ts
  nx-dev/ui-references/src/lib/references-index-item.tsx
  nx-dev/ui-references/src/lib/references-nav-list.tsx
  nx-dev/ui-references/src/lib/references-package-card.tsx
  nx-dev/ui-references/src/lib/references-section.tsx
  nx-dev/ui-references/tsconfig.json
  nx-dev/ui-references/tsconfig.lib.json
  nx-dev/ui-references/tsconfig.spec.json
  nx.json
  tsconfig.base.json
  workspace.json
Labels: type: docs

#11244 docs(nxdev): convert notes into callouts
  docs/generated/packages/nx-plugin.json
  docs/nx-cloud/private/auth-github.md
  docs/nx-cloud/private/auth-single-admin.md
  docs/shared/core-tutorial/03-share-assets.md
  docs/shared/guides/customize-webpack.md
  docs/shared/guides/react-18.md
  docs/shared/guides/setup-incremental-builds-angular.md
  docs/shared/monorepo-ci-circle-ci.md
  docs/shared/nx-plugin.md
  docs/shared/update.md
Labels: type: docs

#11249 docs(storybook): extra topic notes to callouts update
  docs/generated/packages/storybook.json
  docs/shared/guides/storybook/extra-topics-for-angular-projects.md
Labels: type: docs

#11238 fix(linter): correctly fix absolute imports across package boundaries
  e2e/linter/src/linter.test.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
Labels: scope: linter

#11251 fix(core): improve performance of enforce-module-boundaries linting rule on Windows
  packages/workspace/src/utils/runtime-lint-utils.spec.ts
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: scope: linter

#11261 docs(nxdev): add icon to github link button
  nx-dev/feature-package-schema-viewer/src/lib/content.tsx
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-list.tsx
Labels: type: docs

#11265 docs(nxdev): add github example callout
  nx-dev/ui-markdoc/src/index.ts
  nx-dev/ui-markdoc/src/lib/tags/github-repository.component.tsx
  nx-dev/ui-markdoc/src/lib/tags/github-repository.schema.ts
  nx-dev/ui-markdoc/src/lib/tags/youtube.components.tsx
Labels: type: docs

#11308 docs(nxdev): add filter button & state on packages view
  nx-dev/nx-dev/pages/packages.tsx
  nx-dev/ui-references/src/lib/references-index-item.tsx
Labels: type: docs

#11312 docs(nxdev): add custom 404
  nx-dev/nx-dev/pages/404.tsx
Labels: type: docs

#11314 docs(nxdev): apply github repository callout cmp
  docs/shared/distributed-builds.md
  docs/shared/examples/apollo-react.md
  docs/shared/examples/caching.md
  docs/shared/examples/dte.md
  docs/shared/examples/nx-examples.md
  docs/shared/examples/react-nx.md
  docs/shared/extending-nx/project-graph-plugins.md
  docs/shared/guides/module-federation/faster-builds.md
  docs/shared/guides/setup-incremental-builds-angular.md
  docs/shared/incremental-builds.md
  docs/shared/migration/migration-angularjs.md
  docs/shared/migration/migration-cra.md
  docs/shared/tools-workspace-builders.md
Labels: type: docs

#11315 docs(nxdev): add type & simplify default notation
  nx-dev/nx-dev/pages/[...segments].tsx
  nx-dev/nx-dev/pages/_app.tsx
  nx-dev/nx-dev/pages/_document.tsx
  nx-dev/nx-dev/pages/community.tsx
  nx-dev/nx-dev/pages/conf.tsx
  nx-dev/nx-dev/pages/index.tsx
  nx-dev/nx-dev/pages/packages.tsx
Labels: type: docs

#11316 docs(nxdev): add type & simplify default notation
  nx-dev/ui-commands/src/lib/inline-command.tsx
Labels: type: docs

#11317 docs(nxdev): add type & simplify default notation
  nx-dev/ui-common/src/lib/announcement-banner.tsx
  nx-dev/ui-common/src/lib/breadcrumbs.tsx
  nx-dev/ui-common/src/lib/footer.tsx
  nx-dev/ui-common/src/lib/header.tsx
  nx-dev/ui-common/src/lib/npx-create-nx-workspace.tsx
  nx-dev/ui-common/src/lib/nx-users-showcase.tsx
  nx-dev/ui-common/src/lib/plugin-card.spec.tsx
  nx-dev/ui-common/src/lib/plugin-card.tsx
  nx-dev/ui-common/src/lib/selector.tsx
  nx-dev/ui-common/src/lib/sidebar.tsx
  nx-dev/ui-common/src/lib/testimonial-card.tsx
Labels: type: docs

#11319 docs(nxdev): add type & simplify default notation
  nx-dev/ui-community/src/lib/connect-with-us.tsx
  nx-dev/ui-community/src/lib/create-nx-plugin.tsx
  nx-dev/ui-community/src/lib/plugin-directory.tsx
Labels: type: docs

#11320 docs(nxdev): add type & simplify default notation
  nx-dev/ui-conference/src/lib/conf-workshop.tsx
Labels: type: docs

#11321 docs(nxdev): update home lib type & default export
  nx-dev/ui-home/src/lib/affected-command.tsx
  nx-dev/ui-home/src/lib/cloud-support.tsx
  nx-dev/ui-home/src/lib/dependency-graph.tsx
  nx-dev/ui-home/src/lib/ecosystem-features.tsx
  nx-dev/ui-home/src/lib/egghead-courses.tsx
  nx-dev/ui-home/src/lib/event-banner.tsx
  nx-dev/ui-home/src/lib/experience-features.tsx
  nx-dev/ui-home/src/lib/getting-started.tsx
  nx-dev/ui-home/src/lib/monorepo-features.tsx
  nx-dev/ui-home/src/lib/nx-playbook.tsx
  nx-dev/ui-home/src/lib/open-platform.tsx
  nx-dev/ui-home/src/lib/open-source-projects.tsx
  nx-dev/ui-home/src/lib/performance.tsx
  nx-dev/ui-home/src/lib/testimonials.tsx
  nx-dev/ui-home/src/lib/vscode-plugin.tsx
  nx-dev/ui-home/src/lib/youtube-channel.tsx
Labels: type: docs

#11322 docs(nxdev): add sponsor-card type
  nx-dev/ui-sponsor-card/src/lib/sponsor-card.tsx
Labels: type: docs

#11377 docs(nxdev): doc-viewer export type
  nx-dev/feature-doc-viewer/src/lib/content.tsx
  nx-dev/feature-doc-viewer/src/lib/doc-viewer.tsx
Labels: type: docs

#11378 docs(nxdev): update package schema viewer export type
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-list.tsx
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-viewer.tsx
  nx-dev/feature-package-schema-viewer/src/lib/schema-editor.tsx
  nx-dev/feature-package-schema-viewer/src/lib/schema-viewer.tsx
  nx-dev/feature-package-schema-viewer/src/lib/ui/info-panel.tsx
Labels: type: docs

#11379 docs(nxdev): update algolia types
  nx-dev/feature-search/src/lib/algolia-search.tsx
Labels: type: docs

#11385 docs(nxdev): update package schema viewer export type
  nx-dev/feature-package-schema-viewer/src/lib/package-schema-list.tsx
Labels: type: docs

#11386 docs(nxdev): add 404 component type
  nx-dev/nx-dev/pages/404.tsx
Labels: type: docs
