Repository nrwl/nx, pull requests merged in 2022-12, with the labels that each got.

#13502 fix(core): prevent peer deps from ending up as dev deps in create package json
  e2e/next/src/next.test.ts
  e2e/node/src/node.test.ts
  packages/next/src/executors/build/lib/create-package-json.ts
  packages/nx/src/utils/create-package-json.ts
Labels: scope: core

#13547 docs(nxdev): update nx cloud logo
  nx-dev/ui-home/src/lib/extensible-and-integrated/github-intergration-tab.tsx
Labels: type: docs

#13589 docs(nxdev): remove redirect rules for landing pages
  nx-dev/nx-dev/next.config.js
Labels: type: docs

#13602 fix(testing): handle cypress-project generation for standalone projects
  docs/generated/packages/cypress.json
  packages/cypress/src/generators/cypress-project/cypress-project.spec.ts
  packages/cypress/src/generators/cypress-project/cypress-project.ts
  packages/cypress/src/generators/cypress-project/schema.json
Labels: scope: testing tools

#13568 feat(core): improve performance of object sort function
  packages/nx/src/utils/object-sort.ts
Labels: scope: core

#13692 fix(core): handle git repo package versions in lock file parsing
  packages/nx/src/lock-file/__fixtures__/aux.lock.ts
  packages/nx/src/lock-file/lock-file.spec.ts
  packages/nx/src/lock-file/npm.ts
  packages/nx/src/lock-file/pnpm.ts
  packages/nx/src/lock-file/utils/lock-file-type.ts
  packages/nx/src/lock-file/yarn.ts
Labels: scope: core

#13317 feat(core): prune lock file based on projects dependencies and package.json
  docs/generated/devkit/index.md
  docs/generated/packages/devkit.json
  packages/devkit/index.ts
  packages/nx/src/lock-file/lock-file.ts
  packages/nx/src/lock-file/npm.spec.ts
  packages/nx/src/lock-file/npm.ts
  packages/nx/src/lock-file/pnpm.spec.ts
  packages/nx/src/lock-file/pnpm.ts
  packages/nx/src/lock-file/utils/hashing.ts
  packages/nx/src/lock-file/utils/mapping.ts
  packages/nx/src/lock-file/utils/pruning.ts
  packages/nx/src/lock-file/utils/sorting.ts
  packages/nx/src/lock-file/yarn.spec.ts
  packages/nx/src/lock-file/yarn.ts
  packages/nx/src/utils/package-json.ts
Labels: scope: core

#13585 fix(core): support alias packages in affected locators detection
  packages/nx/src/lock-file/__fixtures__/aux.lock.ts
  packages/nx/src/lock-file/lock-file.spec.ts
  packages/nx/src/lock-file/npm.ts
  packages/nx/src/lock-file/pnpm.ts
  packages/nx/src/lock-file/yarn.ts
Labels: scope: core

#13734 feat(core): add lockfile pruning to executors that generate package.json
  docs/generated/packages/node.json
  docs/generated/packages/webpack.json
  e2e/next/src/next.test.ts
  e2e/node/src/node.test.ts
  e2e/utils/index.ts
  packages/next/src/executors/build/lib/create-package-json.ts
  packages/node/src/executors/webpack/schema.json
  packages/nx/src/lock-file/lock-file.ts
  packages/nx/src/lock-file/utils/pruning.ts
  packages/webpack/src/executors/webpack/schema.json
  packages/webpack/src/utils/generate-package-json-webpack-plugin.ts
Labels: scope: core

#13773 docs(nxdev): change vit plugin card by official nx plugin
  nx-dev/ui-home/src/lib/extensible-and-integrated/plugins-tab.tsx
Labels: type: docs

#13728 fix(core): handle local workspace projects in package.json for affected locator
  packages/nx/src/project-graph/affected/locators/npm-packages.spec.ts
  packages/nx/src/project-graph/affected/locators/npm-packages.ts
Labels: scope: core

#13821 docs(core): create a glossary
  docs/map.json
  docs/shared/reference/glossary.md
Labels: type: docs

#13829 docs(nxdev): cleanup documentation code generator
  scripts/documentation/documentation.ts
  scripts/documentation/schema-flattener.ts
  scripts/documentation/utils.ts
Labels: type: docs

#13799 feat(core): add missing lock file generation to executors
  packages/js/src/utils/package-json/update-package-json.spec.ts
  packages/js/src/utils/package-json/update-package-json.ts
  packages/next/src/executors/build/build.impl.ts
  packages/next/src/executors/build/lib/create-package-json.ts
  packages/next/src/executors/build/lib/update-package-json.ts
  packages/nx/src/utils/create-package-json.ts
  packages/rollup/src/executors/rollup/lib/update-package-json.ts
Labels: scope: core

#13830 fix(core): fix lock file pruning optional dependencies
  packages/nx/src/lock-file/__fixtures__/npm.lock.ts
  packages/nx/src/lock-file/__fixtures__/pnpm.lock.ts
  packages/nx/src/lock-file/__fixtures__/yarn.lock.ts
  packages/nx/src/lock-file/npm.spec.ts
  packages/nx/src/lock-file/npm.ts
  packages/nx/src/lock-file/pnpm.spec.ts
  packages/nx/src/lock-file/pnpm.ts
  packages/nx/src/lock-file/utils/lock-file-type.ts
  packages/nx/src/lock-file/yarn.spec.ts
  packages/nx/src/lock-file/yarn.ts
Labels: scope: core

#13847 fix(core): ensure yarn patch and path versions are correct when pruning
  packages/nx/src/lock-file/__fixtures__/yarn.lock.ts
  packages/nx/src/lock-file/__snapshots__/lock-file.spec.ts.snap
  packages/nx/src/lock-file/__snapshots__/yarn.spec.ts.snap
  packages/nx/src/lock-file/yarn.spec.ts
  packages/nx/src/lock-file/yarn.ts
Labels: scope: core

#13817 feat(linter): add support for combo source tags
  docs/shared/recipes/tag-multiple-dimensions.md
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin-nx/src/utils/runtime-lint-utils.ts
Labels: scope: linter

#13851 fix(nextjs): ensure no dev deps in prod package.json
  packages/next/src/executors/build/build.impl.ts
Labels: scope: core

#13875 fix(core): fix pruning of pnpm lockfiles with github packages
  packages/nx/src/lock-file/lock-file.spec.ts
  packages/nx/src/lock-file/pnpm.ts
Labels: scope: core

#13872 fix(core): skip npm nested lockfile key mismatch
  packages/nx/src/lock-file/npm.ts
Labels: scope: core

#13900 docs(angular): add example repo for dynamic federation #12958
  docs/shared/guides/module-federation/dynamic-mfe-angular.md
Labels: type: docs

#13906 docs(nxdev): add nx cloud section on flyout menu
  nx-dev/ui-common/src/lib/header.tsx
Labels: type: docs

#13913 docs(nxdev): extract meta tags from document to app
  nx-dev/nx-dev/pages/_app.tsx
  nx-dev/nx-dev/pages/_document.tsx
Labels: type: docs

#13920 docs(nxdev): add sub-forlder context into devkit urls
  docs/generated/devkit/index.md
  docs/generated/devkit/ngcli_adapter.md
  docs/generated/packages/devkit/documents/index.md
  docs/generated/packages/devkit/documents/ngcli_adapter.md
  typedoc-theme/src/lib/theme.ts
Labels: type: docs

#13935 docs(core): move package documents into its own folder
  docs/generated/manifests/packages.json
  docs/generated/packages/vite/documents/overview.md
  docs/map.json
  docs/packages-metadata.json
  docs/shared/packages/angular/angular-nx-version-matrix.md
  docs/shared/packages/angular/angular-plugin.md
  docs/shared/packages/cypress/cypress-component-testing.md
  docs/shared/packages/cypress/cypress-plugin.md
  docs/shared/packages/cypress/cypress-v11-migration.md
  docs/shared/packages/detox/detox-plugin.md
  docs/shared/packages/esbuild/esbuild-plugin.md
  docs/shared/packages/express/express-plugin.md
  docs/shared/packages/jest/jest-plugin.md
  docs/shared/packages/js/js-plugin.md
  docs/shared/packages/linter/eslint-plugin-nx.md
  docs/shared/packages/linter/linter-plugin.md
  docs/shared/packages/nest/nest-plugin.md
  docs/shared/packages/next/next-plugin.md
  docs/shared/packages/node/node-plugin.md
  docs/shared/packages/nx-plugin/nx-plugin.md
  docs/shared/packages/react-native/react-native-plugin.md
  docs/shared/packages/react/react-plugin.md
  docs/shared/packages/storybook/angular-browser-target.md
  docs/shared/packages/storybook/angular-configuring-styles.md
  docs/shared/packages/storybook/angular-storybook-compodoc.md
  docs/shared/packages/storybook/angular-storybook-targets.md
  docs/shared/packages/storybook/best-practices.md
  docs/shared/packages/storybook/button-docs.png
  docs/shared/packages/storybook/button-size-input.png
  docs/shared/packages/storybook/migrate-webpack-final-angular.md
  docs/shared/packages/storybook/migrate-webpack-final-react.md
  docs/shared/packages/storybook/plugin-angular.md
  docs/shared/packages/storybook/plugin-overview.md
  docs/shared/packages/storybook/plugin-react.md
  docs/shared/packages/storybook/storybook-composition-setup.md
  docs/shared/packages/storybook/storybook-v6-angular.md
  docs/shared/packages/storybook/storybook-v6-react.md
  docs/shared/packages/vite/vite-plugin.md
  docs/shared/packages/web/web-plugin.md
  docs/shared/packages/workspace/nx-compatibility-matrix.md
  docs/shared/packages/workspace/workspace-plugin.md
Labels: type: docs

#13937 docs(core): add new Github integration setup guide
  docs/generated/manifests/cloud.json
  docs/generated/manifests/menus.json
  docs/map.json
  docs/nx-cloud/private/auth-github.md
  docs/nx-cloud/private/get-started.md
  docs/nx-cloud/private/github.md
  docs/nx-cloud/private/standalone.md
  docs/nx-cloud/set-up/access-vcs-setup.png
  docs/nx-cloud/set-up/add-github-repository.png
  docs/nx-cloud/set-up/github.md
  docs/nx-cloud/set-up/minimal-github-access-token.png
  docs/nx-cloud/set-up/use-github-app-auth.png
  docs/nx-cloud/set-up/use-github-pat-auth.png
  nx-dev/nx-dev-e2e/src/e2e/nx-cloud-documentation.cy.ts
Labels: type: docs

#13891 feat(linter): add allowedExternalImports option to boundaries rule
  docs/shared/recipes/ban-external-imports.md
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin-nx/src/utils/runtime-lint-utils.ts
Labels: scope: linter

#13949 fix(core): consult root package.json when resolving peer deps on package generation
  packages/nx/src/utils/create-package-json.ts
Labels: scope: core

#13953 docs(nxdev): add scroll into view for sidebar sub items
  nx-dev/ui-common/src/lib/sidebar.tsx
  nx-dev/ui-common/tsconfig.lib.json
Labels: type: docs

#13940 fix(testing): warn and default if sourceRoot isn't set for ng CT
  packages/angular/plugins/component-testing.ts
Labels: scope: testing tools

#13982 docs(nxdev): improve related documentation link matcher
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/generated/manifests/tags.json
  docs/map.json
  nx-dev/models-document/src/lib/related-documents.utils.ts
Labels: type: docs

#13987 docs(nxdev): take into account custom description
  nx-dev/models-package/src/lib/package.models.ts
  scripts/documentation/package-schemas/generatePackageSchemas.ts
Labels: type: docs

#13988 docs(core): move generated packages metadata file into generated folder
  docs/generated/packages-metadata.json
  scripts/documentation/generators/generate-manifests.ts
  scripts/documentation/package-schemas/generatePackageSchemas.ts
Labels: type: docs

#13942 fix(testing): change ignoreTestFiles to excludeSpecPattern for cy10+
  docs/generated/packages/cypress/executors/cypress.json
  packages/cypress/src/executors/cypress/cypress.impl.ts
  packages/cypress/src/executors/cypress/schema.json
Labels: scope: testing tools

#14037 feat(testing): support async webpack config for react component testing
  e2e/react/src/cypress-component-tests.test.ts
  packages/react/plugins/component-testing/index.ts
  packages/react/src/generators/cypress-component-configuration/__snapshots__/cypress-component-configuration.spec.ts.snap
  packages/react/src/generators/cypress-component-configuration/files/cypress.config.ts__tpl__
Labels: scope: testing tools

#14043 docs(testing): add info about global scripts & @swc/jest
  docs/generated/packages/jest/documents/overview.md
  docs/shared/packages/jest/jest-plugin.md
Labels: scope: testing tools

#14045 docs(testing): redirect cy 10 generator to cy 11
  docs/generated/packages/cypress/documents/v11-migration-guide.md
  docs/shared/packages/cypress/cypress-v11-migration.md
  nx-dev/nx-dev/redirect-rules.config.js
Labels: type: docs, scope: testing tools

#13969 docs(core): add new Gitlab integration setup guide
  docs/generated/manifests/cloud.json
  docs/generated/manifests/menus.json
  docs/map.json
  docs/nx-cloud/set-up/add-gitlab-repository.png
  docs/nx-cloud/set-up/gitlab.md
  docs/nx-cloud/set-up/minimal-gitlab-access-token.png
  docs/nx-cloud/set-up/override-gitlab-api-url.png
  docs/nx-cloud/set-up/use-gitlab-pat-auth.png
Labels: type: docs
