Repository nrwl/nx, pull requests merged in 2022-02, with the labels that each got.

#8814 fix(linter): add swc/core-linux-musl as an optional dependency for alpine
  package.json
  packages/eslint-plugin-nx/package.json
  yarn.lock
Labels: scope: linter

#8827 docs(core): add applications and libraries section
  docs/map.json
  docs/shared/workspace/applications-and-libraries.md
Labels: type: docs

#8831 fix(linter): add missing swc/core-linux-* as optional dependencies
  package.json
  packages/eslint-plugin-nx/package.json
  yarn.lock
Labels: scope: linter

#8839 chore(repo): remove leftover nx-dev tests
  nx-dev/data-access-documents/src/lib/documents.api.spec.ts
  nx-dev/data-access-documents/src/lib/menu.api.spec.ts
  nx-dev/data-access-documents/src/lib/test-utils.ts
Labels: scope: repo

#8842 chore(repo): turn on full linter checks on CI
  .circleci/config.yml
Labels: scope: repo

#8843 fix(core): change ng to nx
  packages/workspace/src/generators/workspace/files/README.md__tmpl__
Labels: scope: core

#8878 chore(repo): remove nightly e2e test trigger on new nx version
  .github/workflows/e2e-matrix.yml
  .github/workflows/e2e-windows.yml
Labels: scope: repo

#8813 feat(core): use stricter types for project graph node references
  dep-graph/client/src/app/machines/dep-graph.spec.ts
  dep-graph/client/src/app/machines/graph.ts
  dep-graph/client/src/app/machines/interfaces.ts
  dep-graph/client/src/app/machines/selectors.ts
  dep-graph/client/src/app/mock-project-graph-service.ts
  dep-graph/client/src/app/util-cytoscape/project-node.ts
  docs/generated/api-nx-devkit/index.md
  packages/devkit/index.ts
  packages/devkit/src/project-graph/project-graph-builder.ts
  packages/tao/src/shared/project-graph.ts
  packages/web/src/executors/rollup/rollup.impl.ts
  packages/workspace/src/command-line/affected.ts
  packages/workspace/src/command-line/dep-graph.ts
  packages/workspace/src/command-line/print-affected.ts
  packages/workspace/src/command-line/run-many.ts
  packages/workspace/src/core/affected-project-graph/locators/tsconfig-json-changes.ts
  packages/workspace/src/core/file-utils.ts
  packages/workspace/src/core/nx-deps/nx-deps-cache.spec.ts
  packages/workspace/src/core/nx-deps/nx-deps-cache.ts
  packages/workspace/src/core/project-graph/build-dependencies/explicit-package-json-dependencies.spec.ts
  packages/workspace/src/core/project-graph/build-dependencies/explicit-package-json-dependencies.ts
  packages/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.spec.ts
  packages/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.ts
  packages/workspace/src/core/project-graph/build-project-graph.ts
  packages/workspace/src/core/project-graph/operators.ts
  packages/workspace/src/core/project-graph/project-graph-models.ts
  packages/workspace/src/core/project-graph/project-graph.ts
  packages/workspace/src/core/target-project-locator.ts
  packages/workspace/src/tasks-runner/run-command.ts
  packages/workspace/src/tasks-runner/utils.ts
  packages/workspace/src/utilities/buildable-libs-utils.ts
  packages/workspace/src/utilities/project-graph-utils.ts
  packages/workspace/src/utils/graph-utils.ts
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: scope: core

#8976 fix(linter): enforce fresh graph if rule not run by nx command
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
  packages/workspace/src/utils/runtime-lint-utils.ts
Labels: scope: linter

#8997 chore(repo): cleanup circleci config
  .circleci/config.yml
Labels: scope: repo

#9049 chore(repo): update nx and nx-cloud to latest version
  package.json
  yarn.lock
Labels: scope: repo

#9061 chore(repo): remove obsolete NX_E2E_SKIP_DAEMON_CLEANUP flag
  .github/workflows/e2e-matrix.yml
  .github/workflows/e2e-windows.yml
  e2e/utils/index.ts
Labels: scope: repo

#9066 chore(repo): fix failing windows nightly
  .github/workflows/e2e-windows.yml
Labels: scope: repo

#9078 chore(repo): use npx on e2e ng calls to fix windows failures
  e2e/jest/src/jest.test.ts
  e2e/utils/index.ts
Labels: scope: repo

#9121 chore(react): fix version on eslint-plugin-react
  package.json
  packages/next/src/utils/versions.ts
  packages/react/package.json
  packages/react/src/utils/versions.ts
  yarn.lock
Labels: scope: react

#9110 fix(linter): make sure hasher has all the tags
  packages/linter/src/executors/eslint/hasher.ts
Labels: scope: linter
