Repository nrwl/nx, pull requests merged in 2023-01, with the labels that each got.

#14008 fix(testing): correctly set task status for failed coverage reports
  e2e/vite/src/vite.test.ts
  packages/vite/migrations.json
  packages/vite/src/executors/test/vitest.impl.ts
  packages/vite/src/generators/vitest/vitest-generator.ts
  packages/vite/src/generators/vitest/vitest.spec.ts
  packages/vite/src/migrations/update-15-4-3/update-report-directory.spec.ts
  packages/vite/src/migrations/update-15-4-3/update-report-directory.ts
  packages/vite/src/utils/generator-utils.ts
Labels: scope: testing tools

#14068 feat(expo): move svg to inline for starter app
  packages/create-nx-workspace/bin/create-nx-workspace.ts
  packages/expo/package.json
  packages/expo/plugins/with-nx-webpack.ts
  packages/expo/src/generators/application/files/assets/logo.png
  packages/expo/src/generators/application/files/assets/star.svg
  packages/expo/src/generators/application/files/src/app/App.tsx.template
  packages/expo/src/generators/application/files/src/app/icons/blog.svg
  packages/expo/src/generators/application/files/src/app/icons/book.svg
  packages/expo/src/generators/application/files/src/app/icons/checkmark.svg
  packages/expo/src/generators/application/files/src/app/icons/chevron-right.svg
  packages/expo/src/generators/application/files/src/app/icons/courses.svg
  packages/expo/src/generators/application/files/src/app/icons/github.svg
  packages/expo/src/generators/application/files/src/app/icons/heart.svg
  packages/expo/src/generators/application/files/src/app/icons/logo.png
  packages/expo/src/generators/application/files/src/app/icons/nx-cloud.svg
  packages/expo/src/generators/application/files/src/app/icons/pointer.svg
  packages/expo/src/generators/application/files/src/app/icons/terminal.svg
  packages/expo/src/generators/application/files/src/app/icons/vscode.svg
  packages/expo/src/generators/application/files/src/app/icons/youtube.svg
  packages/expo/src/generators/init/init.ts
  packages/expo/src/utils/add-jest.ts
  packages/expo/src/utils/versions.ts
  packages/react-native/src/generators/application/files/app/src/app/App.tsx.template
  packages/react-native/src/generators/application/files/app/src/app/icons/blog.svg
  packages/react-native/src/generators/application/files/app/src/app/icons/book.svg
  packages/react-native/src/generators/application/files/app/src/app/icons/checkmark.svg
  packages/react-native/src/generators/application/files/app/src/app/icons/chevron-right.svg
  packages/react-native/src/generators/application/files/app/src/app/icons/courses.svg
  packages/react-native/src/generators/application/files/app/src/app/icons/github.svg
  packages/react-native/src/generators/application/files/app/src/app/icons/heart.svg
  packages/react-native/src/generators/application/files/app/src/app/icons/logo.png
  packages/react-native/src/generators/application/files/app/src/app/icons/nx-cloud.svg
  packages/react-native/src/generators/application/files/app/src/app/icons/pointer.svg
  packages/react-native/src/generators/application/files/app/src/app/icons/terminal.svg
  packages/react-native/src/generators/application/files/app/src/app/icons/vscode.svg
  packages/react-native/src/generators/application/files/app/src/app/icons/youtube.svg
  packages/react-native/src/utils/add-jest.ts
Labels: type: feature, scope: react-native

#14117 docs(nxdev): remove survey banners
  nx-dev/nx-dev/pages/index.tsx
  nx-dev/ui-common/src/lib/documentation-header.tsx
Labels: type: docs

#14118 docs(nxdev): parameter view takes full available width
  nx-dev/feature-package-schema-viewer/src/lib/parameter-view.tsx
Labels: type: docs

#14116 fix(testing): vitest deleting project root with coverage enabled
  e2e/vite/src/vite.test.ts
  packages/vite/src/executors/test/vitest.impl.ts
Labels: scope: testing tools, scope: bundlers

#14119 docs(nxdev): add bottom margin and reduce padding on ui tabs
  nx-dev/ui-markdoc/src/lib/tags/tabs.component.tsx
Labels: type: docs

#14137 docs(testing): add deprecation messages for Jest/Cypress
  docs/generated/packages/cypress/executors/cypress.json
  docs/generated/packages/jest/executors/jest.json
  docs/generated/packages/jest/generators/jest-project.json
  packages/cypress/src/executors/cypress/cypress.impl.ts
  packages/cypress/src/executors/cypress/schema.json
  packages/jest/src/executors/jest/schema.d.ts
  packages/jest/src/executors/jest/schema.json
  packages/jest/src/generators/jest-project/schema.d.ts
  packages/jest/src/generators/jest-project/schema.json
Labels: type: docs, scope: testing tools

#14148 fix(testing): only check provided project is root for cypress-project…
  packages/cypress/src/generators/cypress-project/cypress-project.spec.ts
  packages/cypress/src/generators/cypress-project/cypress-project.ts
Labels: scope: testing tools

#14165 docs(nxdev): add status page link
  nx-dev/ui-common/src/lib/footer.tsx
Labels: type: docs

#14171 docs(nxdev): add button component
  nx-dev/ui-common/src/index.ts
  nx-dev/ui-common/src/lib/button.tsx
  nx-dev/ui-home/src/lib/extensible-and-integrated.tsx
  nx-dev/ui-home/src/lib/getting-started.tsx
  nx-dev/ui-home/src/lib/hero.tsx
  nx-dev/ui-home/src/lib/migrate.tsx
  nx-dev/ui-home/src/lib/migrations-and-code-generation.tsx
  nx-dev/ui-home/src/lib/monorepo-styles.tsx
Labels: type: docs

#14175 docs(nxdev): add typography component
  nx-dev/nx-dev/pages/community.tsx
  nx-dev/ui-common/src/index.ts
  nx-dev/ui-common/src/lib/typography.tsx
  nx-dev/ui-community/src/lib/connect-with-us.tsx
  nx-dev/ui-community/src/lib/create-nx-plugin.tsx
  nx-dev/ui-community/src/lib/plugin-directory.tsx
  nx-dev/ui-home/src/lib/extensible-and-integrated.tsx
  nx-dev/ui-home/src/lib/migrations-and-code-generation.tsx
  nx-dev/ui-home/src/lib/monorepo-styles.tsx
  nx-dev/ui-home/src/lib/newsletter.tsx
  nx-dev/ui-home/src/lib/nx-is-fast.tsx
  nx-dev/ui-home/src/lib/nx-statistics.tsx
  nx-dev/ui-home/src/lib/testimonials.tsx
Labels: type: docs

#14188 fix(web): dynamic default unitTestRunner based on bundler for @nrwl/web:app
  docs/generated/packages/web/generators/application.json
  packages/web/src/generators/application/application.spec.ts
  packages/web/src/generators/application/application.ts
  packages/web/src/generators/application/schema.json
Labels: scope: testing tools, scope: bundlers

#14229 docs(nxdev): remove current items from related documents
  nx-dev/nx-dev/pages/[...segments].tsx
  nx-dev/nx-dev/pages/nx-cloud/[...segments].tsx
  nx-dev/nx-dev/pages/packages/[name]/documents/[...segments].tsx
  nx-dev/nx-dev/pages/recipes/[...segments].tsx
Labels: type: docs

#14245 docs(misc): updating to tutorial version of react standalone video
  docs/shared/react-standalone-tutorial/1-code-generation.md
Labels: type: docs

#14058 feat(testing): Cypress 12 Support
  packages/cypress/migrations.json
  packages/cypress/package.json
  packages/cypress/src/generators/migrate-to-cypress-11/migrate-to-cypress-11.ts
  packages/cypress/src/migrations/update-15-5-0/__snapshots__/update-to-cypress-12.spec.ts.snap
  packages/cypress/src/migrations/update-15-5-0/helpers.ts
  packages/cypress/src/migrations/update-15-5-0/update-to-cypress-12.spec.ts
  packages/cypress/src/migrations/update-15-5-0/update-to-cypress-12.ts
  packages/cypress/src/utils/versions.ts
Labels: scope: testing tools

#14346 docs(nxdev): add tutorial redirect rules
  nx-dev/nx-dev/next.config.js
  nx-dev/nx-dev/redirect-rules.config.js
  nx-dev/nx-dev/redirect-rules.config.spec.js
Labels: type: docs

#14358 docs(nxdev): fix react monorepo tutorial link
  docs/shared/npm-tutorial/integrated.md
Labels: type: docs

#14315 feat(nx-cloud): display current token for connect-to-nx-cloud
  packages/nx/src/command-line/connect.ts
  packages/nx/src/utils/nx-cloud-utils.ts
Labels: scope: nx-cloud

#14365 docs(nxdev): add brands & guidelines link
  nx-dev/ui-common/src/lib/footer.tsx
  yarn.lock
Labels: type: docs

#14394 fix(core): fix broken lines and columns import
  packages/nx/src/utils/json.ts
Labels: type: bug, scope: core

#14371 docs(core): add link for standalone-angular-app example repo
  docs/shared/angular-standalone-tutorial/1-code-generation.md
Labels: type: docs

#14405 docs(nxdev): support x-priority schema options
  nx-dev/feature-package-schema-viewer/src/lib/parameter-view.tsx
  nx-dev/feature-package-schema-viewer/src/lib/schema-viewer.tsx
  nx-dev/models-package/src/lib/package.models.ts
Labels: type: docs

#13968 feat(js): add lockfile generator to js plugin
  docs/generated/packages/js/executors/swc.json
  docs/generated/packages/js/executors/tsc.json
  e2e/js/src/js-swc.test.ts
  e2e/js/src/js-tsc.test.ts
  packages/js/src/executors/swc/schema.json
  packages/js/src/executors/tsc/schema.json
  packages/js/src/utils/package-json/update-package-json.spec.ts
  packages/js/src/utils/package-json/update-package-json.ts
  packages/js/src/utils/schema.d.ts
Labels: scope: js

#14362 fix(testing): do not set vitest root when not in workspaceRoot
  e2e/utils/index.ts
  e2e/vite/src/vite.test.ts
  packages/vite/src/executors/test/vitest.impl.ts
Labels: scope: testing tools

#14253 docs(testing): add x-priority to cypress package
  docs/generated/packages/cypress/executors/cypress.json
  docs/generated/packages/cypress/generators/cypress-project.json
  docs/generated/packages/cypress/generators/init.json
  packages/cypress/src/executors/cypress/schema.json
  packages/cypress/src/generators/convert-tslint-to-eslint/schema.json
  packages/cypress/src/generators/cypress-project/schema.json
  packages/cypress/src/generators/init/schema.json
Labels: scope: testing tools

#14252 docs(testing): add x-priority to jest package
  docs/generated/packages/jest/generators/init.json
  docs/generated/packages/jest/generators/jest-project.json
  packages/jest/src/generators/init/schema.json
  packages/jest/src/generators/jest-project/schema.json
Labels: scope: testing tools

#14630 fix(devkit): only install deps with higher version
  packages/devkit/src/utils/package-json.spec.ts
  packages/devkit/src/utils/package-json.ts
Labels: scope: devkit

#13744 fix(testing): jest batch mode improvements
  nx-dev/nx-dev/jest.config.ts
  packages/jest/src/executors/jest/jest.impl.ts
  packages/nx/src/config/task-graph.ts
  packages/nx/src/tasks-runner/batch/batch-messages.ts
  packages/nx/src/tasks-runner/batch/run-batch.ts
  packages/nx/src/tasks-runner/life-cycles/store-run-information-life-cycle.spec.ts
  packages/nx/src/tasks-runner/life-cycles/store-run-information-life-cycle.ts
  packages/nx/src/tasks-runner/life-cycles/task-profiling-life-cycle.ts
  packages/nx/src/tasks-runner/life-cycles/task-timings-life-cycle.ts
  packages/nx/src/tasks-runner/run-command.ts
  packages/nx/src/tasks-runner/task-orchestrator.ts
Labels: scope: testing tools
