Repository nrwl/nx, pull requests merged in 2023-06, with the labels that each got.

#17388 docs(core): expand json examples
  docs/shared/reference/project-configuration.md
Labels: type: docs

#17321 docs(core): deprecate npmScope
  docs/shared/reference/nx-json.md
Labels: type: docs

#17396 fix(testing): resolve full paths to vite configs for vitest
  packages/vite/src/executors/test/vitest.impl.ts
Labels: scope: testing tools

#17116 docs(nextjs): Add examples for executors
  docs/generated/packages/next/executors/build.json
  docs/generated/packages/next/executors/server.json
  packages/next/docs/build-next-executor-examples.md
  packages/next/docs/server-next-executor-examples.md
  packages/next/src/executors/build/schema.json
  packages/next/src/executors/server/schema.json
Labels: scope: nextjs, scope: docs

#17507 docs(nx-dev): update nx-cloud swagger link
  docs/nx-cloud/reference/server-api.md
  nx-dev/nx-dev/pages/changelog.tsx
Labels: type: docs

#17510 fix(nextjs): Update @nx/next to be a devDependency
  packages/next/migrations.json
  packages/next/src/generators/init/init.spec.ts
  packages/next/src/generators/init/init.ts
  packages/next/src/migrations/update-16-4-0/update-nx-next-dependency.spec.ts
  packages/next/src/migrations/update-16-4-0/update-nx-next-dependency.ts
Labels: scope: nextjs

#17500 fix(core): handle string and array parserOptions.project values
  packages/workspace/src/generators/move/lib/update-eslintrc-json.spec.ts
  packages/workspace/src/generators/move/lib/update-eslintrc-json.ts
Labels: scope: core

#17110 docs(node): add recipes for various databases w/ node
  docs/generated/manifests/menus.json
  docs/generated/manifests/recipes.json
  docs/generated/manifests/tags.json
  docs/map.json
  docs/shared/recipes/database/mongo-fastify.md
  docs/shared/recipes/database/nestjs-prisma.md
  docs/shared/recipes/database/postgres-fastify.md
  docs/shared/recipes/database/redis-fastify.md
  docs/shared/recipes/database/serverless-fastify-planetscale.md
Labels: type: docs

#17678 docs(core): add new champions
  nx-dev/nx-dev/lib/champions.ts
  nx-dev/nx-dev/public/images/champions/daniel-glejzner.webp
  nx-dev/nx-dev/public/images/champions/dmitriy-stepanenko.webp
  nx-dev/nx-dev/public/images/champions/edouard-bozon.webp
  nx-dev/nx-dev/public/images/champions/michael-hladky.webp
  nx-dev/nx-dev/public/images/champions/nacho-vazquez.webp
  nx-dev/nx-dev/public/images/champions/nathan-walker.webp
  nx-dev/nx-dev/public/images/champions/stefan-haas.webp
Labels: type: docs

#17613 fix(core): ensure correct package name matching when parsing pnpm lock file
  packages/nx/src/plugins/js/lock-file/pnpm-parser.ts
Labels: type: bug, scope: core

#17165 fix(testing): deprecate cypress tsconfig option
  docs/generated/packages/cypress/executors/cypress.json
  packages/cypress/migrations.json
  packages/cypress/src/executors/cypress/cypress.impl.ts
  packages/cypress/src/executors/cypress/schema.json
  packages/cypress/src/migrations/update-16-4-0/tsconfig-sourcemaps.spec.ts
  packages/cypress/src/migrations/update-16-4-0/tsconfig-sourcemaps.ts
Labels: scope: testing tools

#17738 fix(nextjs): Custom server generator root undefined
  packages/next/src/generators/custom-server/custom-server.ts
Labels: scope: nextjs

#17581 feat(linter): add rule for dependency checking
  .eslintrc.json
  e2e/linter/src/linter.test.ts
  nx.json
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/index.ts
  packages/eslint-plugin/src/rules/dependency-checks.spec.ts
  packages/eslint-plugin/src/rules/dependency-checks.ts
  packages/eslint-plugin/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin/src/utils/package-json-utils.ts
  packages/js/src/internal.ts
  packages/js/src/utils/compiler-helper-dependency.ts
  packages/linter/src/generators/init/global-eslint-config.ts
  packages/nx/src/plugins/js/package-json/create-package-json.ts
  packages/plugin/src/generators/lint-checks/generator.ts
Labels: type: feature, scope: linter

#17741 feat(nest): add v10 migrations for tsconfig & CacheModule
  packages/nest/migrations.json
  packages/nest/package.json
  packages/nest/src/migrations/update-16-4-0-cache-manager/nestjs-10-updates.ts
  packages/nest/src/migrations/update-16-4-0-cache-manager/nestjs-10.spec.ts
Labels: scope: node

#17743 feat(nx-dev): site map
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/map.json
  docs/shared/reference/sitemap.md
  nx-dev/ui-common/src/lib/footer.tsx
  scripts/documentation/generators/generate-manifests.ts
  scripts/documentation/utils.ts
Labels: type: docs

#17733 fix(nextjs): Respect --nextAppDir when passed during CNW
  e2e/workspace-create/src/create-nx-workspace.test.ts
  packages/workspace/src/generators/new/generate-preset.ts
  packages/workspace/src/generators/preset/preset.ts
Labels: scope: nextjs

#17707 fix(webpack): sync webpack version to nx/webpack
  packages/webpack/migrations.json
Labels: scope: bundlers

#17792 fix(nextjs): For serve executor keepAliveTimeout should be camelCased
  packages/next/src/executors/server/server.impl.ts
Labels: scope: nextjs

#17796 docs(nextjs): Update nextjs docs since --root was removed
  docs/generated/packages/next/executors/build.json
  packages/next/docs/build-next-executor-examples.md
Labels: scope: nextjs

#17799 docs(core): workspace-lint deprecation
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/map.json
  docs/shared/deprecated/workspace-lint.md
  docs/shared/reference/commands.md
  docs/shared/reference/sitemap.md
Labels: type: docs

#17790 feat(testing): add --force-exit to jest executor
  docs/generated/packages/jest/executors/jest.json
  packages/jest/src/executors/jest/jest.impl.ts
  packages/jest/src/executors/jest/schema.d.ts
  packages/jest/src/executors/jest/schema.json
Labels: scope: testing tools

#17806 fix(nextjs): Custom server should run on fresh apps without errors
  packages/js/src/executors/node/node.impl.ts
Labels: scope: nextjs

#17788 feat(testing): bump cypress to latest for angular CT
  e2e/angular-extensions/src/cypress-component-tests.test.ts
  e2e/cypress/src/cypress.test.ts
  packages/cypress/migrations.json
  packages/cypress/src/migrations/update-16-4-0/warn-incompatible-angular-cypress.spec.ts
  packages/cypress/src/migrations/update-16-4-0/warn-incompatible-angular-cypress.ts
  packages/cypress/src/utils/versions.ts
Labels: scope: testing tools

#17836 chore(repo): bump webpack version
  package.json
  packages/angular/src/builders/webpack-browser/webpack-browser.impl.ts
  packages/angular/src/builders/webpack-dev-server/webpack-dev-server.impl.ts
  packages/react/plugins/storybook/index.ts
  packages/react/plugins/with-react.ts
  pnpm-lock.yaml
Labels: scope: react, scope: angular, scope: storybook, scope: repo

#17866 fix(nextjs): Running nx build --configuration=development should not throw an error
  e2e/next/src/next.test.ts
  packages/next/src/executors/build/build.impl.ts
  packages/next/src/executors/build/lib/create-next-config-file.ts
Labels: scope: nextjs

#17530 feat(linter): allow globs in onlyDependOnLibsWithTags eslint-plugin configuration option
  docs/shared/core-features/enforce-project-boundaries.md
  packages/eslint-plugin/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin/src/utils/runtime-lint-utils.spec.ts
  packages/eslint-plugin/src/utils/runtime-lint-utils.ts
Labels: type: feature, scope: linter

#17883 fix(linter): create-package-json should omit non-npm and ignored packages
  packages/eslint-plugin/src/rules/dependency-checks.ts
  packages/nx/src/plugins/js/package-json/create-package-json.ts
Labels: type: bug, scope: core, scope: linter
