Repository nrwl/nx, pull requests merged in 2023-12, with the labels that each got.

#20557 fix(linter): support adding plugin at a later stage
  packages/eslint/src/generators/init/init.spec.ts
  packages/eslint/src/generators/init/init.ts
  packages/eslint/src/generators/lint-project/lint-project.ts
  packages/eslint/src/generators/utils/plugin.ts
Labels: scope: linter

#20193 feat(nextjs): Add support for create nodes for nextjs
  e2e/next-core/src/next-pcv3.test.ts
  e2e/next-core/src/next-webpack.test.ts
  e2e/next-extensions/src/next-experimental.test.ts
  packages/cypress/plugins/cypress-preset.ts
  packages/next/package.json
  packages/next/plugin.ts
  packages/next/plugins/with-nx.ts
  packages/next/src/executors/export/export.impl.ts
  packages/next/src/executors/server/server.impl.ts
  packages/next/src/generators/application/application.spec.ts
  packages/next/src/generators/application/application.ts
  packages/next/src/generators/application/lib/add-e2e.ts
  packages/next/src/generators/application/lib/add-plugin.ts
  packages/next/src/generators/application/lib/add-project.ts
  packages/next/src/generators/init/init.ts
  packages/next/src/generators/init/lib/add-plugin.ts
  packages/next/src/plugins/__snapshots__/plugin.spec.ts.snap
  packages/next/src/plugins/plugin.spec.ts
  packages/next/src/plugins/plugin.ts
  packages/next/src/utils/versions.ts
Labels: scope: nextjs

#20606 fix(testing): fix lint config generation for cypress standalone
  e2e/nx-misc/src/workspace.test.ts
  packages/cypress/src/utils/add-linter.ts
  packages/eslint/src/generators/lint-project/lint-project.ts
Labels: scope: testing tools, scope: linter

#20670 docs(nx-cloud): update broken image link for Google Auth
  docs/nx-cloud/recipes/google-auth.md
Labels: type: docs

#20720 feat(linter): add .nx to ignored folders
  packages/eslint/src/generators/init/global-eslint-config.ts
Labels: scope: linter

#20737 fix(core): fallback to checking stderr if stdout is empty on publish executor
  packages/js/src/executors/release-publish/release-publish.impl.ts
Labels: scope: core

#20709 fix(linter): move should migrate all eslint configs
  packages/eslint/src/generators/init/init-migration.ts
  packages/eslint/src/generators/utils/eslint-file.ts
  packages/workspace/src/generators/convert-to-monorepo/convert-to-monorepo.spec.ts
  packages/workspace/src/generators/convert-to-monorepo/convert-to-monorepo.ts
  packages/workspace/src/generators/move/lib/extract-base-configs.ts
  packages/workspace/src/generators/move/move.spec.ts
  packages/workspace/src/generators/move/move.ts
Labels: scope: linter

#20703 feat(nextjs): Update @nx/next to Next.js 14
  e2e/next-core/src/next-pcv3.test.ts
  e2e/next-core/src/next-webpack.test.ts
  e2e/next-core/src/next.test.ts
  e2e/next-extensions/src/next-experimental.test.ts
  packages/next/src/executors/export/export.impl.ts
  packages/next/src/utils/versions.ts
Labels: scope: nextjs

#20751 fix(nextjs): empty port should not overwrite env port
  packages/next/src/executors/server/custom-server.impl.ts
  packages/next/src/executors/server/server.impl.ts
Labels: scope: nextjs

#20754 fix(nextjs): Add missing setParserOptionProject
  packages/next/src/generators/application/lib/add-linting.ts
Labels: scope: nextjs

#20775 fix(nextjs): Page generator should work out of the box
  packages/next/src/generators/page/page.ts
  packages/react/src/generators/component/files/__fileName__.tsx__tmpl__
  packages/react/src/generators/component/lib/normalize-options.ts
  packages/react/src/generators/component/schema.d.ts
Labels: scope: nextjs

#20797 chore(react): Update unit tests to be faster
  packages/react/src/generators/application/__snapshots__/application.spec.ts.snap
  packages/react/src/generators/application/application.pcv3.spec.ts
  packages/react/src/generators/application/application.spec.ts
  packages/react/src/generators/federate-module/federate-module.spec.ts
  packages/react/src/generators/host/__snapshots__/host.spec.ts.snap
  packages/react/src/generators/host/host.spec.ts
  packages/react/src/generators/init/init.spec.ts
  packages/react/src/generators/library/__snapshots__/library.spec.ts.snap
  packages/react/src/generators/library/library.spec.ts
  packages/react/src/generators/redux/redux.spec.ts
  packages/react/src/generators/remote/__snapshots__/remote.spec.ts.snap
  packages/react/src/generators/remote/remote.spec.ts
  packages/react/src/generators/setup-ssr/setup-ssr.spec.ts
Labels: scope: react

#20826 fix(node): E2E test port conflicts
  e2e/node/src/node-server.test.ts
Labels: scope: node

#20836 feat(nextjs): Add support for experimental-https when running dev server
  docs/generated/packages/next/executors/server.json
  packages/next/src/executors/server/schema.json
  packages/next/src/executors/server/server.impl.ts
  packages/next/src/utils/types.ts
Labels: scope: nextjs

#20834 chore(react): Update react e2e tests to be more lean
  e2e/react-core/src/react-package.test.ts
  e2e/react-core/src/react.test.ts
  e2e/react-extensions/src/cypress-component-tests.test.ts
  e2e/react-module-federation/src/react-module-federation.test.ts
Labels: scope: react

#20859 fix(linter): ensure angular entry point checks are correct
  packages/eslint-plugin/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin/src/utils/runtime-lint-utils.spec.ts
  packages/eslint-plugin/src/utils/runtime-lint-utils.ts
Labels: scope: linter

#20933 fix(nextjs): Playwright should work with workspace libs
  e2e/next-extensions/src/next-playwright.test.ts
  e2e/react-extensions/src/playwright.test.ts
  packages/playwright/src/generators/configuration/configuration.ts
Labels: scope: react, scope: nextjs

#20941 fix(nextjs): Missing deps for image and css optimization
  packages/next/src/executors/build/lib/update-package-json.ts
Labels: scope: nextjs
