Repository nrwl/nx, pull requests merged in 2023-08, with the labels that each got.

#18281 feat(nextjs): add playwright as an option for e2e testing
  docs/generated/packages/next/generators/application.json
  e2e/next/src/next-appdir.test.ts
  e2e/next/src/utils.ts
  packages/next/.eslintrc.json
  packages/next/src/generators/application/application.ts
  packages/next/src/generators/application/lib/add-cypress.ts
  packages/next/src/generators/application/lib/add-e2e.ts
  packages/next/src/generators/application/schema.d.ts
  packages/next/src/generators/application/schema.json
  packages/next/src/generators/init/init.ts
  packages/next/src/generators/init/schema.d.ts
Labels: scope: nextjs, scope: testing tools

#18284 feat(web): add playwright e2eTestRunner option
  docs/generated/packages/web/generators/application.json
  docs/generated/packages/web/generators/init.json
  e2e/web/src/web.test.ts
  packages/web/.eslintrc.json
  packages/web/src/generators/application/application.spec.ts
  packages/web/src/generators/application/application.ts
  packages/web/src/generators/application/schema.d.ts
  packages/web/src/generators/application/schema.json
  packages/web/src/generators/init/init.spec.ts
  packages/web/src/generators/init/init.ts
  packages/web/src/generators/init/schema.d.ts
  packages/web/src/generators/init/schema.json
Labels: scope: misc

#18408 fix(core): update e2e tsconfig extends to be mapped to the correct root tsconfig
  e2e/nx-misc/src/workspace.test.ts
  packages/workspace/src/generators/move/lib/update-project-root-files.ts
Labels: scope: core

#18327 fix(testing): check if target exists before adding target for jest
  packages/jest/src/generators/configuration/configuration.spec.ts
  packages/jest/src/generators/configuration/lib/update-workspace.ts
Labels: scope: testing tools

#18357 docs(testing): add playwright overview page
  docs/generated/manifests/menus.json
  docs/generated/manifests/packages.json
  docs/generated/packages-metadata.json
  docs/generated/packages/playwright/documents/overview.md
  docs/map.json
  docs/shared/packages/playwright/playwright-plugin.md
  docs/shared/reference/sitemap.md
Labels: scope: testing tools

#18163 feat(angular): add playwright to e2eTestRunner option
  docs/generated/packages/angular/generators/application.json
  docs/generated/packages/angular/generators/host.json
  docs/generated/packages/angular/generators/init.json
  docs/generated/packages/angular/generators/remote.json
  e2e/angular-core/src/ng-add.test.ts
  e2e/angular-core/src/projects.test.ts
  packages/angular/.eslintrc.json
  packages/angular/package.json
  packages/angular/project.json
  packages/angular/src/generators/application/application.spec.ts
  packages/angular/src/generators/application/lib/add-e2e.ts
  packages/angular/src/generators/application/schema.json
  packages/angular/src/generators/host/schema.json
  packages/angular/src/generators/init/init.spec.ts
  packages/angular/src/generators/init/init.ts
  packages/angular/src/generators/init/schema.json
  packages/angular/src/generators/remote/schema.json
  packages/angular/src/utils/test-runners.ts
Labels: scope: testing tools, scope: angular

#18447 fix(testing): playwright plugin clean up
  .circleci/config.yml
  .github/workflows/e2e-matrix.yml
  .github/workflows/e2e-windows.yml
  docs/generated/packages/playwright/executors/playwright.json
  docs/generated/packages/playwright/generators/init.json
  e2e/angular-core/src/projects.test.ts
  e2e/angular-extensions/src/cypress-component-tests.test.ts
  e2e/cypress/src/cypress.test.ts
  e2e/next/src/next-component-tests.test.ts
  e2e/next/src/utils.ts
  e2e/react-core/src/react-module-federation.test.ts
  e2e/react-core/src/react.test.ts
  e2e/react-extensions/src/cypress-component-tests.test.ts
  e2e/utils/command-utils.ts
  e2e/web/src/web-vite.test.ts
  e2e/web/src/web.test.ts
  packages/angular/project.json
  packages/angular/src/generators/application/lib/add-e2e.ts
  packages/playwright/package.json
  packages/playwright/src/executors/playwright/playwright.ts
  packages/playwright/src/executors/playwright/schema.json
  packages/playwright/src/generators/init/init.ts
  packages/playwright/src/generators/init/schema.d.ts
  packages/playwright/src/generators/init/schema.json
Labels: scope: testing tools

#18277 docs(core): add astro recipe
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/map.json
  docs/shared/recipes/add-stack/add-astro.md
  docs/shared/reference/sitemap.md
Labels: type: docs

#18394 fix(linter): ensure package detection works in PnP
  packages/eslint-plugin/src/utils/config-utils.ts
Labels: scope: linter

#18306 fix(core): report should not include non-plugin packages as local plugins
  packages/nx/src/command-line/generate/generate.ts
  packages/nx/src/command-line/list/list.ts
  packages/nx/src/command-line/report/report.ts
  packages/nx/src/utils/plugins/local-plugins.ts
  packages/nx/src/utils/plugins/plugin-capabilities.ts
Labels: scope: core

#18462 fix(react): add babel/core when babel/preset-react is preset
  packages/react-native/src/generators/init/init.ts
  packages/react/migrations.json
  packages/react/src/generators/application/lib/install-common-dependencies.ts
  packages/react/src/generators/library/lib/install-common-dependencies.ts
  packages/react/src/migrations/update-16-7-0/add-babel-core.spec.ts
  packages/react/src/migrations/update-16-7-0/add-babel-core.ts
  packages/react/src/utils/versions.ts
Labels: scope: react

#18474 feat(linter): update eslint to 8.46.0
  package.json
  packages/angular/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/cypress/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/linter/migrations.json
  packages/linter/src/utils/versions.ts
  packages/nest/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  pnpm-lock.yaml
Labels: scope: linter

#18302 feat(core): expand support for projectRoot token to include project.json
  e2e/nx-run/src/run.test.ts
  packages/nx/src/config/workspaces.spec.ts
  packages/nx/src/config/workspaces.ts
  packages/nx/src/project-graph/build-nodes/workspace-projects.spec.ts
  packages/nx/src/project-graph/build-nodes/workspace-projects.ts
Labels: scope: core

#17532 feat(linter): add generator for converting to flat config
  docs/generated/manifests/menus.json
  docs/generated/manifests/packages.json
  docs/generated/packages-metadata.json
  docs/generated/packages/linter/generators/convert-to-flat-config.json
  docs/shared/reference/sitemap.md
  e2e/linter/src/linter.test.ts
  package.json
  packages/angular/src/generators/ng-add/__snapshots__/migrate-from-angular-cli.spec.ts.snap
  packages/angular/src/generators/ng-add/utilities/workspace.ts
  packages/linter/generators.json
  packages/linter/package.json
  packages/linter/src/executors/eslint/lint.impl.ts
  packages/linter/src/generators/convert-to-flat-config/__snapshots__/generator.spec.ts.snap
  packages/linter/src/generators/convert-to-flat-config/converters/generate-ast.ts
  packages/linter/src/generators/convert-to-flat-config/converters/json-converter.spec.ts
  packages/linter/src/generators/convert-to-flat-config/converters/json-converter.ts
  packages/linter/src/generators/convert-to-flat-config/generator.spec.ts
  packages/linter/src/generators/convert-to-flat-config/generator.ts
  packages/linter/src/generators/convert-to-flat-config/schema.d.ts
  packages/linter/src/generators/convert-to-flat-config/schema.json
  packages/linter/src/generators/init/init.spec.ts
  packages/linter/src/generators/init/init.ts
  packages/linter/src/utils/versions.ts
  packages/nx/src/command-line/init/implementation/angular/standalone-workspace.ts
  pnpm-lock.yaml
Labels: scope: linter

#18535 feat(testing): Vite 5 compatibility
  packages/cypress/src/plugins/preprocessor-vite.ts
  packages/react/plugins/component-testing/index.ts
Labels: scope: testing tools

#18556 docs(core): Add vue documentation for nx-recipe
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/map.json
  docs/shared/recipes/add-stack/add-vue.md
  docs/shared/reference/sitemap.md
Labels: type: docs, scope: docs

#18464 feat(linter): deprecate tslint
  CONTRIBUTING.md
  docs/generated/packages/angular/generators/convert-tslint-to-eslint.json
  docs/generated/packages/linter/documents/overview.md
  docs/generated/packages/nest/generators/convert-tslint-to-eslint.json
  docs/shared/monorepo-nx-enterprise.md
  docs/shared/packages/linter/linter-plugin.md
  docs/shared/recipes/generators/generator-options.md
  nx-dev/models-package/src/lib/json-schema.models.ts
  packages/angular/generators.json
  packages/angular/src/generators/convert-tslint-to-eslint/compat.ts
  packages/angular/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts
  packages/angular/src/generators/convert-tslint-to-eslint/schema.json
  packages/angular/src/utils/nx-devkit/ast-utils.ts
  packages/cypress/index.ts
  packages/cypress/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts
  packages/cypress/src/generators/convert-tslint-to-eslint/schema.json
  packages/jest/src/generators/configuration/lib/update-workspace.ts
  packages/linter/index.ts
  packages/linter/src/utils/convert-tslint-to-eslint/convert-nx-enforce-module-boundaries-rule.ts
  packages/linter/src/utils/convert-tslint-to-eslint/convert-to-eslint-config.ts
  packages/linter/src/utils/convert-tslint-to-eslint/project-converter.ts
  packages/linter/src/utils/convert-tslint-to-eslint/utils.ts
  packages/linter/src/utils/versions.ts
  packages/nest/generators.json
  packages/nest/index.ts
  packages/nest/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts
  packages/nest/src/generators/convert-tslint-to-eslint/schema.json
  packages/nx/src/native/index.d.ts
  scripts/documentation/json-parser.ts
Labels: scope: linter

#18553 fix(linter): bump eslint-plugin-cypress
  package.json
  packages/cypress/migrations.json
  packages/cypress/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/cypress/src/utils/versions.ts
  pnpm-lock.yaml
Labels: scope: testing tools, scope: linter

#18575 docs(core): Update vue recipe to include a library
  docs/shared/recipes/add-stack/add-vue.md
Labels: type: docs, scope: docs

#18032 feat(core): add api for v2 of project project graph plugins
  docs/generated/devkit/CreateDependencies.md
  docs/generated/devkit/CreateDependenciesContext.md
  docs/generated/devkit/CreateNodes.md
  docs/generated/devkit/CreateNodesContext.md
  docs/generated/devkit/CreateNodesFunction.md
  docs/generated/devkit/NxPlugin.md
  docs/generated/devkit/NxPluginV1.md
  docs/generated/devkit/NxPluginV2.md
  docs/generated/devkit/ProjectGraphBuilder.md
  docs/generated/devkit/ProjectGraphDependencyWithFile.md
  docs/generated/devkit/ProjectGraphProcessorContext.md
  docs/generated/devkit/ProjectTargetConfigurator.md
  docs/generated/devkit/README.md
  docs/generated/devkit/validateDependency.md
  docs/generated/packages/devkit/documents/nx_devkit.md
  package.json
  packages/devkit/src/utils/module-federation/share.spec.ts
  packages/nx/plugins/package-json-workspaces.ts
  packages/nx/plugins/project-json.ts
  packages/nx/src/adapter/angular-json.ts
  packages/nx/src/command-line/run/run.ts
  packages/nx/src/config/project-graph.ts
  packages/nx/src/config/workspaces.spec.ts
  packages/nx/src/config/workspaces.ts
  packages/nx/src/daemon/server/project-graph-incremental-recomputation.ts
  packages/nx/src/devkit-exports.ts
  packages/nx/src/generators/utils/project-configuration.spec.ts
  packages/nx/src/generators/utils/project-configuration.ts
  packages/nx/src/migrations/update-15-0-0/migrate-to-inputs.spec.ts
  packages/nx/src/native/index.d.ts
  packages/nx/src/native/tests/workspace_files.spec.ts
  packages/nx/src/native/workspace/get_config_files.rs
  packages/nx/src/native/workspace/get_nx_workspace_files.rs
  packages/nx/src/native/workspace/types.rs
  packages/nx/src/plugins/js/lock-file/npm-parser.spec.ts
  packages/nx/src/plugins/js/lock-file/pnpm-parser.spec.ts
  packages/nx/src/plugins/js/lock-file/yarn-parser.spec.ts
  packages/nx/src/project-graph/affected/locators/project-glob-changes.ts
  packages/nx/src/project-graph/build-dependencies/implict-project-dependencies.spec.ts
  packages/nx/src/project-graph/build-nodes/workspace-projects.spec.ts
  packages/nx/src/project-graph/build-nodes/workspace-projects.ts
  packages/nx/src/project-graph/build-project-graph.ts
  packages/nx/src/project-graph/nx-deps-cache.ts
  packages/nx/src/project-graph/project-graph-builder.ts
  packages/nx/src/project-graph/project-graph.ts
  packages/nx/src/project-graph/utils/project-configuration-utils.spec.ts
  packages/nx/src/project-graph/utils/project-configuration-utils.ts
  packages/nx/src/project-graph/utils/retrieve-workspace-files.ts
  packages/nx/src/tasks-runner/utils.ts
  packages/nx/src/utils/find-matching-projects.ts
  packages/nx/src/utils/globs.ts
  packages/nx/src/utils/nx-plugin.deprecated.ts
  packages/nx/src/utils/nx-plugin.ts
  packages/nx/src/utils/package-manager.spec.ts
  packages/nx/src/utils/plugins/plugin-capabilities.ts
  pnpm-lock.yaml
Labels: scope: core

#18619 fix(nx-dev): ensure long titles on og images have line breaks
  scripts/documentation/open-graph/generate-images.ts
Labels: scope: docs

#18587 docs(testing): update docs to use configuration generator
  docs/generated/packages/cypress/documents/overview.md
  docs/generated/packages/cypress/executors/cypress.json
  docs/generated/packages/cypress/generators/cypress-project.json
  docs/generated/packages/jest/documents/overview.md
  docs/shared/packages/cypress/cypress-plugin.md
  docs/shared/packages/jest/jest-plugin.md
  packages/cypress/docs/cypress-examples.md
  packages/cypress/docs/cypress-project-examples.md
Labels: type: docs, scope: testing tools

#18558 fix(testing): playwright cleanup
  docs/generated/packages/playwright/generators/configuration.json
  packages/next/src/generators/application/lib/add-e2e.ts
  packages/next/src/generators/application/lib/normalize-options.ts
  packages/next/src/generators/application/lib/update-cypress-tsconfig.ts
  packages/playwright/src/executors/playwright/playwright.ts
  packages/playwright/src/generators/configuration/schema.d.ts
  packages/playwright/src/generators/configuration/schema.json
Labels: scope: testing tools

#18549 docs(core): add Nuxt recipe
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/map.json
  docs/shared/recipes/add-stack/add-nuxt.md
  docs/shared/reference/sitemap.md
Labels: type: docs

#18590 docs(core): Add svelte docs recipe
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/map.json
  docs/shared/recipes/add-stack/add-svelte.md
  docs/shared/recipes/add-stack/add-vue.md
  docs/shared/reference/sitemap.md
Labels: type: docs, scope: docs

#18669 fix(core): use existing version when calling "yarn set version"
  packages/create-nx-workspace/src/utils/package-manager.ts
  packages/nx/src/utils/package-manager.ts
Labels: scope: core

#18661 fix(nextjs): make next build package manager agnostic
  packages/next/src/executors/build/build.impl.ts
Labels: scope: nextjs

#18687 fix(core): nx should not break if packages were not installed
  packages/nx/src/plugins/js/index.ts
Labels: scope: core

#18395 fix(core): fix schema links
  packages/nx/schemas/nx-schema.json
  packages/nx/schemas/project-schema.json
Labels: scope: core

#18615 feat(react): use helper to determine project name and root directory in project generators
  docs/generated/packages/react/generators/application.json
  docs/generated/packages/react/generators/host.json
  docs/generated/packages/react/generators/library.json
  docs/generated/packages/react/generators/remote.json
  e2e/react-core/src/react-module-federation.test.ts
  e2e/react-core/src/react.test.ts
  packages/devkit/src/generators/project-name-and-root-utils.spec.ts
  packages/devkit/src/generators/project-name-and-root-utils.ts
  packages/react/generators.json
  packages/react/src/generators/application/application.spec.ts
  packages/react/src/generators/application/application.ts
  packages/react/src/generators/application/lib/add-e2e.ts
  packages/react/src/generators/application/lib/normalize-options.ts
  packages/react/src/generators/application/schema.d.ts
  packages/react/src/generators/application/schema.json
  packages/react/src/generators/host/host.ts
  packages/react/src/generators/host/schema.d.ts
  packages/react/src/generators/host/schema.json
  packages/react/src/generators/library/lib/add-rollup-build-target.ts
  packages/react/src/generators/library/lib/normalize-options.spec.ts
  packages/react/src/generators/library/lib/normalize-options.ts
  packages/react/src/generators/library/lib/update-app-routes.ts
  packages/react/src/generators/library/library.ts
  packages/react/src/generators/library/schema.d.ts
  packages/react/src/generators/library/schema.json
  packages/react/src/generators/remote/remote.ts
  packages/react/src/generators/remote/schema.d.ts
  packages/react/src/generators/remote/schema.json
Labels: scope: react

#18663 docs(core): remove references to --all for run-many
  docs/generated/cli/affected.md
  docs/generated/cli/run-many.md
  docs/generated/packages/nx/documents/affected.md
  docs/generated/packages/nx/documents/run-many.md
  docs/nx-cloud/reference/config.md
  docs/shared/mental-model.md
  docs/shared/reference/nx-json.md
  e2e/nx-run/src/run.test.ts
  e2e/web/src/web.test.ts
  package.json
  packages/nx/src/command-line/examples.ts
  packages/nx/src/command-line/yargs-utils/shared-options.ts
  scripts/build.sh
Labels: scope: docs, scope: repo

#18716 docs(core): Create embeddings fix null url paths
  tools/documentation/create-embeddings/src/main.mts
Labels: type: docs, scope: docs

#18671 fix(core): ensure preinstall is only run once on repo
  packages/devkit/src/tasks/install-packages-task.ts
  packages/workspace/src/generators/new/new.ts
Labels: scope: core

#18700 fix(core): skip local yarn patches for lock file pruning
  packages/nx/src/plugins/js/lock-file/yarn-parser.ts
Labels: type: bug, scope: core

#18729 fix(testing): make playwright nxE2EPreset options optional
  packages/playwright/src/utils/preset.ts
Labels: scope: testing tools

#18670 fix(misc): format must exclude ignored patterns
  packages/nx/src/command-line/format/format.ts
Labels: scope: core

#18534 feat(linter): add flat config support to generators
  package.json
  packages/angular/src/generators/add-linting/add-linting.ts
  packages/angular/src/generators/add-linting/lib/create-eslint-configuration.ts
  packages/cypress/src/generators/configuration/configuration.spec.ts
  packages/cypress/src/utils/add-linter.ts
  packages/detox/src/generators/application/lib/add-linting.ts
  packages/expo/src/utils/add-linting.ts
  packages/js/src/generators/library/library.ts
  packages/linter/src/executors/eslint/lint.impl.ts
  packages/linter/src/executors/eslint/schema.d.ts
  packages/linter/src/generators/convert-to-flat-config/converters/generate-ast.ts
  packages/linter/src/generators/convert-to-flat-config/converters/json-converter.ts
  packages/linter/src/generators/init/global-eslint-config.ts
  packages/linter/src/generators/init/init-migration.ts
  packages/linter/src/generators/lint-project/lint-project.ts
  packages/linter/src/generators/utils/eslint-file.ts
  packages/linter/src/generators/utils/flat-config/ast-utils.spec.ts
  packages/linter/src/generators/utils/flat-config/ast-utils.ts
  packages/linter/src/generators/utils/flat-config/path-utils.ts
  packages/linter/src/generators/workspace-rule/workspace-rule.ts
  packages/linter/src/utils/flat-config.ts
  packages/next/src/generators/application/application.spec.ts
  packages/next/src/generators/application/lib/add-linting.spec.ts
  packages/next/src/generators/application/lib/add-linting.ts
  packages/node/src/generators/e2e-project/e2e-project.ts
  packages/nx/src/command-line/init/implementation/angular/standalone-workspace.ts
  packages/playwright/src/utils/add-linter.ts
  packages/plugin/src/generators/lint-checks/generator.ts
  packages/react-native/src/utils/add-linting.ts
  packages/react/src/generators/application/application.ts
  packages/react/src/generators/application/lib/add-e2e.ts
  packages/react/src/generators/library/lib/add-linting.ts
  packages/react/src/utils/lint.ts
  packages/storybook/src/generators/configuration/lib/util-functions.ts
  packages/workspace/src/generators/move/lib/move-project-files.ts
  packages/workspace/src/generators/move/lib/update-eslint-config.spec.ts
  packages/workspace/src/generators/move/lib/update-eslint-config.ts
  packages/workspace/src/generators/move/lib/update-eslintrc-json.spec.ts
  packages/workspace/src/generators/move/lib/update-eslintrc-json.ts
  packages/workspace/src/generators/move/lib/update-project-root-files.ts
  packages/workspace/src/generators/move/move.ts
  pnpm-lock.yaml
Labels: scope: linter

#18614 docs(linter): add recipe for flat config converter
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/generated/manifests/packages.json
  docs/generated/manifests/tags.json
  docs/generated/packages-metadata.json
  docs/generated/packages/linter/documents/overview.md
  docs/generated/packages/linter/generators/convert-to-flat-config.json
  docs/map.json
  docs/shared/packages/linter/linter-plugin.md
  docs/shared/recipes/tips-n-tricks/migrating-to-flat-eslint.md
  docs/shared/reference/sitemap.md
  packages/linter/generators.json
  packages/linter/src/generators/convert-to-flat-config/schema.json
Labels: scope: docs, scope: linter

#18629 chore(nx-dev): switch e2e to playwright
  .circleci/config.yml
  docs/nx-cloud/private/auth-saml.md
  docs/nx-cloud/reference/release-notes.md
  nx-dev/nx-dev-e2e/.eslintrc.json
  nx-dev/nx-dev-e2e/cypress.config.ts
  nx-dev/nx-dev-e2e/playwright.config.ts
  nx-dev/nx-dev-e2e/project.json
  nx-dev/nx-dev-e2e/src/additional-api-references.spec.ts
  nx-dev/nx-dev-e2e/src/app.spec.ts
  nx-dev/nx-dev-e2e/src/e2e/additional-api-references.cy.ts
  nx-dev/nx-dev-e2e/src/e2e/app.cy.ts
  nx-dev/nx-dev-e2e/src/e2e/helpers.ts
  nx-dev/nx-dev-e2e/src/e2e/nx-cloud-documentation.cy.ts
  nx-dev/nx-dev-e2e/src/e2e/packages.cy.ts
  nx-dev/nx-dev-e2e/src/e2e/recipes.cy.ts
  nx-dev/nx-dev-e2e/src/fixtures/.gitkeep
  nx-dev/nx-dev-e2e/src/helpers.ts
  nx-dev/nx-dev-e2e/src/nx-cloud-documentation.spec.ts
  nx-dev/nx-dev-e2e/src/packages.spec.ts
  nx-dev/nx-dev-e2e/src/recipes.spec.ts
  nx-dev/nx-dev-e2e/src/support/commands.ts
  nx-dev/nx-dev-e2e/src/support/e2e.ts
  nx-dev/nx-dev-e2e/tsconfig.json
  nx-dev/nx-dev/project.json
  package.json
  pnpm-lock.yaml
Labels: type: docs, scope: testing tools

#18775 chore(testing): update cypress e2e for timeout issues
  e2e/cypress/src/cypress.test.ts
Labels: scope: testing tools

#18597 fix(testing): improve error message for ct generators
  docs/generated/packages/angular/generators/cypress-component-configuration.json
  docs/generated/packages/cypress/documents/cypress-component-testing.md
  docs/shared/packages/cypress/cypress-component-testing.md
  packages/angular/docs/cypress-component-configuration-examples.md
  packages/cypress/src/utils/find-target-options.ts
Labels: scope: testing tools

#18800 docs(nextjs): fix formatting issue with install command
  docs/generated/packages/next/documents/overview.md
  docs/shared/packages/next/plugin-overview.md
Labels: type: docs, scope: nextjs

#18647 feat(repo): add pm version field to issue template
  .github/ISSUE_TEMPLATE/1-bug.yml
Labels: scope: repo

#18797 fix(vite): support incremental building when running 'serve'
  packages/vite/src/utils/executor-utils.ts
Labels: scope: bundlers

#18477 fix(bundling): fallback to manual file resolution if tsconfig-paths fails
  e2e/vite/src/vite.test.ts
  packages/vite/plugins/nx-tsconfig-paths.plugin.ts
Labels: scope: bundlers

#18795 fix(core): convert to monorepo generator should respect nested libs
  packages/workspace/src/generators/convert-to-monorepo/convert-to-monorepo.spec.ts
  packages/workspace/src/generators/convert-to-monorepo/convert-to-monorepo.ts
Labels: scope: core

#18827 fix(nextjs): improve e2e test by reusing the project
  CODEOWNERS
  e2e/next-core/jest.config.ts
  e2e/next-core/project.json
  e2e/next-core/src/next-appdir.test.ts
  e2e/next-core/src/next-lock-file.test.ts
  e2e/next-core/src/next-structure.test.ts
  e2e/next-core/src/next-webpack.test.ts
  e2e/next-core/src/next.test.ts
  e2e/next-core/src/utils.ts
  e2e/next-core/tsconfig.json
  e2e/next-core/tsconfig.spec.json
  e2e/next-extensions/jest.config.ts
  e2e/next-extensions/project.json
  e2e/next-extensions/src/next-component-tests.test.ts
  e2e/next-extensions/src/next-experimental.test.ts
  e2e/next-extensions/src/next-storybook.test.ts
  e2e/next-extensions/src/next-styles.test.ts
  e2e/next-extensions/src/utils.ts
  e2e/next-extensions/tsconfig.json
  e2e/next-extensions/tsconfig.spec.json
Labels: scope: nextjs

#18863 feat(linter): add option to ignore files based on pattern
  packages/eslint-plugin/src/rules/dependency-checks.spec.ts
  packages/eslint-plugin/src/rules/dependency-checks.ts
  packages/js/src/generators/library/library.spec.ts
  packages/js/src/generators/library/library.ts
  packages/js/src/utils/find-npm-dependencies.spec.ts
  packages/js/src/utils/find-npm-dependencies.ts
Labels: scope: linter

#18839 fix(testing): omit indexHtmlFile option for cy >12.17.0 for ng ct
  packages/angular/plugins/component-testing.ts
Labels: scope: testing tools

#18891 fix(node): pass projectNameAndRootFormat to js lib generator from nest lib generator
  packages/express/src/generators/application/application.spec.ts
  packages/express/src/generators/init/init.spec.ts
  packages/nest/src/generators/application/application.spec.ts
  packages/nest/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/nest/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.spec.ts
  packages/nest/src/generators/init/init.spec.ts
  packages/nest/src/generators/library/__snapshots__/library.spec.ts.snap
  packages/nest/src/generators/library/lib/normalize-options.ts
  packages/nest/src/generators/library/library.spec.ts
  packages/nest/src/generators/utils/testing.ts
  packages/node/src/generators/application/application.spec.ts
  packages/node/src/generators/e2e-project/e2e-project.spec.ts
  packages/node/src/generators/init/init.spec.ts
  packages/node/src/generators/library/library.spec.ts
  packages/node/src/generators/setup-docker/setup-docker.spec.ts
Labels: scope: node

#18894 chore(js): update js plugin unit tests to use "as-provided" option when generating apps/libs
  packages/js/src/generators/convert-to-swc/convert-to-swc.spec.ts
  packages/js/src/generators/library/__snapshots__/library.spec.ts.snap
  packages/js/src/generators/library/library.spec.ts
  packages/js/src/migrations/update-16-6-0/explicitly-set-projects-to-update-buildable-deps.spec.ts
Labels: scope: js

#18900 chore(expo): update expo plugin unit tests to use "as-provided"
  packages/expo/src/generators/application/application.spec.ts
  packages/expo/src/generators/application/lib/nomalize-options.spec.ts
  packages/expo/src/generators/component/component.spec.ts
  packages/expo/src/generators/init/init.spec.ts
  packages/expo/src/generators/library/library.spec.ts
  packages/expo/src/utils/add-linting.spec.ts
Labels: scope: react

#18882 feat(linter): migrate projects using dep-check lint rule to ignore build config files
  packages/linter/migrations.json
  packages/linter/src/migrations/update-16-8-0-add-ignored-files/update-16-8-0-add-ignored-files.spec.ts
  packages/linter/src/migrations/update-16-8-0-add-ignored-files/update-16-8-0-add-ignored-files.ts
Labels: scope: linter

#18893 chore(react): update unit tests to use "as-provided" when generating apps/libs
  packages/react/src/generators/application/__snapshots__/application.spec.ts.snap
  packages/react/src/generators/application/application.spec.ts
  packages/react/src/generators/component-cypress-spec/component-cypress-spec.spec.ts
  packages/react/src/generators/component-story/component-story.spec.ts
  packages/react/src/generators/component-test/component-test.spec.ts
  packages/react/src/generators/component/component.spec.ts
  packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.spec.ts
  packages/react/src/generators/hook/hook.spec.ts
  packages/react/src/generators/host/host.spec.ts
  packages/react/src/generators/init/init.spec.ts
  packages/react/src/generators/library/library.spec.ts
  packages/react/src/generators/redux/redux.spec.ts
  packages/react/src/generators/remote/remote.spec.ts
  packages/react/src/generators/setup-ssr/setup-ssr.spec.ts
  packages/react/src/generators/setup-tailwind/setup-tailwind.spec.ts
  packages/react/src/generators/stories/stories.app.spec.ts
  packages/react/src/generators/stories/stories.lib.spec.ts
  packages/react/src/generators/stories/stories.nextjs.spec.ts
  packages/react/src/generators/storybook-configuration/configuration.spec.ts
  packages/react/src/migrations/update-16-7-0-add-typings/update-16-7-0-add-typings.spec.ts
  packages/react/src/utils/testing-generators.ts
  packages/web/src/generators/application/application.spec.ts
  packages/web/src/generators/init/init.spec.ts
  packages/web/src/generators/static-serve/static-serve-configuration.spec.ts
Labels: scope: react

#18915 chore(detox): update detox plugin unit tests to use "as-provided"
  packages/detox/src/generators/application/application.spec.ts
  packages/detox/src/generators/init/init.spec.ts
Labels: scope: react-native

#18945 chore(react-native): update react-native plugin unit tests to use "as-provided"
  packages/react-native/src/generators/application/application.spec.ts
  packages/react-native/src/generators/application/lib/nomalize-options.spec.ts
  packages/react-native/src/generators/component-story/component-story.spec.ts
  packages/react-native/src/generators/component/component.spec.ts
  packages/react-native/src/generators/init/init.spec.ts
  packages/react-native/src/generators/library/library.spec.ts
  packages/react-native/src/generators/stories/stories-app.spec.ts
  packages/react-native/src/generators/stories/stories-lib.spec.ts
  packages/react-native/src/generators/storybook-configuration/configuration.spec.ts
  packages/react-native/src/generators/storybook-configuration/lib/add-resolver-main-fields-to-metro-config.spec.ts
  packages/react-native/src/generators/storybook-configuration/lib/replace-app-import-with-storybook-toggle.spec.ts
  packages/react-native/src/utils/testing-generators.ts
Labels: scope: react-native

#18951 chore(testing): update nightly ci to ensure cy is available
  e2e/cypress/src/cypress.test.ts
Labels: scope: testing tools
