Repository nrwl/nx, pull requests merged in 2023-07, with the labels that each got.

#17755 feat(linter): allow banning of deep/secondary paths
  packages/eslint-plugin/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin/src/utils/runtime-lint-utils.spec.ts
  packages/eslint-plugin/src/utils/runtime-lint-utils.ts
Labels: type: feature, scope: linter

#17705 docs(core): add root-level example to top-level run tasks docs page
  docs/shared/core-features/run-tasks.md
Labels: type: docs

#17918 feat(testing): add test-setup.ts to ignored prod inputs
  packages/jest/migrations.json
  packages/jest/src/generators/init/init.spec.ts
  packages/jest/src/generators/init/init.ts
  packages/jest/src/migrations/update-16-5-0/add-test-setup-to-inputs-ignore.spec.ts
  packages/jest/src/migrations/update-16-5-0/add-test-setup-to-inputs-ignore.ts
Labels: scope: testing tools

#17896 docs(nx-dev): rename menu items for getting started
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/map.json
  docs/shared/reference/sitemap.md
Labels: scope: docs

#17916 feat(linter): bump typescript-eslint to 5.60.1
  package.json
  packages/angular/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/cypress/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/eslint-plugin/package.json
  packages/linter/migrations.json
  packages/linter/src/migrations/update-14-4-4/__snapshots__/experimental-to-utils-deps.spec.ts.snap
  packages/linter/src/utils/versions.ts
  packages/nest/src/generators/convert-tslint-to-eslint/__snapshots__/convert-tslint-to-eslint.spec.ts.snap
  packages/workspace/src/utils/versions.ts
  pnpm-lock.yaml
Labels: scope: linter

#17941 docs(nx-dev): fix link titles to Advanced Update Process
  docs/generated/manifests/menus.json
  docs/generated/manifests/recipes.json
  docs/generated/manifests/tags.json
  docs/map.json
  docs/shared/reference/sitemap.md
Labels: type: docs

#17926 fix(core): ensure external dependency hashes are resolved in a deterministic way
  packages/nx/src/hasher/task-hasher.spec.ts
  packages/nx/src/hasher/task-hasher.ts
Labels: type: bug, scope: core

#18004 docs(core): changelog for 16.5.0
  docs/changelog/16_5_0.md
Labels: type: docs

#17962 docs(linter): add documentation on dependency-checks rule
  docs/generated/manifests/menus.json
  docs/generated/manifests/packages.json
  docs/generated/packages-metadata.json
  docs/generated/packages/eslint-plugin/documents/dependency-checks.md
  docs/generated/packages/eslint-plugin/documents/enforce-module-boundaries.md
  docs/generated/packages/eslint-plugin/documents/overview.md
  docs/map.json
  docs/shared/packages/linter/dependency-checks.md
  docs/shared/packages/linter/enforce-module-boundaries.md
  docs/shared/packages/linter/eslint-plugin.md
  docs/shared/reference/sitemap.md
Labels: type: docs, scope: linter

#17993 docs(angular): add info for angular 16.1.0 in version compatibility matrix docs
  docs/generated/packages/angular/documents/angular-nx-version-matrix.md
  docs/shared/packages/angular/angular-nx-version-matrix.md
Labels: type: docs

#18061 feat(testing): update jest to v29.6.1
  packages/jest/migrations.json
  packages/jest/src/utils/versions.ts
Labels: scope: testing tools

#17975 feat(testing): add @nx/playwright plugin
  CODEOWNERS
  e2e/playwright/jest.config.ts
  e2e/playwright/project.json
  e2e/playwright/src/playwright.test.ts
  e2e/playwright/tsconfig.json
  e2e/playwright/tsconfig.spec.json
  e2e/utils/create-project-utils.ts
  e2e/utils/get-env-info.ts
  jest.config.ts
  packages/nx/package.json
  packages/playwright/.eslintrc.json
  packages/playwright/README.md
  packages/playwright/executors.json
  packages/playwright/jest.config.ts
  packages/playwright/package.json
  packages/playwright/project.json
  packages/playwright/src/executors/playwright/compat.ts
  packages/playwright/src/executors/playwright/playwright.ts
  packages/playwright/src/executors/playwright/schema.json
  packages/playwright/src/index.ts
  packages/playwright/tsconfig.json
  packages/playwright/tsconfig.lib.json
  packages/playwright/tsconfig.spec.json
  tsconfig.base.json
Labels: scope: testing tools

#18096 Revert "feat(testing): update jest to v29.6.1 (#18061)"
  packages/jest/migrations.json
  packages/jest/src/utils/versions.ts
Labels: scope: testing tools

#17844 feat(vite): add tsconfig paths resolution plugin
  e2e/vite/src/vite.test.ts
  packages/vite/migrations.json
  packages/vite/package.json
  packages/vite/plugins/nx-tsconfig-paths.plugin.ts
  packages/vite/src/executors/build/build.impl.ts
  packages/vite/src/executors/dev-server/dev-server.impl.ts
  packages/vite/src/generators/configuration/__snapshots__/configuration.spec.ts.snap
  packages/vite/src/generators/configuration/configuration.spec.ts
  packages/vite/src/generators/init/__snapshots__/init.spec.ts.snap
  packages/vite/src/generators/init/init.ts
  packages/vite/src/generators/vitest/__snapshots__/vitest.spec.ts.snap
  packages/vite/src/migrations/update-16-6-0-change-ts-paths-plugin/change-ts-paths-plugin.spec.ts
  packages/vite/src/migrations/update-16-6-0-change-ts-paths-plugin/change-ts-paths-plugin.ts
  packages/vite/src/utils/executor-utils.ts
  packages/vite/src/utils/generator-utils.ts
  packages/vite/src/utils/versions.ts
Labels: scope: bundlers

#18187 fix(nx-dev): fix project config reference headlines
  docs/shared/reference/project-configuration.md
Labels: scope: docs

#18190 feat(testing): add options for frameworks in playwright configuration…
  packages/playwright/package.json
  packages/playwright/src/generators/configuration/configuration.ts
  packages/playwright/src/generators/configuration/files/playwright.config.ts.template
  packages/playwright/src/generators/configuration/schema.d.ts
  packages/playwright/src/generators/configuration/schema.json
  packages/playwright/src/generators/init/init.ts
  packages/playwright/src/index.ts
Labels: scope: testing tools

#18194 feat(testing): add playwright e2e preset
  package.json
  packages/playwright/src/generators/configuration/files/playwright.config.ts.template
  packages/playwright/src/index.ts
  packages/playwright/src/utils/preset.ts
  pnpm-lock.yaml
Labels: scope: testing tools

#18195 fix(testing): run playwright from workspaceRoot
  packages/playwright/src/executors/playwright/playwright.ts
  packages/playwright/src/generators/configuration/configuration.ts
Labels: scope: testing tools

#18227 fix(testing): update playwright tsconfig.base.json and entrypoint
  packages/playwright/index.ts
  tsconfig.base.json
Labels: scope: testing tools

#18287 feat(nx-dev): github star widget
  nx-dev/feature-doc-viewer/src/lib/doc-viewer.tsx
  nx-dev/feature-doc-viewer/src/lib/table-of-contents.tsx
  nx-dev/nx-dev/lib/githubStars.api.ts
  nx-dev/nx-dev/pages/[...segments].tsx
  nx-dev/nx-dev/pages/extending-nx/[...segments].tsx
  nx-dev/nx-dev/pages/extending-nx/index.tsx
  nx-dev/nx-dev/pages/nx-cloud/[...segments].tsx
  nx-dev/nx-dev/pages/nx-cloud/index.tsx
  nx-dev/nx-dev/pages/packages/[name]/documents/[...segments].tsx
  nx-dev/nx-dev/pages/packages/rspack/documents/overview.tsx
  nx-dev/nx-dev/pages/packages/rspack/documents/rspack-config-setup.tsx
  nx-dev/nx-dev/pages/packages/rspack/documents/rspack-plugins.tsx
  nx-dev/ui-common/src/index.ts
  nx-dev/ui-common/src/lib/github-star-widget.tsx
Labels: scope: docs

#18305 chore(misc): remove usage of deprecated updateBuildableProjectDepsInPackageJson option
  packages-legacy/angular/project.json
  packages-legacy/cypress/project.json
  packages-legacy/detox/project.json
  packages-legacy/devkit/project.json
  packages-legacy/esbuild/project.json
  packages-legacy/eslint-plugin-nx/project.json
  packages-legacy/expo/project.json
  packages-legacy/express/project.json
  packages-legacy/jest/project.json
  packages-legacy/js/project.json
  packages-legacy/linter/project.json
  packages-legacy/nest/project.json
  packages-legacy/next/project.json
  packages-legacy/node/project.json
  packages-legacy/nx-plugin/project.json
  packages-legacy/react-native/project.json
  packages-legacy/react/project.json
  packages-legacy/rollup/project.json
  packages-legacy/storybook/project.json
  packages-legacy/vite/project.json
  packages-legacy/web/project.json
  packages-legacy/webpack/project.json
  packages-legacy/workspace/project.json
  packages/vite/project.json
Labels: scope: misc

#18326 fix(core): shell script invocation should use yarn for berry
  packages/nx/src/utils/package-manager.ts
Labels: scope: core

#18317 fix(core): eslint dep check rule should check prereleases correctly
  packages/eslint-plugin/src/rules/dependency-checks.ts
Labels: scope: core

#18323 fix(linter): ensure tslint converter works with pnp
  packages/angular/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.spec.ts
  packages/cypress/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.spec.ts
  packages/linter/src/utils/convert-tslint-to-eslint/convert-to-eslint-config.ts
Labels: scope: linter

#18351 docs(nx-dev): remove reference commands
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/map.json
  docs/shared/reference/commands.md
  docs/shared/reference/sitemap.md
  nx-dev/nx-dev/redirect-rules.js
Labels: scope: docs

#18352 fix(nx-dev): enable nx logo on docs to navigate to home
  nx-dev/ui-common/src/lib/documentation-header.tsx
Labels: scope: docs

#18363 fix(js): fix misc issues in tsc batch executor
  docs/generated/packages/js/executors/tsc.json
  docs/shared/incremental-builds.md
  packages/js/docs/tsc-examples.md
  packages/js/src/executors/tsc/lib/batch/build-task-info-per-tsconfig-map.ts
  packages/js/src/executors/tsc/lib/get-task-options.ts
  packages/js/src/executors/tsc/lib/get-tsconfig.ts
Labels: scope: js

#18366 fix(react-native): update generated jest config to be in sync w/cache
  packages/react-native/src/generators/application/application.spec.ts
  packages/react-native/src/generators/library/library.spec.ts
  packages/react-native/src/utils/add-jest.ts
Labels: scope: testing tools, scope: react-native

#18343 fix(storybook): support pnp with storybook package
  packages/storybook/src/generators/migrate-7/calling-storybook-cli.ts
  packages/storybook/src/generators/migrate-7/helper-functions.spec.ts
  packages/storybook/src/generators/migrate-7/helper-functions.ts
Labels: scope: storybook

#18321 fix(js): ensure compile swc uses current package manager
  packages/js/src/executors/swc/swc.impl.ts
  packages/js/src/utils/swc/compile-swc.ts
Labels: scope: js

#18316 feat(linter): support path wildcards in enforce-module-boundaries autofix
  packages/eslint-plugin/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin/src/utils/ast-utils.ts
Labels: scope: linter

#18275 feat(testing): set playwright to public and restrict exports
  docs/generated/manifests/menus.json
  docs/generated/manifests/packages.json
  docs/generated/packages-metadata.json
  docs/generated/packages/playwright/executors/playwright.json
  docs/generated/packages/playwright/generators/configuration.json
  docs/generated/packages/playwright/generators/init.json
  docs/shared/reference/sitemap.md
  nx-dev/nx-dev/public/images/icons/playwright.svg
  nx-dev/ui-references/src/lib/icons-map.ts
  packages/playwright/package.json
Labels: scope: testing tools

#18389 fix(angular): update magic-string dependency
  package.json
  packages/angular/package.json
  pnpm-lock.yaml
Labels: scope: angular
