Repository nrwl/nx, pull requests merged in 2023-03, with the labels that each got.

#15334 docs(core): add note to restart ts server
  docs/shared/angular-standalone-tutorial/2-project-graph.md
  docs/shared/node-server-tutorial/2-project-graph.md
  docs/shared/npm-tutorial/integrated.md
  docs/shared/react-standalone-tutorial/2-project-graph.md
Labels: type: docs

#15325 docs(core): remove IE 11
  docs/shared/guides/browser-support.md
Labels: type: docs

#15317 docs(core): reference minimatch library
  docs/shared/concepts/customizing-inputs.md
  docs/shared/concepts/how-caching-works.md
  docs/shared/reference/project-configuration.md
Labels: type: docs

#15345 fix(linter): ensure ast file detection supports tsx files
  packages/eslint-plugin-nx/src/utils/ast-utils.ts
Labels: scope: linter

#15254 docs(core): remove outdated documents
  docs/generated/packages/angular/generators/change-storybook-targets.json
  docs/generated/packages/cypress/documents/v10-migration-guide.md
  docs/generated/packages/cypress/generators/migrate-to-cypress-10.json
  docs/generated/packages/devkit.json
  docs/generated/packages/devkit/documents/index.md
  docs/generated/packages/storybook/generators/change-storybook-targets.json
  docs/generated/packages/webpack/documents/customize-webpack.md
  docs/generated/packages/workspace/generators/convert-to-nx-project.json
Labels: type: docs

#15260 fix(vite): add missing types for tsconfigs
  e2e/react/src/react-package.test.ts
  packages/react/src/generators/application/application.spec.ts
  packages/react/src/generators/library/library.spec.ts
  packages/react/src/utils/create-ts-config.ts
  packages/vite/src/generators/vitest/files/tsconfig.spec.json__tmpl__
  packages/vite/src/generators/vitest/vitest.spec.ts
Labels: scope: bundlers

#15219 fix(core): plugin should not override existing external nodes
  e2e/js/src/js-swc.test.ts
  e2e/js/src/js-tsc.test.ts
  e2e/node/src/node.test.ts
  packages/nx/src/plugins/js/project-graph/build-nodes/build-npm-package-nodes.ts
  packages/nx/src/project-graph/project-graph-builder.ts
Labels: scope: core

#15404 fix(testing): type the jest nx preset
  packages/jest/preset/jest-preset.ts
Labels: scope: testing tools

#15502 fix(core): use smarter nesting of npm packages
  packages/nx/src/lock-file/npm-parser.ts
Labels: scope: core

#15460 feat(repo): use pnpm v7 for ci
  .circleci/config.yml
Labels: scope: repo

#15504 docs(core): update deployment via ci docs
  docs/shared/recipes/ci-deployment.md
Labels: type: docs, scope: core

#15158 fix(core): catch all lock file parsing/pruning errors and provide fallback
  packages/nx/src/lock-file/lock-file.ts
  packages/nx/src/lock-file/npm-parser.ts
Labels: scope: core

#15539 chore(repo): add additional scope to codeowners
  CODEOWNERS
Labels: scope: repo

#15474 docs(expo): update docs and examples for expo
  docs/generated/manifests/menus.json
  docs/generated/manifests/packages.json
  docs/generated/packages-metadata.json
  docs/generated/packages/expo/documents/overview.md
  docs/generated/packages/expo/executors/prebuild.json
  docs/generated/packages/expo/executors/run.json
  docs/generated/packages/expo/executors/start.json
  docs/generated/packages/react-native/documents/overview.md
  docs/map.json
  docs/shared/packages/expo/expo-plugin.md
  docs/shared/packages/react-native/react-native-plugin.md
  packages/expo/docs/prebuild-examples.md
  packages/expo/docs/run-examples.md
  packages/expo/docs/start-examples.md
  packages/expo/src/executors/install/schema.d.ts
  packages/expo/src/executors/prebuild/schema.json
  packages/expo/src/executors/run/schema.json
  packages/expo/src/executors/start/schema.json
Labels: type: docs

#15581 docs(bundling): updating rspack overview and add app generator
  nx-dev/nx-dev/lib/rspack/content/overview.ts
  nx-dev/nx-dev/lib/rspack/pkg.ts
  nx-dev/nx-dev/lib/rspack/schema/generators/application.ts
  nx-dev/nx-dev/lib/rspack/schema/generators/configuration.ts
  nx-dev/nx-dev/pages/packages/index.tsx
  nx-dev/nx-dev/pages/packages/rspack/generators/application.tsx
  nx-dev/ui-common/src/lib/sidebar-container.tsx
Labels: type: docs

#15585 chore(linter): fix deprecated ts overloads in e2e tests
  e2e/linter/src/linter.test.ts
Labels: scope: linter

#15596 feat(linter): combine tests to reduce total duration
  e2e/linter/src/linter.test.ts
Labels: scope: linter

#15462 feat(repo): make granular slack notifications when E2E tests fail
  .github/workflows/e2e-matrix.yml
  .github/workflows/e2e-windows.yml
  .github/workflows/npm-audit.yml
Labels: scope: repo

#15538 chore(repo): ensure correct flags for nightly e2e
  .github/workflows/e2e-matrix.yml
  .github/workflows/e2e-windows.yml
Labels: scope: repo

#13966 feat(core): use inputs to determine package dependencies
  docs/generated/devkit/nrwl_devkit.md
  docs/generated/packages/devkit/documents/nrwl_devkit.md
  packages/js/src/utils/package-json/update-package-json.spec.ts
  packages/js/src/utils/package-json/update-package-json.ts
  packages/next/src/executors/build/build.impl.ts
  packages/nx/src/hasher/hasher.ts
  packages/nx/src/utils/create-package-json.spec.ts
  packages/nx/src/utils/create-package-json.ts
  packages/webpack/src/plugins/generate-package-json-plugin.ts
Labels: type: feature, scope: core

#15647 fix(core): fix invalid yarn parser dependencies grouping key
  packages/nx/src/lock-file/yarn-parser.ts
Labels: scope: core

#15648 fix(core): handle missing package version on lockfile parsing
  packages/nx/src/hasher/hashing-impl.ts
  packages/nx/src/lock-file/npm-parser.ts
  packages/nx/src/lock-file/pnpm-parser.ts
  packages/nx/src/lock-file/yarn-parser.ts
Labels: scope: core

#15695 fix(repo): update @monodon/rust to 1.1.1
  package.json
  yarn.lock
Labels: scope: repo

#15683 feat(repo): improve yarn install caching for nightly
  .github/workflows/e2e-matrix.yml
  .github/workflows/e2e-windows.yml
Labels: scope: repo

#15678 docs(linter): add API information for enforce-module-boundaries
  docs/generated/manifests/menus.json
  docs/generated/manifests/packages.json
  docs/generated/packages-metadata.json
  docs/generated/packages/eslint-plugin-nx/documents/enforce-module-boundaries.md
  docs/generated/packages/eslint-plugin-nx/documents/overview.md
  docs/generated/packages/linter/documents/eslint-plugin-nx.md
  docs/generated/packages/linter/documents/overview.md
  docs/map.json
  docs/packages.json
  docs/shared/packages/linter/enforce-module-boundaries.md
  docs/shared/packages/linter/eslint-plugin-nx.md
  docs/shared/packages/linter/linter-plugin.md
  packages/eslint-plugin-nx/package.json
Labels: scope: linter

#15670 feat(linter): add override for noImportsOfLazyLoadedLibraries
  packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts
Labels: type: feature, scope: linter

#15681 fix(node): fix standalone linter setup
  e2e/linter/src/linter.test.ts
  packages/node/src/generators/application/application.ts
  packages/node/src/generators/e2e-project/e2e-project.ts
Labels: scope: node

#15736 feat(testing): add cypress-e2e-configuration generator
  docs/generated/manifests/menus.json
  docs/generated/manifests/packages.json
  docs/generated/packages-metadata.json
  docs/generated/packages/cypress/generators/cypress-e2e-configuration.json
  packages/cypress/docs/cypress-e2e-config-examples.md
  packages/cypress/generators.json
  packages/cypress/plugins/cypress-preset.ts
  packages/cypress/src/executors/cypress/cypress.impl.ts
  packages/cypress/src/generators/convert-tslint-to-eslint/convert-tslint-to-eslint.ts
  packages/cypress/src/generators/cypress-e2e-configuration/__snapshots__/cypress-e2e-configuration.spec.ts.snap
  packages/cypress/src/generators/cypress-e2e-configuration/cypress-e2e-configuration.spec.ts
  packages/cypress/src/generators/cypress-e2e-configuration/cypress-e2e-configuration.ts
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/__dir__/e2e/app.cy.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/__dir__/fixtures/example.json__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/__dir__/support/app.po.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/__dir__/support/commands.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/__dir__/support/e2e.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/cypress.config.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/tsconfig__tsFileExt__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__dir__/fixtures/example.json__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__dir__/integration/app.spec.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__dir__/plugins/index.js
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__dir__/support/app.po.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__dir__/support/commands.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__dir__/support/index.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/cypress.json
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/tsconfig__tsFileExt__
  packages/cypress/src/generators/cypress-e2e-configuration/schema.json
  packages/cypress/src/generators/cypress-project/cypress-project.ts
  packages/cypress/src/utils/add-linter.ts
Labels: scope: testing tools

#15899 fix(linter): remove outdated e2e test check
  e2e/linter/src/linter.test.ts
Labels: scope: linter

#15885 docs(linter): add docs on checkDynamicDependenciesExceptions flag
  docs/generated/packages/eslint-plugin-nx/documents/enforce-module-boundaries.md
  docs/shared/packages/linter/enforce-module-boundaries.md
Labels: type: docs

#15908 feat(repo): add nightly tests for several node versions
  .github/workflows/e2e-matrix.yml
  .github/workflows/e2e-windows.yml
Labels: scope: repo

#16013 docs(node): add recipe for deploying server to Fly.io
  docs/generated/manifests/menus.json
  docs/generated/manifests/recipes.json
  docs/generated/manifests/tags.json
  docs/map.json
  docs/shared/node-server-tutorial/1-code-generation.md
  docs/shared/recipes/deployment/node-server-fly-io.md
Labels: type: docs
