Repository nrwl/nx, pull requests merged in 2023-10, with the labels that each got.

#19406 fix(testing): install devkit when init playwright
  packages/playwright/src/generators/init/init.ts
Labels: scope: testing tools

#19484 docs(nx-cloud): update gitlab artifacts config for main job
  docs/shared/monorepo-ci-gitlab.md
Labels: type: docs

#19286 feat(react): Add federate-module generator
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx-api.json
  docs/generated/packages-metadata.json
  docs/generated/packages/react/generators/federate-module.json
  docs/shared/reference/sitemap.md
  e2e/react-core/src/react-module-federation.test.ts
  packages/react/generators.json
  packages/react/src/generators/federate-module/federate-module.spec.ts
  packages/react/src/generators/federate-module/federate-module.ts
  packages/react/src/generators/federate-module/lib/utils.spec.ts
  packages/react/src/generators/federate-module/lib/utils.ts
  packages/react/src/generators/federate-module/schema.d.ts
  packages/react/src/generators/federate-module/schema.json
  packages/react/src/generators/remote/remote.ts
  packages/react/src/module-federation/with-module-federation.ts
Labels: scope: react

#19512 fix(linter): fix validateDependenciesSectionExistance fixer
  packages/eslint-plugin/src/rules/dependency-checks.spec.ts
  packages/eslint-plugin/src/rules/dependency-checks.ts
Labels: scope: linter

#19474 fix(react): Add missing Nx Welcome for styled-jsx
  e2e/react-core/src/react.test.ts
  packages/react/src/generators/application/files/style-styled-jsx/src/app/__fileName__.tsx__tmpl__
Labels: scope: react

#19566 feat(react): Add support for promise based remotes
  e2e/react-core/src/react-module-federation.test.ts
  packages/webpack/src/utils/module-federation/remotes.ts
Labels: scope: react

#19585 fix(nextjs): Add missing environment variables for Nx 18 environment variables
  packages/next/plugins/with-nx.ts
Labels: scope: nextjs

#19587 fix(nextjs): Library generator should not add cypress dependency
  packages/next/src/generators/library/library.spec.ts
  packages/next/src/generators/library/library.ts
Labels: scope: nextjs

#19605 docs(nx-cloud): update the enterprise auth docs
  docs/nx-cloud/private/auth-bitbucket.md
  docs/nx-cloud/private/auth-github.md
  docs/nx-cloud/private/auth-gitlab.md
  docs/nx-cloud/private/auth-saml.md
  docs/nx-cloud/private/images/github_auth_step_5.png
  docs/nx-cloud/private/images/gitlab_step_1.png
  docs/nx-cloud/private/images/gitlab_step_2.png
  docs/nx-cloud/private/images/gitlab_step_3.png
  docs/nx-cloud/private/images/gitlab_step_4.png
  docs/nx-cloud/private/images/gitlab_step_5.png
  docs/nx-cloud/private/images/saml/azure_8.png
  docs/nx-cloud/private/images/saml/okta_4.png
Labels: scope: docs, scope: nx-cloud

#19626 chore(repo): use latest circleci rust image
  .circleci/config.yml
Labels: scope: repo

#19642 docs(misc): Add federate module recipe
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/map.json
  docs/shared/recipes/module-federation/federate-a-module.md
  docs/shared/reference/sitemap.md
Labels: type: docs, scope: docs

#19674 fix(linter): handle string extends property in config
  packages/eslint/src/generators/utils/eslint-file.spec.ts
  packages/eslint/src/generators/utils/eslint-file.ts
Labels: scope: linter

#18937 fix(core): ensure CNW works without .yarnrc with custom registry
  packages/create-nx-workspace/src/utils/package-manager.ts
  packages/devkit/src/tasks/install-packages-task.ts
  packages/nx/src/command-line/migrate/command-object.ts
Labels: scope: core

#19720 fix(react): Error when invalid path is provided to federate-module generator
  docs/generated/packages/react/generators/federate-module.json
  packages/angular/src/generators/federate-module/federate-module.ts
  packages/react/src/generators/federate-module/federate-module.spec.ts
  packages/react/src/generators/federate-module/federate-module.ts
  packages/react/src/generators/federate-module/schema.json
Labels: scope: react, scope: angular

#19666 docs(misc): Add Manage Library Versions recipe
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx.json
  docs/map.json
  docs/shared/guides/module-federation/manage-library-versions-with-module-federation.md
  docs/shared/guides/module-federation/nx-library-version.png
  docs/shared/guides/module-federation/shared-api.png
  docs/shared/reference/sitemap.md
Labels: scope: docs

#19649 docs(linter): update docs for eslint package
  CODEOWNERS
  docs/generated/manifests/menus.json
  docs/generated/manifests/nx-api.json
  docs/generated/packages-metadata.json
  docs/generated/packages/eslint-plugin/documents/dependency-checks.md
  docs/generated/packages/eslint-plugin/documents/overview.md
  docs/generated/packages/eslint/documents/overview.md
  docs/generated/packages/eslint/executors/lint.json
  docs/generated/packages/eslint/generators/convert-to-flat-config.json
  docs/generated/packages/eslint/generators/workspace-rule.json
  docs/generated/packages/eslint/generators/workspace-rules-project.json
  docs/map.json
  docs/shared/core-features/automate-updating-dependencies.md
  docs/shared/packages/eslint/dependency-checks.md
  docs/shared/packages/eslint/enforce-module-boundaries.md
  docs/shared/packages/eslint/eslint-plugin.md
  docs/shared/packages/eslint/eslint.md
  docs/shared/recipes/tips-n-tricks/migrating-to-flat-eslint.md
  docs/shared/reference/sitemap.md
  graph/client-e2e/src/fixtures/nx-examples-task-inputs.json
  graph/client/src/assets/task-inputs/e2e-affected.json
  graph/client/src/assets/task-inputs/e2e.json
  nx-dev/nx-dev-e2e/src/packages.spec.ts
  nx-dev/nx-dev/redirect-rules.js
  packages/eslint/docs/eslint-examples.md
  packages/eslint/docs/workspace-rule-examples.md
  packages/eslint/src/migrations/update-17-0-0-rename-to-eslint/update-17-0-0-rename-to-eslint.ts
  packages/storybook/src/generators/configuration/__snapshots__/configuration.spec.ts.snap
  packages/storybook/src/generators/configuration/test-configs/root-workspace-configuration.json
  packages/storybook/src/generators/configuration/test-configs/various-projects.json
  packages/storybook/src/utils/test-configs/different-target-variations.json
  packages/storybook/src/utils/test-configs/executor-context.json
  packages/vite/src/generators/configuration/__snapshots__/configuration.spec.ts.snap
  packages/vite/src/utils/test-files/angular-project.config.json
  packages/vite/src/utils/test-files/react-lib-non-buildable-jest.json
  packages/vite/src/utils/test-files/react-lib-non-buildable-vitest.json
  packages/vite/src/utils/test-files/react-mixed-project.config.json
  packages/vite/src/utils/test-files/react-project.config.json
  packages/vite/src/utils/test-files/web-project.config.json
  scripts/documentation/package-schemas/package-metadata.ts
Labels: scope: linter

#19800 fix(core): ensure require.resolve('nx') resolves correctly
  packages/angular/src/builders/module-federation-dev-server/module-federation-dev-server.impl.ts
  packages/react/src/executors/module-federation-dev-server/module-federation-dev-server.impl.ts
Labels: scope: react

#19829 feat(nx-cloud): update agents yaml to support triggers
  .nx/workflows/agents.yaml
Labels: scope: nx-cloud

#19833 fix(nextjs): Custom server should work on fresh applications
  packages/next/plugins/with-nx.ts
  packages/next/src/generators/custom-server/custom-server.ts
Labels: scope: nextjs

#19859 fix(js): should respect vitest test environment
  packages/js/src/generators/library/library.spec.ts
  packages/js/src/generators/library/library.ts
  packages/vite/src/utils/generator-utils.ts
Labels: scope: js

#19882 fix(react): Update types version so that there is no mismatch when using yarn
  packages/react/src/utils/versions.ts
Labels: scope: react
