Repository nrwl/nx, pull requests merged in 2023-05, with the labels that each got.

#16680 fix(testing): add --quiet cypress executor option
  docs/generated/packages/cypress/executors/cypress.json
  packages/cypress/src/executors/cypress/cypress.impl.ts
  packages/cypress/src/executors/cypress/schema.json
Labels: scope: testing tools

#16702 fix(node): ensure that bundlers for node is webpack/esbuild
  docs/generated/packages/workspace/generators/preset.json
  packages/node/src/generators/application/application.ts
  packages/workspace/src/generators/new/generate-preset.ts
  packages/workspace/src/generators/preset/preset.ts
  packages/workspace/src/generators/preset/schema.d.ts
  packages/workspace/src/generators/preset/schema.json
Labels: scope: node, scope: bundlers

#16703 fix(expo): expo generator on windows
  packages/expo/src/generators/application/lib/normalize-options.ts
Labels: scope: react-native

#16724 feat(core): bump version of @nrwl/ci workflow
  docs/shared/monorepo-ci-github-actions.md
  packages/workspace/src/generators/ci-workflow/__snapshots__/ci-workflow.spec.ts.snap
  packages/workspace/src/generators/ci-workflow/files/github/.github/workflows/__workflowFileName__.yml__tmpl__
Labels: type: feature, scope: core

#16739 docs(core): add example of custom/ejected github workflow
  docs/shared/monorepo-ci-github-actions.md
Labels: type: docs

#16743 feat(linter): support custom build targets for buildability check
  packages/eslint-plugin/src/rules/enforce-module-boundaries.spec.ts
  packages/eslint-plugin/src/rules/enforce-module-boundaries.ts
  packages/eslint-plugin/src/utils/runtime-lint-utils.ts
Labels: type: bug, scope: linter

#10414 feat(node): allow executing esm compiled scripts
  e2e/node/src/node.test.ts
  packages/js/src/executors/node/node-with-require-overrides.ts
Labels: PR status: tests needed

#16822 fix(react): bump migration version
  packages/react/migrations.json
  packages/react/src/migrations/update-16-2-0-remove-package/update-16-2-0-remove-package.spec.ts
  packages/react/src/migrations/update-16-2-0-remove-package/update-16-2-0-remove-package.ts
  packages/web/migrations.json
  packages/web/src/migrations/update-16-2-0-remove-packages/update-16-2-0-remove-packages.spec.ts
  packages/web/src/migrations/update-16-2-0-remove-packages/update-16-2-0-remove-packages.ts
Labels: scope: react

#16858 feat(linter): allow ESLint Flat Config to be opted into manually
  packages/linter/src/executors/eslint/lint.impl.spec.ts
  packages/linter/src/executors/eslint/lint.impl.ts
  packages/linter/src/executors/eslint/utility/eslint-utils.spec.ts
  packages/linter/src/executors/eslint/utility/eslint-utils.ts
Labels: scope: linter

#16681 fix(js): info about jest global setup/teardown + swc
  docs/generated/packages/jest/documents/overview.md
  docs/shared/packages/jest/jest-plugin.md
  packages/js/src/generators/library/__snapshots__/library.spec.ts.snap
  packages/js/src/generators/library/files/jest-config/jest.config.__ext__
Labels: type: docs, scope: testing tools, scope: js

#16902 fix(repo): ignore failed daemon reset on e2e tests
  e2e/utils/create-project-utils.ts
Labels: type: bug, scope: repo

#16864 chore(repo): enable enforce-module-boundaries on nx repo
  .eslintrc.json
  graph/client-e2e/src/globals.d.ts
  graph/client/src/app/feature-projects/machines/interfaces.ts
  graph/client/src/app/feature-projects/machines/project-graph.spec.ts
  graph/client/src/app/feature-projects/machines/selectors.ts
  graph/client/src/app/feature-projects/project-list.tsx
  graph/client/src/app/feature-projects/projects-sidebar.tsx
  graph/client/src/app/feature-tasks/task-list.tsx
  graph/client/src/app/feature-tasks/tasks-sidebar.tsx
  graph/client/src/app/fetch-project-graph-service.ts
  graph/client/src/app/hooks/use-environment-config.ts
  graph/client/src/app/interfaces.ts
  graph/client/src/app/local-project-graph-service.ts
  graph/client/src/app/machines/interfaces.ts
  graph/client/src/app/mock-project-graph-service.ts
  graph/client/src/app/routes.tsx
  graph/client/src/app/util.ts
  graph/client/src/globals.d.ts
  graph/ui-components/.storybook/preview.js
  graph/ui-graph/src/lib/interfaces.ts
  graph/ui-graph/src/lib/nx-project-graph-viz.tsx
  graph/ui-graph/src/lib/nx-task-graph-viz.tsx
  graph/ui-graph/src/lib/util-cytoscape/project-edge.ts
  graph/ui-graph/src/lib/util-cytoscape/project-node.ts
  graph/ui-graph/src/lib/util-cytoscape/project-traversal-graph.ts
  graph/ui-graph/src/lib/util-cytoscape/render-graph.ts
  graph/ui-graph/src/lib/util-cytoscape/task-edge.ts
  graph/ui-graph/src/lib/util-cytoscape/task-node.ts
  graph/ui-graph/src/lib/util-cytoscape/task-traversal.graph.ts
  graph/ui-graph/src/lib/util.ts
  nx-dev/nx-dev/pages/packages/[name]/documents/index.tsx
  nx-dev/nx-dev/pages/packages/[name]/executors/index.tsx
  nx-dev/nx-dev/pages/packages/[name]/generators/index.tsx
  nx-dev/nx-dev/pages/packages/rspack/documents/index.tsx
  nx-dev/nx-dev/pages/packages/rspack/executors/index.tsx
  nx-dev/nx-dev/pages/packages/rspack/generators/index.tsx
  nx-dev/nx-dev/pages/plugins/registry.tsx
  nx-dev/ui-common/src/lib/sidebar-container.tsx
  packages/angular/src/generators/remote/remote.spec.ts
  packages/devkit/src/utils/get-workspace-layout.spec.ts
  packages/js/src/migrations/update-13-8-5/update-swcrc.spec.ts
  packages/nx/src/utils/package-manager.spec.ts
  packages/react/src/migrations/update-13-0-0/webpack5-changes-utils.spec.ts
  packages/storybook/src/migrations/update-14-0-0/migrate-stories-to-6-2/migrate-stories-to-6-2.spec.ts
  packages/workspace/src/generators/new/generate-workspace-files.spec.ts
  packages/workspace/src/generators/remove/lib/remove-project.spec.ts
  packages/workspace/src/migrations/update-13-6-0/remove-old-task-runner-options.spec.ts
  tsconfig.base.json
Labels: type: feature, scope: repo, scope: linter

#16651 fix(testing): prevent ct and e2e generators from overwriting configs
  docs/generated/packages/cypress/generators/cypress-component-configuration.json
  e2e/cypress/src/cypress.test.ts
  packages/angular/src/generators/cypress-component-configuration/__snapshots__/cypress-component-configuration.spec.ts.snap
  packages/angular/src/generators/cypress-component-configuration/cypress-component-configuration.spec.ts
  packages/angular/src/generators/cypress-component-configuration/cypress-component-configuration.ts
  packages/angular/src/generators/cypress-component-configuration/files/cypress.config.ts__tpl__
  packages/angular/src/generators/cypress-component-configuration/files/cypress/support/commands.ts__tpl__
  packages/cypress/migrations.json
  packages/cypress/src/generators/base-setup/base-setup.ts
  packages/cypress/src/generators/base-setup/files/__directory__/fixtures/example.json
  packages/cypress/src/generators/base-setup/files/__directory__/support/commands.ts__ext__
  packages/cypress/src/generators/base-setup/files/__directory__/tsconfig.json
  packages/cypress/src/generators/base-setup/files/cypress.config.ts__ext__
  packages/cypress/src/generators/cypress-component-configuration/cypress-component-configuration.spec.ts
  packages/cypress/src/generators/cypress-component-configuration/cypress-component-configuration.ts
  packages/cypress/src/generators/cypress-component-configuration/files/__directory__/support/component-index.html
  packages/cypress/src/generators/cypress-component-configuration/files/__directory__/support/component.ts__ext__
  packages/cypress/src/generators/cypress-component-configuration/files/cypress/support/commands.ts__ext__
  packages/cypress/src/generators/cypress-component-configuration/files/cypress/tsconfig.cy.json
  packages/cypress/src/generators/cypress-component-configuration/schema.d.ts
  packages/cypress/src/generators/cypress-component-configuration/schema.json
  packages/cypress/src/generators/cypress-e2e-configuration/cypress-e2e-configuration.spec.ts
  packages/cypress/src/generators/cypress-e2e-configuration/cypress-e2e-configuration.ts
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/__directory__/e2e/app.cy.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/__directory__/support/app.po.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/__directory__/support/e2e.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/cypress.config.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v10/tsconfig__tsFileExt__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__dir__/fixtures/example.json__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__dir__/support/commands.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__directory__/fixtures/example.json__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__directory__/integration/app.spec.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__directory__/plugins/index.js
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__directory__/support/app.po.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__directory__/support/commands.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__directory__/support/index.ts__tmpl__
  packages/cypress/src/generators/cypress-e2e-configuration/files/v9/__directory__/tsconfig.json
  packages/cypress/src/migrations/update-16-2-0/update-cy-tsconfig.spec.ts
  packages/cypress/src/migrations/update-16-2-0/update-cy-tsconfig.ts
  packages/cypress/src/utils/config.spec.ts
  packages/cypress/src/utils/config.ts
  packages/next/src/generators/cypress-component-configuration/__snapshots__/cypress-component-configuration.spec.ts.snap
  packages/next/src/generators/cypress-component-configuration/cypress-component-configuration.spec.ts
  packages/next/src/generators/cypress-component-configuration/cypress-component-configuration.ts
  packages/next/src/generators/cypress-component-configuration/files/cypress.config.ts__tpl__
  packages/next/src/generators/cypress-component-configuration/files/cypress/support/styles.ct.css__tpl__
  packages/react/plugins/component-testing/index.ts
  packages/react/src/generators/cypress-component-configuration/__snapshots__/cypress-component-configuration.spec.ts.snap
  packages/react/src/generators/cypress-component-configuration/cypress-component-configuration.spec.ts
  packages/react/src/generators/cypress-component-configuration/files/cypress.config.ts__tpl__
  packages/react/src/generators/cypress-component-configuration/files/cypress/support/commands.ts__tpl__
  packages/react/src/generators/cypress-component-configuration/lib/add-files.ts
Labels: scope: testing tools

#16971 fix(react): add ts extension to tailwindcss utility glob
  packages/react/tailwind.ts
Labels: scope: react

#16926 feat(core): include entire external node dependency tree in hash
  packages/nx/src/hasher/hasher.spec.ts
  packages/nx/src/hasher/hasher.ts
Labels: type: feature, scope: core

#16903 feat(core): support third-party packages for surgical hashTarget hashing
  packages/nx/src/hasher/hasher.ts
Labels: type: feature, scope: core

#16859 fix(core): resolve nx against command root if workspace not provided
  packages/nx/bin/nx.ts
Labels: type: bug, scope: core

#16922 docs(core): community page
  nx-dev/nx-dev/pages/community.tsx
  nx-dev/nx-dev/public/images/champions/brandon-roberts.webp
  nx-dev/nx-dev/public/images/champions/devin-shoemaker.webp
  nx-dev/nx-dev/public/images/champions/dominik-pieper.webp
  nx-dev/nx-dev/public/images/champions/issam-guissouma.webp
  nx-dev/nx-dev/public/images/champions/kate-sky.webp
  nx-dev/nx-dev/public/images/champions/lara-newsom.webp
  nx-dev/nx-dev/public/images/champions/lars-gyrup-brink-nielsen.webp
  nx-dev/nx-dev/public/images/champions/santosh-yadav.webp
  nx-dev/nx-dev/public/images/champions/shai-reznik.webp
  nx-dev/nx-dev/public/images/champions/william-ghelfi.webp
  nx-dev/nx-dev/public/images/champions/younes-jaaidi.webp
  nx-dev/ui-common/src/index.ts
  nx-dev/ui-common/src/lib/champion-card.tsx
  nx-dev/ui-common/src/lib/champion-perks.tsx
Labels: type: docs

#17007 docs(core): update Santosh contact info
  nx-dev/nx-dev/pages/community.tsx
Labels: type: docs

#17022 docs(repo): typo fix on nx enterprise
  docs/shared/monorepo-nx-enterprise.md
Labels: type: docs

#16916 feat(core): add commandExternalDependencies hash input
  docs/shared/reference/project-configuration.md
  packages/nx/schemas/nx-schema.json
  packages/nx/schemas/project-schema.json
  packages/nx/src/config/workspace-json-project-json.ts
  packages/nx/src/hasher/hasher.spec.ts
  packages/nx/src/hasher/hasher.ts
Labels: type: feature, scope: core

#16896 feat(nextjs): Use next.js cli for build and serve targets
  docs/generated/packages/next/executors/build.json
  docs/generated/packages/next/executors/export.json
  docs/generated/packages/next/executors/server.json
  e2e/next/src/utils.ts
  packages/next/executors.json
  packages/next/package.json
  packages/next/plugins/with-nx.ts
  packages/next/src/executors/build/build.impl.ts
  packages/next/src/executors/build/schema.json
  packages/next/src/executors/export/export.impl.ts
  packages/next/src/executors/server/custom-server.impl.ts
  packages/next/src/executors/server/schema.json
  packages/next/src/executors/server/server.impl.ts
  packages/next/src/utils/config.ts
  packages/next/src/utils/create-cli-options.ts
  packages/next/src/utils/types.ts
Labels: scope: nextjs

#17069 feat(nextjs): Add --turbo support
  docs/generated/packages/next/executors/server.json
  e2e/next/src/next.test.ts
  packages/next/src/executors/server/schema.json
  packages/next/src/executors/server/server.impl.ts
  packages/next/src/utils/types.ts
Labels: scope: nextjs

#17087 chore(testing): skip nextjs ct/e2e test
  e2e/cypress/src/cypress.test.ts
Labels: scope: testing tools

#17059 feat(nx-dev): add watch to automatically sync docs to nx-dev when developing locally
  nx-dev/nx-dev/copy-docs.js
  nx-dev/nx-dev/next.config.js
  nx-dev/nx-dev/project.json
  nx.json
Labels: type: docs

#16917 fix(web): provide free port to http-server
  packages/web/package.json
  packages/web/src/executors/file-server/file-server.impl.ts
Labels: scope: testing tools

#17197 docs(core): add champions
  nx-dev/nx-dev/lib/champions.ts
  nx-dev/nx-dev/pages/community.tsx
  nx-dev/nx-dev/public/images/champions/jay-bell.webp
  nx-dev/nx-dev/public/images/champions/jorge-cano.webp
  nx-dev/nx-dev/public/images/champions/preston-lamb.webp
  nx-dev/nx-dev/public/images/champions/tine-kondo.webp
Labels: type: docs

#17148 feat(testing): add --randomize flag for jest
  docs/generated/packages/jest/executors/jest.json
  packages/jest/src/executors/jest/jest.impl.ts
  packages/jest/src/executors/jest/schema.d.ts
  packages/jest/src/executors/jest/schema.json
Labels: scope: testing tools

#16928 feat(js): add verdaccio executor
  docs/generated/manifests/menus.json
  docs/generated/manifests/packages.json
  docs/generated/packages-metadata.json
  docs/generated/packages/js/executors/verdaccio.json
  docs/generated/packages/js/generators/setup-verdaccio.json
  packages/js/executors.json
  packages/js/generators.json
  packages/js/package.json
  packages/js/src/executors/verdaccio/compat.ts
  packages/js/src/executors/verdaccio/schema.d.ts
  packages/js/src/executors/verdaccio/schema.json
  packages/js/src/executors/verdaccio/verdaccio.impl.ts
  packages/js/src/generators/init/init.ts
  packages/js/src/generators/library/library.ts
  packages/js/src/generators/setup-verdaccio/files/config.yml
  packages/js/src/generators/setup-verdaccio/files/htpasswd
  packages/js/src/generators/setup-verdaccio/generator.spec.ts
  packages/js/src/generators/setup-verdaccio/generator.ts
  packages/js/src/generators/setup-verdaccio/schema.d.ts
  packages/js/src/generators/setup-verdaccio/schema.json
  packages/js/src/utils/versions.ts
Labels: type: docs

#17147 fix(testing): make sure new tsconfig exists before adding ref
  packages/cypress/src/migrations/update-16-2-0/update-cy-tsconfig.ts
Labels: scope: testing tools

#17149 feat(testing): support cypress reporterOptions as objects
  docs/generated/packages/cypress/executors/cypress.json
  packages/cypress/src/executors/cypress/cypress.impl.ts
  packages/cypress/src/executors/cypress/schema.json
Labels: scope: testing tools

#17225 docs(core): increase run syntax svg
  docs/shared/images/run-target-syntax.svg
Labels: type: docs

#17320 fix(node): Nightly failures
  packages/nest/src/generators/library/lib/add-exports-to-barrel.ts
Labels: scope: node
