Repository nrwl/nx, pull requests merged in 2023-11, with the labels that each got.

#19977 fix(detox): Update jest transform to point to correct tsconfig
  packages/detox/src/generators/application/files/app/jest.config.json.template
Labels: scope: react-native

#19979 fix(module-federation): refactor federate-module generator
  docs/generated/packages/angular/generators/federate-module.json
  docs/generated/packages/react/generators/federate-module.json
  docs/shared/recipes/module-federation/federate-a-module.md
  e2e/angular-core/src/module-federation.test.ts
  e2e/react-core/src/react-module-federation.test.ts
  packages/angular/src/generators/federate-module/schema.json
  packages/react/src/generators/federate-module/schema.json
Labels: scope: react, scope: angular

#20017 fix(linter): migrate custom ignorePath to flat config
  packages/eslint/src/generators/convert-to-flat-config/__snapshots__/generator.spec.ts.snap
  packages/eslint/src/generators/convert-to-flat-config/converters/json-converter.spec.ts
  packages/eslint/src/generators/convert-to-flat-config/converters/json-converter.ts
  packages/eslint/src/generators/convert-to-flat-config/generator.spec.ts
  packages/eslint/src/generators/convert-to-flat-config/generator.ts
Labels: scope: linter

#20055 docs(core): fix azure last successful commit logic
  docs/shared/monorepo-ci-azure.md
Labels: type: docs

#20018 fix(linter): do not expect project to have flat eslint config
  e2e/eslint/src/linter.test.ts
  packages/eslint/src/executors/lint/lint.impl.spec.ts
  packages/eslint/src/executors/lint/lint.impl.ts
Labels: scope: linter

#20053 cleanup(linter): remove unused imports
  packages/eslint-plugin/src/rules/dependency-checks.ts
  packages/eslint-plugin/src/rules/enforce-module-boundaries.ts
Labels: scope: linter

#20169 chore(repo): use new launch template syntax
  .circleci/config.yml
  .nx/workflows/agents.yaml
Labels: scope: repo

#20024 feat(module-federation): Add react support for dynamic federation
  docs/generated/packages/react/generators/host.json
  docs/generated/packages/react/generators/remote.json
  e2e/react-core/src/react-module-federation.test.ts
  packages/react/mf/dynamic-federation.ts
  packages/react/mf/index.ts
  packages/react/src/generators/host/files/common/src/app/__fileName__.tsx__tmpl__
  packages/react/src/generators/host/files/module-federation-ssr-ts/module-federation.server.config.ts__tmpl__
  packages/react/src/generators/host/files/module-federation-ssr/module-federation.server.config.js__tmpl__
  packages/react/src/generators/host/files/module-federation-ts/module-federation.config.ts__tmpl__
  packages/react/src/generators/host/files/module-federation-ts/src/main.ts__tmpl__
  packages/react/src/generators/host/files/module-federation/module-federation.config.js__tmpl__
  packages/react/src/generators/host/files/module-federation/src/main.ts__tmpl__
  packages/react/src/generators/host/host.ts
  packages/react/src/generators/host/lib/add-module-federation-files.ts
  packages/react/src/generators/host/lib/setup-ssr-for-host.ts
  packages/react/src/generators/host/schema.d.ts
  packages/react/src/generators/host/schema.json
  packages/react/src/generators/remote/__snapshots__/remote.spec.ts.snap
  packages/react/src/generators/remote/files/module-federation-ts/module-federation.config.ts__tmpl__
  packages/react/src/generators/remote/files/module-federation/module-federation.config.js__tmpl__
  packages/react/src/generators/remote/lib/add-remote-to-dynamic-host.ts
  packages/react/src/generators/remote/remote.ts
  packages/react/src/generators/remote/schema.d.ts
  packages/react/src/generators/remote/schema.json
  packages/react/src/rules/update-module-federation-project.ts
Labels: scope: react

#20241 fix(nextjs): read nextConfig path correctly when provided as an option.
  packages/next/src/executors/build/lib/create-next-config-file.ts
Labels: scope: nextjs

#20263 docs(nx-dev): fix incorrect link to medium instead of dev.to
  nx-dev/nx-dev/pages/blog/index.tsx
Labels: type: docs

#20022 feat(linter): support yaml for flat config conversion
  packages/eslint/package.json
  packages/eslint/src/generators/convert-to-flat-config/__snapshots__/generator.spec.ts.snap
  packages/eslint/src/generators/convert-to-flat-config/converters/json-converter.spec.ts
  packages/eslint/src/generators/convert-to-flat-config/converters/json-converter.ts
  packages/eslint/src/generators/convert-to-flat-config/generator.spec.ts
  packages/eslint/src/generators/convert-to-flat-config/generator.ts
  packages/eslint/src/generators/init/global-eslint-config.ts
  packages/eslint/src/generators/lint-project/lint-project.ts
  packages/eslint/src/generators/utils/flat-config/ast-utils.ts
  packages/next/src/generators/application/lib/add-linting.spec.ts
Labels: scope: linter

#20061 fix(core): ensure plugin testing uses correct pm for install
  packages/plugin/src/utils/testing-utils/async-commands.ts
  packages/plugin/src/utils/testing-utils/commands.ts
  packages/plugin/src/utils/testing-utils/nx-project.ts
Labels: scope: core

#20431 docs(misc): Update Svelte recipe to use ts-standalone preset
  docs/shared/recipes/add-stack/add-svelte.md
Labels: scope: docs

#20264 feat(linter): add create-nodes plugin
  e2e/eslint/src/linter.test.ts
  packages/devkit/src/utils/replace-project-configuration-with-plugin.ts
  packages/eslint/package.json
  packages/eslint/plugin.ts
  packages/eslint/src/generators/init/__snapshots__/init.spec.ts.snap
  packages/eslint/src/generators/init/init.spec.ts
  packages/eslint/src/generators/init/init.ts
  packages/eslint/src/generators/lint-project/lint-project.ts
  packages/eslint/src/generators/utils/eslint-file.spec.ts
  packages/eslint/src/generators/utils/eslint-file.ts
  packages/eslint/src/migrations/update-15-0-0/add-eslint-inputs.spec.ts
  packages/eslint/src/migrations/update-15-0-0/add-eslint-inputs.ts
  packages/eslint/src/migrations/update-15-7-1/add-eslint-ignore.ts
  packages/eslint/src/plugins/plugin.spec.ts
  packages/eslint/src/plugins/plugin.ts
  packages/eslint/src/utils/config-file.ts
Labels: scope: linter
