Repository nrwl/nx, pull requests merged in 2024-04, with the labels that each got.

#22621 fix(js): update jest snapshot after vite-plugin-dts bump
  packages/js/src/generators/library/__snapshots__/library.spec.ts.snap
Labels: scope: js

#22654 docs(nx-cloud): remove server api reference
  docs/generated/manifests/ci.json
  docs/generated/manifests/menus.json
  docs/map.json
  docs/nx-cloud/reference/server-api.md
  docs/shared/reference/sitemap.md
  nx-dev/nx-dev-e2e/src/nx-cloud-documentation.spec.ts
Labels: type: docs

#22709 fix(nextjs): Adding tailwind should work when creating an app OOTB
  docs/generated/packages/next/generators/application.json
  packages/next/src/generators/application/application.ts
  packages/next/src/generators/application/lib/create-application-files.ts
  packages/next/src/generators/application/lib/normalize-options.ts
  packages/next/src/generators/application/schema.json
  packages/react/src/generators/setup-tailwind/lib/add-tailwind-style-imports.ts
Labels: scope: nextjs

#22888 docs(nx-cloud): add info about start-ci-run and --stop-agents-after u…
  docs/nx-cloud/reference/nx-cloud-cli.md
Labels: type: docs, scope: nx-cloud

#22580 fix(core): fix pnpm install order on ci workflows
  packages/workspace/src/generators/ci-workflow/__snapshots__/ci-workflow.spec.ts.snap
  packages/workspace/src/generators/ci-workflow/files/azure/azure-pipelines.yml__tmpl__
  packages/workspace/src/generators/ci-workflow/files/bitbucket-pipelines/bitbucket-pipelines.yml__tmpl__
  packages/workspace/src/generators/ci-workflow/files/circleci/.circleci/config.yml__tmpl__
  packages/workspace/src/generators/ci-workflow/files/github/.github/workflows/__workflowFileName__.yml__tmpl__
  packages/workspace/src/generators/ci-workflow/files/gitlab/.gitlab-ci.yml__tmpl__
Labels: type: bug, scope: core

#23009 fix(core): nxComponentTestingPreset should not expose bundler option
  packages/angular/plugins/component-testing.ts
  packages/cypress/plugins/cypress-preset.ts
Labels: scope: testing tools

#23042 docs(core): Fix the '>' position when rendering multiline commands
  nx-dev/ui-fence/src/lib/fences/terminal-output.tsx
Labels: scope: docs
