Repository nrwl/nx, pull requests merged in 2024-11, with the labels that each got.

#28734 fix(nextjs): Formatting for pages
  packages/next/src/generators/application/files/app/page.tsx__tmpl__
  packages/next/src/generators/application/files/common/specs/__fileName__.spec.tsx__tmpl__
  packages/next/src/generators/application/files/pages/__fileName__.tsx__tmpl__
  packages/react/src/generators/application/files/base-rspack/src/main.tsx__tmpl__
  packages/react/src/generators/application/lib/create-application-files.ts
Labels: scope: nextjs

#28735 feat(nx-cloud): configure import paths for light client when running …
  packages/nx/src/command-line/login/login.ts
  packages/nx/src/command-line/logout/logout.ts
Labels: scope: nx-cloud

#28650 fix(release): support workspace root as a subdirectory of git root
  packages/nx/src/command-line/release/utils/git.ts
Labels: scope: release

#28886 fix(nx-dev): update course API to ignore system OS Metadata file
  nx-dev/data-access-courses/src/lib/courses.api.ts
Labels: scope: docs

#28961 docs(nx-cloud): add cipe project graph recipe
  docs/generated/manifests/ci.json
  docs/generated/manifests/menus.json
  docs/map.json
  docs/nx-cloud/recipes/cipe-affected-project-graph-break-up-ui.png
  docs/nx-cloud/recipes/cipe-affected-project-graph-button-affected.png
  docs/nx-cloud/recipes/cipe-affected-project-graph-button-tasks.png
  docs/nx-cloud/recipes/cipe-affected-project-graph-every-projects.png
  docs/nx-cloud/recipes/cipe-affected-project-graph-every-tasks.png
  docs/nx-cloud/recipes/cipe-affected-project-graph-nav-item.png
  docs/nx-cloud/recipes/cipe-affected-project-graph-tooltip-affected.png
  docs/nx-cloud/recipes/cipe-affected-project-graph-tooltip-tasks.png
  docs/nx-cloud/recipes/cipe-affected-project-graph.md
  docs/shared/reference/sitemap.md
Labels: type: docs

#29066 fix(nextjs): ensure next apps config is correctly checked when using jest
  packages/jest/src/generators/configuration/lib/update-tsconfig.ts
Labels: scope: nextjs

#29068 fix(angular): ngrx-root-store generator check ngModule path
  packages/angular/src/generators/ngrx-root-store/lib/normalize-options.ts
Labels: scope: angular

#29084 fix(nest): Fix generators (guard, interceptor etc...) path to not duplicate when provided
  docs/generated/packages/nest/generators/guard.json
  docs/generated/packages/nest/generators/interceptor.json
  packages/nest/src/generators/guard/schema.json
  packages/nest/src/generators/interceptor/schema.json
  packages/nest/src/generators/utils/normalize-options.ts
Labels: scope: node

#29110 fix(nest): update project config to enable artifacts to be built as dev
  packages/nest/src/generators/application/application.spec.ts
  packages/node/src/generators/application/application.ts
Labels: scope: node
