Repository nrwl/nx, pull requests merged in 2024-03, with the labels that each got.

#22079 fix(nextjs): Add spec files when creating a next app
  e2e/next-core/src/next-appdir.test.ts
  packages/next/src/generators/application/__snapshots__/application.spec.ts.snap
  packages/next/src/generators/application/application.spec.ts
  packages/next/src/generators/application/files/app/page.tsx__tmpl__
  packages/next/src/generators/application/files/common/specs/__fileName__.spec.tsx__tmpl__
  packages/next/src/generators/application/lib/create-application-files.ts
Labels: scope: nextjs

#21998 fix(nextjs): avoid path error on dev server creation
  packages/next/src/executors/server/server.impl.ts
Labels: scope: nextjs

#22170 fix(nextjs): Adding styles to nextjs cypress should not fail.
  e2e/next-extensions/src/next-component-tests.test.ts
  packages/cypress/src/generators/component-configuration/component-configuration.ts
  packages/cypress/src/generators/component-configuration/files/__directory__/support/component-index.html
  packages/cypress/src/generators/component-configuration/schema.d.ts
  packages/next/src/generators/cypress-component-configuration/cypress-component-configuration.ts
Labels: scope: nextjs

#22175 fix(testing): minor adjustment to the config generation template
  packages/playwright/src/generators/configuration/files/playwright.config.ts.template
Labels: scope: testing tools

#22190 fix(nextjs): Surface error codes when build is interrupted by signals SIGINT, SIGTERM etc...
  packages/next/src/executors/build/build.impl.ts
Labels: scope: nextjs

#22224 fix(angular): Module federation with Crystal enabled.
  packages/angular/src/utils/mf/with-module-federation-ssr.ts
  packages/angular/src/utils/mf/with-module-federation.ts
Labels: scope: angular

#22338 docs(nextjs): Fix tabs for Nx 18
  docs/generated/packages/next/documents/overview.md
  docs/shared/packages/next/plugin-overview.md
Labels: scope: docs

#22452 docs(nx-cloud): add basic Azure DevOps setup recipe
  docs/generated/manifests/ci.json
  docs/generated/manifests/menus.json
  docs/map.json
  docs/nx-cloud/set-up/access-vcs-setup.webp
  docs/nx-cloud/set-up/add-azure-devops-repository.webp
  docs/nx-cloud/set-up/add-bitbucket-cloud-repository.webp
  docs/nx-cloud/set-up/add-gitlab-repository.webp
  docs/nx-cloud/set-up/azure-devops.md
  docs/nx-cloud/set-up/find-gitlab-project-id.png
  docs/nx-cloud/set-up/find-gitlab-project-id.webp
  docs/nx-cloud/set-up/github.md
  docs/nx-cloud/set-up/gitlab.md
  docs/nx-cloud/set-up/minimal-ado-access-token.webp
  docs/nx-cloud/set-up/minimal-github-access-token.png
  docs/nx-cloud/set-up/minimal-github-access-token.webp
  docs/nx-cloud/set-up/minimal-gitlab-access-token.png
  docs/nx-cloud/set-up/minimal-gitlab-access-token.webp
  docs/nx-cloud/set-up/record-commands.md
  docs/nx-cloud/set-up/record-hello-world.png
  docs/nx-cloud/set-up/record-hello-world.webp
  docs/nx-cloud/set-up/use-github-app-auth.webp
  docs/shared/features/distribute-task-execution.md
  docs/shared/reference/sitemap.md
Labels: scope: docs
