Repository nrwl/nx, pull requests merged in 2024-01, with the labels that each got.

#21007 fix(nextjs): Add support for mjs next config file
  e2e/next-core/src/next-pcv3.test.ts
  packages/next/src/plugins/plugin.ts
Labels: scope: nextjs

#20583 feat(linter): move common options to target defaults
  graph/client/src/assets/release-static/environment.js
  packages/angular/src/generators/add-linting/add-linting.spec.ts
  packages/angular/src/generators/application/__snapshots__/application.spec.ts.snap
  packages/angular/src/generators/application/application.spec.ts
  packages/angular/src/generators/library/library.spec.ts
  packages/angular/src/generators/ng-add/__snapshots__/migrate-from-angular-cli.spec.ts.snap
  packages/cypress/src/generators/cypress-project/__snapshots__/cypress-project.spec.ts.snap
  packages/cypress/src/generators/migrate-to-cypress-11/__snapshots__/migrate-to-cypress-11.spec.ts.snap
  packages/eslint/migrations.json
  packages/eslint/src/generators/init/init.spec.ts
  packages/eslint/src/generators/init/init.ts
  packages/eslint/src/generators/lint-project/lint-project.spec.ts
  packages/eslint/src/generators/lint-project/lint-project.ts
  packages/eslint/src/migrations/update-17-2-9/move-options-to-target-defaults.spec.ts
  packages/eslint/src/migrations/update-17-2-9/move-options-to-target-defaults.ts
  packages/eslint/src/plugins/plugin.ts
  packages/expo/src/generators/library/library.spec.ts
  packages/js/src/generators/library/library.spec.ts
  packages/nest/src/generators/library/__snapshots__/library.spec.ts.snap
  packages/nest/src/generators/library/library.spec.ts
  packages/node/src/generators/application/application.spec.ts
  packages/node/src/generators/library/library.spec.ts
  packages/nuxt/src/generators/application/__snapshots__/application.spec.ts.snap
  packages/nx/src/command-line/init/implementation/add-nx-to-nest.ts
  packages/plugin/src/generators/e2e-project/e2e.spec.ts
  packages/plugin/src/generators/plugin/plugin.spec.ts
  packages/react-native/src/generators/library/library.spec.ts
  packages/react/src/generators/application/application.spec.ts
  packages/react/src/generators/library/library.spec.ts
  packages/remix/src/generators/cypress/cypress.impl.spec.ts
  packages/storybook/src/generators/configuration/__snapshots__/configuration.spec.ts.snap
  packages/vue/src/generators/application/__snapshots__/application.spec.ts.snap
  packages/vue/src/generators/library/library.spec.ts
  packages/web/src/generators/application/application.spec.ts
  packages/workspace/src/generators/move/move.spec.ts
Labels: scope: linter

#21103 fix(nextjs): PCV3 with Cypress and Playwright should work with standalone Next.js Projects
  e2e/next-core/src/next-structure.test.ts
  packages/next/src/generators/application/lib/create-application-files.ts
Labels: scope: nextjs

#21010 feat(nextjs): Standalone projects now default to src
  docs/generated/cli/create-nx-workspace.md
  docs/generated/packages/next/generators/application.json
  docs/generated/packages/nx/documents/create-nx-workspace.md
  docs/generated/packages/workspace/generators/new.json
  docs/generated/packages/workspace/generators/preset.json
  e2e/next-core/src/next-structure.test.ts
  e2e/next-core/src/next.test.ts
  e2e/next-extensions/src/next-component-tests.test.ts
  e2e/next-extensions/src/next-styles.test.ts
  e2e/nx-misc/src/workspace.test.ts
  e2e/utils/create-project-utils.ts
  e2e/workspace-create/src/create-nx-workspace.test.ts
  packages/create-nx-workspace/bin/create-nx-workspace.ts
  packages/next/src/generators/application/application.spec.ts
  packages/next/src/generators/application/files/common/specs/__fileName__.spec.tsx__tmpl__
  packages/next/src/generators/application/lib/create-application-files.ts
  packages/next/src/generators/application/lib/normalize-options.ts
  packages/next/src/generators/application/schema.d.ts
  packages/next/src/generators/application/schema.json
  packages/workspace/src/generators/convert-to-monorepo/convert-to-monorepo.spec.ts
  packages/workspace/src/generators/new/generate-preset.ts
  packages/workspace/src/generators/new/new.ts
  packages/workspace/src/generators/new/schema.json
  packages/workspace/src/generators/preset/preset.spec.ts
  packages/workspace/src/generators/preset/preset.ts
  packages/workspace/src/generators/preset/schema.d.ts
  packages/workspace/src/generators/preset/schema.json
Labels: scope: nextjs

#21188 fix(testing): Inline projects inside playwright.config.ts
  packages/playwright/src/generators/configuration/files/playwright.config.ts.template
  packages/playwright/src/utils/preset.ts
Labels: scope: testing tools

#21222 fix(nextjs): custom server unable to run production builds
  packages/next/src/executors/server/custom-server.impl.ts
  packages/next/src/executors/server/server.impl.ts
Labels: scope: nextjs

#21238 chore(nextjs): Remove env variable warning message
  packages/next/plugins/with-nx.ts
Labels: scope: nextjs

#21267 docs(nextjs): Update Next.js docs to add inferred targets
  docs/generated/packages/next/documents/overview.md
  docs/shared/packages/next/plugin-overview.md
Labels: scope: nextjs

#21287 fix(vite): PCV3 Plugin update to use resolveConfig
  packages/vite/src/plugins/__snapshots__/plugin-with-test.spec.ts.snap
  packages/vite/src/plugins/plugin-vitest.spec.ts
  packages/vite/src/plugins/plugin-with-test.spec.ts
  packages/vite/src/plugins/plugin.spec.ts
  packages/vite/src/plugins/plugin.ts
Labels: scope: plugins

#21366 fix(vite): PCV3 multiple targets
  e2e/vite/src/vite-pcv3.test.ts
  packages/vite/src/generators/vitest/vitest-generator.ts
Labels: scope: react

#21401 fix(nextjs): Add missing support swc for custom server
  packages/next/src/generators/custom-server/custom-server.spec.ts
  packages/next/src/generators/custom-server/custom-server.ts
  packages/next/src/utils/add-swc-to-custom-server.ts
  packages/next/src/utils/versions.ts
Labels: scope: nextjs
