Repository nrwl/nx, pull requests merged in 2024-07, with the labels that each got.

#23508 fix(node): Enable e2e test
  e2e/node/src/__snapshots__/node-server.test.ts.snap
  e2e/node/src/node-server.test.ts
  packages/node/src/generators/setup-docker/setup-docker.ts
Labels: scope: node

#26642 feat(core): update `actions/setup-node` to `v4` in `ci-workflow` generator
  packages/workspace/src/generators/ci-workflow/__snapshots__/ci-workflow.spec.ts.snap
  packages/workspace/src/generators/ci-workflow/files/github/.github/workflows/__workflowFileName__.yml__tmpl__
Labels: scope: core

#27065 docs(nx-dev): replace amplify logo with aws
  nx-dev/ui-cloud/src/lib/trusted-by.tsx
  nx-dev/ui-customers/src/lib/oss-projects.tsx
  nx-dev/ui-enterprise/src/lib/trusted-by.tsx
  nx-dev/ui-home/src/lib/trusted-by.tsx
  nx-dev/ui-icons/src/lib/customers/aws-amplify.tsx
Labels: scope: docs

#27061 feat(nx-dev): reprioritize customer logos on landing page
  nx-dev/ui-home/src/lib/trusted-by.tsx
  nx-dev/ui-icons/src/index.ts
  nx-dev/ui-icons/src/lib/customers/aws.tsx
Labels: type: docs

#27075 feat(nx-dev): Update footer links
  nx-dev/ui-common/src/lib/call-to-action.tsx
  nx-dev/ui-common/src/lib/footer.tsx
  nx-dev/ui-home/src/lib/hero.tsx
Labels: scope: docs
