Repository nrwl/nx, pull requests merged in 2025-07, with the labels that each got.

#30516 fix(core): add option to use v8 for daemon message serialization to avoid issues when JSON.stringify would fail
  packages/nx/src/daemon/client/client.ts
  packages/nx/src/daemon/client/daemon-socket-messenger.ts
  packages/nx/src/daemon/server/file-watching/file-watcher-sockets.ts
  packages/nx/src/daemon/server/handle-context-file-data.ts
  packages/nx/src/daemon/server/handle-flush-sync-generator-changes-to-disk.ts
  packages/nx/src/daemon/server/handle-get-files-in-directory.ts
  packages/nx/src/daemon/server/handle-get-registered-sync-generators.ts
  packages/nx/src/daemon/server/handle-get-sync-generator-changes.ts
  packages/nx/src/daemon/server/handle-glob.ts
  packages/nx/src/daemon/server/handle-hash-tasks.ts
  packages/nx/src/daemon/server/handle-nx-workspace-files.ts
  packages/nx/src/daemon/server/handle-outputs-tracking.ts
  packages/nx/src/daemon/server/handle-task-history.ts
  packages/nx/src/daemon/server/handle-tasks-execution-hooks.ts
  packages/nx/src/daemon/server/server.ts
  packages/nx/src/daemon/server/shutdown-utils.ts
  packages/nx/src/project-graph/plugins/isolation/messaging.ts
  packages/nx/src/project-graph/plugins/isolation/plugin-pool.ts
  packages/nx/src/project-graph/plugins/loaded-nx-plugin.ts
  packages/nx/src/tasks-runner/pseudo-ipc.ts
  packages/nx/src/utils/consume-messages-from-socket.spec.ts
  packages/nx/src/utils/consume-messages-from-socket.ts
Labels: priority: medium

#31621 feat(core): add support for `--tui` and `--no-tui`
  docs/generated/cli/affected.md
  docs/generated/cli/run-many.md
  docs/generated/cli/run.md
  docs/generated/packages/nx/documents/affected.md
  docs/generated/packages/nx/documents/run-many.md
  docs/generated/packages/nx/documents/run.md
  packages/nx/src/command-line/yargs-utils/shared-options.spec.ts
  packages/nx/src/command-line/yargs-utils/shared-options.ts
  packages/nx/src/tasks-runner/is-tui-enabled.spec.ts
  packages/nx/src/tasks-runner/is-tui-enabled.ts
  packages/nx/src/utils/command-line-utils.ts
Labels: priority: medium, codex

#31409 Update config-utils.ts
  packages/devkit/src/utils/config-utils.ts
Labels: priority: medium

#29608 fix(react-native): fix react native web configuration
  packages/react-native/src/generators/web-configuration/lib/webpack-targets.spec.ts
  packages/react-native/src/generators/web-configuration/lib/webpack-targets.ts
  packages/react-native/src/generators/web-configuration/web-configuration.ts
Labels: priority: medium

#32005 docs(core): update intro language for tutorials
  docs/shared/tutorials/angular-monorepo.md
  docs/shared/tutorials/gradle.md
  docs/shared/tutorials/react-monorepo.md
  docs/shared/tutorials/typescript-packages.md
Labels: type: docs

#31660 chore(gradle): document build-ci target
  docs/generated/packages/gradle/documents/overview.md
  docs/shared/packages/gradle/gradle-plugin.md
  packages/gradle/src/generators/ci-workflow/__snapshots__/generator.spec.ts.snap
  packages/gradle/src/generators/ci-workflow/files/github/.github/workflows/__workflowFileName__.yml.template
  packages/gradle/src/generators/ci-workflow/generator.ts
Labels: priority: medium

#32025 docs(core): add "next steps" for `nx init` docs
  docs/shared/getting-started/start-with-existing-project.md
Labels: type: docs

#29817 fix(react-native): add release option to publisable react-native library
  e2e/release/src/release-publishable-libraries-ts-solution.test.ts
  e2e/release/src/release-publishable-libraries.test.ts
  packages/react-native/src/generators/library/library.ts
Labels: priority: medium

#32109 fix(nx-dev): reenable YouTube, and Tweet components to markdoc configuration
  nx-dev/ui-markdoc/src/index.ts
Labels: scope: docs

#32137 docs(misc): update gradle tutorial
  docs/shared/tutorials/gradle-project-graph.json
  docs/shared/tutorials/gradle.md
  docs/shared/tutorials/nx-cloud-apply-fix-self-healing-ci.avif
  docs/shared/tutorials/nx-cloud-gh-comment-self-healing-coment.avif
Labels: type: docs

#32152 fix(rspack): update installed version of rspack to be same as @nx/rspack
  packages/rspack/src/utils/versions.ts
Labels: scope: js
