Repository nrwl/nx, pull requests merged in 2025-05, with the labels that each got.

#30818 feat(core)!: drop support for node versions prior to 20.19.0
  .github/workflows/generate-embeddings.yml
  .github/workflows/issue-notifier.yml
  .github/workflows/nightly/process-matrix.ts
  .github/workflows/publish.yml
  .nx/workflows/agents.yaml
  e2e/next/src/next-component-tests.test.ts
  e2e/release/src/lock-file-updates.test.ts
  e2e/remix/src/nx-remix.test.ts
  packages/nx/native-packages/darwin-arm64/package.json
  packages/nx/native-packages/darwin-x64/package.json
  packages/nx/native-packages/freebsd-x64/package.json
  packages/nx/native-packages/linux-arm-gnueabihf/package.json
  packages/nx/native-packages/linux-arm64-gnu/package.json
  packages/nx/native-packages/linux-arm64-musl/package.json
  packages/nx/native-packages/linux-x64-gnu/package.json
  packages/nx/native-packages/linux-x64-musl/package.json
  packages/nx/native-packages/win32-arm64-msvc/package.json
  packages/nx/native-packages/win32-x64-msvc/package.json
  packages/nx/package.json
Labels: scope: core, PR status: breaking-changes

#31105 docs(nx-dev): add Nx Cloud terms link in footer
  nx-dev/ui-common/src/lib/footer.tsx
Labels: type: docs, scope: docs

#31138 fix(core): do not follow symlinks when creating remote cache tarball
  packages/nx/src/native/cache/http_remote_cache.rs
Labels: priority: high

#31011 feat(core): run parallel based on the number of cpu cores
  docs/shared/recipes/running-tasks/run-tasks-in-parallel.md
  packages/nx/src/command-line/yargs-utils/shared-options.spec.ts
  packages/nx/src/command-line/yargs-utils/shared-options.ts
Labels: priority: medium

#30402 fix(esbuild): update peerDep range
  packages/esbuild/package.json
Labels: priority: high

#29026 fix(core): replace red in console with blue
  packages/nx/src/tasks-runner/running-tasks/node-child-process.ts
Labels: priority: medium

#29253 fix(linter): handle the flat config in workspace rule generators
  packages/eslint/src/generators/workspace-rule/files/__name__.spec.ts__tmpl__
  packages/eslint/src/generators/workspace-rule/workspace-rule.ts
  packages/eslint/src/generators/workspace-rules-project/__snapshots__/workspace-rules-project.spec.ts.snap
  packages/eslint/src/generators/workspace-rules-project/workspace-rules-project.spec.ts
  packages/eslint/src/generators/workspace-rules-project/workspace-rules-project.ts
Labels: scope: linter, priority: high

#31103 feat(devkit): allow requiring cts config files
  packages/devkit/src/utils/config-utils.ts
Labels: priority: high

#31091 feat(core): update getTouchedProjectsFromLockFile to detect which projects were changed from pnpm lock file diff
  packages/nx/src/plugins/js/project-graph/affected/lock-file-changes.spec.ts
  packages/nx/src/plugins/js/project-graph/affected/lock-file-changes.ts
  packages/nx/src/project-graph/file-utils.ts
Labels: priority: high

#31255 docs(nx-cloud): add `install-aws-cli` launch template step usage info
  docs/nx-cloud/reference/launch-templates.md
Labels: type: docs

#31261 docs(nx-cloud): improve info on setting access tokens in various CI providers
  docs/nx-cloud/concepts/cache-security.md
  docs/nx-cloud/recipes/access-tokens.md
  docs/nx-cloud/recipes/ado-add-branch-control.avif
  docs/nx-cloud/recipes/ado-library-end.avif
  docs/nx-cloud/recipes/ado-library-start.avif
  docs/nx-cloud/recipes/ado-pipeline-permission.avif
  docs/nx-cloud/recipes/ado-protected-branch.avif
  docs/nx-cloud/recipes/ado-protected-var-group.avif
  docs/nx-cloud/recipes/ado-unprotected-branch.avif
  docs/nx-cloud/recipes/bitbucket-deployment-env.avif
  docs/nx-cloud/recipes/bitbucket-repo-vars.avif
  docs/nx-cloud/recipes/circle-expression-restriction.avif
  docs/nx-cloud/recipes/circle-new-context.avif
  docs/nx-cloud/recipes/circle-new-env-var-token.avif
  docs/nx-cloud/recipes/circle-new-env-var.avif
  docs/nx-cloud/recipes/github-secrets-settings.avif
  docs/nx-cloud/recipes/github-select-protected-branches.avif
  docs/nx-cloud/recipes/github-settings-overview.avif
  docs/nx-cloud/recipes/gitlab-new-environment.avif
  docs/nx-cloud/recipes/gitlab-project-nav.avif
  docs/nx-cloud/recipes/gitlab-settings-nav.avif
  docs/nx-cloud/recipes/gitlab-variable-setting.avif
  docs/nx-cloud/recipes/gitlab-variable-settings-readonly.avif
  docs/nx-cloud/recipes/gitlab-variable-settings-readwrite.avif
Labels: type: docs

#31328 fix(react): routing option to library generator
  packages/react/src/generators/library/library.spec.ts
  packages/react/src/generators/library/library.ts
Labels: scope: react
