Repository nrwl/nx, pull requests merged in 2025-06, with the labels that each got.

#31393 feat(nest): Update nest version to 11
  docs/generated/manifests/menus.json
  docs/generated/manifests/new-nx-api.json
  docs/generated/manifests/nx-api.json
  docs/generated/packages-metadata.json
  docs/generated/packages/nest/migrations/21.2.0-beta.2-package-updates.json
  docs/shared/reference/sitemap.md
  packages/nest/migrations.json
  packages/nest/package.json
  packages/nest/src/generators/application/application.spec.ts
  packages/nest/src/generators/application/files/common/app/app.controller.ts__tmpl__
  packages/nest/src/generators/application/files/common/app/app.module.ts__tmpl__
  packages/nest/src/generators/application/files/common/app/app.service.ts__tmpl__
  packages/nest/src/generators/application/files/common/main.ts__tmpl__
  packages/nest/src/generators/application/files/test/app/app.controller.spec.ts__tmpl__
  packages/nest/src/generators/application/files/test/app/app.service.spec.ts__tmpl__
  packages/nest/src/generators/application/lib/create-files.ts
  packages/nest/src/utils/versions.ts
Labels: scope: node

#31413 fix(vite): add ajv dependency for non-pnpm package managers
  packages/vite/src/utils/ensure-dependencies.ts
  packages/vite/src/utils/versions.ts
Labels: scope: js

#31415 fix(js): enable end-to-end tests for Vue application in dev mode
  e2e/vue/src/vue.test.ts
Labels: scope: vue

#31402 docs(core): move plugin api docs to tech plugin guides
  docs/blog/2023-02-16-nx-15-7-node-support-angular-lts-lockfile-pruning.md
  docs/blog/2023-07-06-nx-16-5-release.md
  docs/blog/2025-05-08-improved-module-federation.md
  docs/generated/manifests/menus.json
  docs/generated/manifests/new-nx-api.json
  docs/generated/manifests/nx.json
  docs/generated/manifests/tags.json
  docs/generated/packages/angular/documents/nx-and-angular.md
  docs/generated/packages/eslint-plugin/documents/overview.md
  docs/generated/packages/storybook/documents/overview.md
  docs/generated/packages/storybook/generators/migrate-7.json
  docs/map.json
  docs/shared/guides/nx-and-angular-cli.md
  docs/shared/migration/migration-angular.md
  docs/shared/packages/eslint/eslint-plugin.md
  docs/shared/packages/storybook/plugin-overview.md
  docs/shared/recipes/storybook/configuring-storybook.md
  docs/shared/recipes/storybook/one-storybook-for-all.md
  docs/shared/recipes/storybook/one-storybook-per-scope.md
  docs/shared/recipes/storybook/one-storybook-with-composition.md
  docs/shared/recipes/storybook/plugin-angular.md
  docs/shared/recipes/storybook/plugin-react.md
  docs/shared/reference/sitemap.md
  docs/shared/tutorials/angular-monorepo.md
  nx-dev/models-document/src/lib/mappings.ts
  nx-dev/nx-dev/redirect-rules.js
  packages/storybook/docs/migrate-7-generator-examples.md
Labels: type: docs

#31445 docs(nx-dev): update enterprise page tagline
  nx-dev/nx-dev/pages/enterprise/index.tsx
  nx-dev/ui-enterprise/src/lib/hero.tsx
Labels: codex

#30453 feat(bundling): use tsconfig.lib.json for rollup.config.ts
  packages/rollup/src/plugins/__snapshots__/plugin.spec.ts.snap
  packages/rollup/src/plugins/plugin.ts
Labels: priority: high

#30567 fix(bundling): do not normalize tsconfig path for Windows with rollup
  packages/rollup/src/plugins/with-nx/with-nx.ts
Labels: priority: medium

#30462 docs(module-federation): update creating-a-remote.md
  docs/shared/recipes/module-federation/creating-a-remote.md
Labels: priority: medium

#31560 docs(nx-dev): add CVE-2025-36852 ref post
  docs/blog/2025-06-12-cve-2025-36852-critical-cache-poisoning-vulnerability-creep.md
  nx-dev/data-access-documents/src/lib/blog.api.ts
  nx-dev/ui-blog/src/lib/blog-container.tsx
Labels: type: docs

#31679 docs(nx-dev): add Nx Labs page
  nx-dev/nx-dev/pages/contact/labs.tsx
  nx-dev/nx-dev/pages/enterprise/security.tsx
  nx-dev/ui-common/src/lib/headers/header.tsx
  nx-dev/ui-common/src/lib/headers/menu-items.ts
  nx-dev/ui-contact/src/index.ts
  nx-dev/ui-contact/src/lib/nx-labs.tsx
  nx-dev/ui-icons/src/lib/customers/zipari.tsx
Labels: priority: medium

#31657 docs(nx-cloud): initial polygraph docs
  docs/external-generated/packages/conformance/documents/create-conformance-rule.md
  docs/external-generated/packages/conformance/documents/overview.md
  docs/generated/manifests/ci.json
  docs/generated/manifests/menus.json
  docs/generated/manifests/tags.json
  docs/map.json
  docs/nx-cloud/enterprise/conformance/configure-conformance-rules-in-nx-cloud.md
  docs/nx-cloud/enterprise/custom-workflows.md
  docs/nx-cloud/enterprise/images/apply-workflow.avif
  docs/nx-cloud/enterprise/images/cipe-conformance-report.avif
  docs/nx-cloud/enterprise/images/conformance-apply-workspace-empty.avif
  docs/nx-cloud/enterprise/images/conformance-notifications.avif
  docs/nx-cloud/enterprise/images/conformance-rule-dashboard-empty.avif
  docs/nx-cloud/enterprise/images/conformance-rule-results-table.avif
  docs/nx-cloud/enterprise/images/conformance-rules-table-run-meta.avif
  docs/nx-cloud/enterprise/images/connect-polygraph-to-repos.avif
  docs/nx-cloud/enterprise/images/connect-repo-to-polygraph.avif
  docs/nx-cloud/enterprise/images/custom-workflow-assign-template.avif
  docs/nx-cloud/enterprise/images/custom-workflow-configure-launch-template.avif
  docs/nx-cloud/enterprise/images/custom-workflow-conformance-run.avif
  docs/nx-cloud/enterprise/images/custom-workflow-repeating-workflows.avif
  docs/nx-cloud/enterprise/images/org-overview.avif
  docs/nx-cloud/enterprise/images/org-polygraph-overview.avif
  docs/nx-cloud/enterprise/images/polygraph-connect-workspace.avif
  docs/nx-cloud/enterprise/images/workspace-graph.avif
  docs/nx-cloud/enterprise/metadata-only-workspace.md
  docs/nx-cloud/enterprise/polygraph.md
  docs/shared/features/powerpack/conformance.md
  docs/shared/packages/conformance/conformance-plugin.md
  docs/shared/packages/conformance/create-conformance-rule.md
  docs/shared/reference/sitemap.md
Labels: type: docs, priority: medium

#30806 feat(module-federation): bump @module-federation/enhanced version to 0.15.0 to fix vulnerability
  docs/generated/manifests/new-nx-api.json
  docs/generated/packages-metadata.json
  docs/generated/packages/module-federation/migrations/20.5.0-package-updates.json
  docs/generated/packages/module-federation/migrations/20.5.0.json
  docs/generated/packages/module-federation/migrations/21.2.0-package-updates.json
  package.json
  packages/angular/src/utils/versions.ts
  packages/module-federation/migrations.json
  packages/module-federation/package.json
  packages/module-federation/src/executors/utils/build-static-remotes.ts
  packages/module-federation/src/plugins/utils/build-static-remotes.ts
  packages/module-federation/src/with-module-federation/angular/with-module-federation.ts
  packages/module-federation/src/with-module-federation/rspack/with-module-federation.ts
  packages/module-federation/src/with-module-federation/webpack/with-module-federation.ts
  packages/react/src/utils/versions.ts
  packages/rspack/package.json
  pnpm-lock.yaml
Labels: priority: high

#31626 feat(graph): enhance migration state management and introduce migration stopping functionality.
  graph/client/src/app/console-migrate/migrate.app.tsx
  graph/migrate/src/lib/components/automatic-migration.tsx
  graph/migrate/src/lib/components/migration-card.tsx
  graph/migrate/src/lib/components/migration-list.tsx
  graph/migrate/src/lib/components/migration-timeline.tsx
  graph/migrate/src/lib/migrate.stories.tsx
  graph/migrate/src/lib/migrate.tsx
  graph/migrate/src/lib/state/automatic/guards.ts
  graph/migrate/src/lib/state/automatic/machine.spec.ts
  graph/migrate/src/lib/state/automatic/machine.ts
  graph/migrate/src/lib/state/automatic/selectors.ts
  graph/migrate/src/lib/state/automatic/types.ts
  packages/nx/src/command-line/migrate/migrate-ui-api.ts
  packages/nx/src/command-line/migrate/run-migration-process.js
Labels: priority: medium

#31666 docs(nx-dev): write blog post about autofix notifications in JetBrains
  docs/blog/2025-02-17-monorepos-are-ai-future-proof.md
  docs/blog/2025-03-06-making-cursor-smarter.md
  docs/blog/2025-04-15-nx-mcp-vscode-copilot.md
  docs/blog/2025-04-17-nx-and-ai-why-they-work-together.md
  docs/blog/2025-05-01-nx-mcp-ci-fixes.md
  docs/blog/2025-05-13-nx-generators-ai-integration.md
  docs/blog/2025-05-28-nx-terminal-integration-ai.md
  docs/blog/2025-06-23-nx-self-healing-ci.md
  docs/blog/2025-06-25-nx-cloud-mcp-ci-optimization.md
  docs/blog/2025-06-26-jetbrains-ci-notifications.md
  docs/blog/images/articles/autofix-ai-assistant.avif
  docs/blog/images/articles/autofix-notification.avif
  docs/blog/images/articles/jetbrains-mcp-autofixing.avif
  docs/blog/images/articles/jetbrains-mcp-autofixing.png
  docs/shared/getting-started/ai-setup.md
Labels: priority: medium

#31655 feat(core): pass in progress task outputs to tui for non-direct child processes
  CLAUDE.md
  packages/nx/src/tasks-runner/forked-process-task-runner.ts
  packages/nx/src/tasks-runner/running-tasks/node-child-process.ts
  packages/nx/src/tasks-runner/task-orchestrator.ts
Labels: priority: medium

#31733 docs(nx-cloud): callout templates use nx-cloud features
  docs/shared/monorepo-ci-azure.md
  docs/shared/monorepo-ci-bitbucket-pipelines.md
  docs/shared/monorepo-ci-circle-ci.md
  docs/shared/monorepo-ci-github-actions.md
  docs/shared/monorepo-ci-gitlab.md
  docs/shared/monorepo-ci-jenkins.md
Labels: type: docs

#31767 fix(node): improve error handling during cleanup in Node application tests
  e2e/node/src/node-ts-solution.test.ts
Labels: scope: node

#31770 fix(core): resolve package.json for @nx/js to improve plugin detection
  packages/nx/src/utils/package-json.ts
Labels: scope: core

#31665 fix(core): allow any framework value in preset generator schema
  docs/generated/packages/workspace/generators/new.json
  docs/generated/packages/workspace/generators/preset.json
  packages/workspace/src/generators/new/new.ts
  packages/workspace/src/generators/new/schema.json
  packages/workspace/src/generators/preset/schema.d.ts
  packages/workspace/src/generators/preset/schema.json
Labels: priority: medium

#31791 docs(misc): add info about Okta advanced configuration
  docs/nx-cloud/enterprise/single-tenant/auth-saml.md
  docs/nx-cloud/enterprise/single-tenant/images/saml/okta_11.png
Labels: scope: docs
