Repository nrwl/nx, pull requests merged in 2025-03, with the labels that each got.

#30232 fix(vite): correct mapping for reportsDirectory when using executors
  e2e/vite/src/vite-legacy.test.ts
  packages/vite/src/executors/test/lib/utils.ts
Labels: scope: js

#30265 docs(nx-dev): consistency updates for team members
  nx-dev/ui-company/src/lib/the-team.tsx
Labels: type: docs

#30277 docs(linter): add support for esm in eslint api docs
  docs/generated/packages/eslint/documents/overview.md
  docs/shared/packages/eslint/eslint.md
Labels: scope: docs

#30230 fix(bundling): fix esbuild to work with ts project references
  e2e/node/src/node-ts-solution-esbuild.test.ts
  packages/esbuild/src/executors/esbuild/lib/build-esbuild-options.ts
  packages/js/src/plugins/typescript/plugin.ts
  packages/js/src/plugins/typescript/util.ts
  packages/js/src/utils/typescript/ts-solution-setup.ts
  packages/storybook/src/generators/configuration/lib/util-functions.ts
Labels: scope: bundlers

#30294 docs(nx-dev): Update ARM resource classes
  nx-dev/ui-pricing/src/lib/credit-pricing.tsx
Labels: type: docs

#30077 docs(nx-cloud): update assignment rules pages with new model
  docs/nx-cloud/reference/assignment-rules.md
  docs/nx-cloud/reference/env-vars.md
Labels: PR status: do not merge

#30440 docs(misc): add angular book blog
  docs/blog/2025-03-17-modern-angular-testing-with-nx.md
  docs/blog/2025-03-18-architecting-angular-applications.md
  docs/blog/2025-03-19-using-angular-with-rspack.md
  docs/blog/2025-03-20-enterprise-angular-book.md
  docs/blog/images/2025-03-20/book-relaunch.avif
  docs/blog/images/2025-03-20/book-relaunch.png
Labels: PR status: do not merge

#30120 feat(repo): replace explicit matrix with dynamic parsed from json
  .github/workflows/e2e-matrix.yml
  .github/workflows/e2e-windows.yml
  .github/workflows/nightly/process-matrix.ts
Labels: scope: repo

#30537 fix(nextjs): bumped to eslintConfigNextVersion to v15
  docs/generated/manifests/nx-api.json
  docs/generated/packages-metadata.json
  docs/generated/packages/next/migrations/20.7.1-beta.0-package-updates.json
  packages/next/migrations.json
  packages/next/src/utils/versions.ts
Labels: scope: nextjs
