Repository nrwl/nx, pull requests merged in 2025-02, with the labels that each got.

#29895 fix(nextjs): enhance support for custom server with SWC configuration
  e2e/next/src/next-legacy.test.ts
  e2e/next/src/next.test.ts
  packages/js/src/executors/node/node.impl.ts
  packages/js/src/utils/swc/add-swc-config.ts
  packages/next/src/generators/application/application.ts
  packages/next/src/generators/custom-server/custom-server.ts
  packages/next/src/generators/custom-server/files/server/main.ts__tmpl__
  packages/next/src/utils/add-swc-to-custom-server.ts
Labels: scope: nextjs, scope: js

#30104 fix(repo): fix nightly reporting
  .github/workflows/e2e-matrix.yml
  .github/workflows/e2e-windows.yml
Labels: scope: repo

#30173 fix(core): standardize useGitHub param
  packages/create-nx-workspace/bin/create-nx-workspace.ts
  packages/create-nx-workspace/src/internal-utils/prompts.ts
  packages/create-nx-workspace/src/utils/nx/nx-cloud.ts
Labels: scope: core

#30189 fix(nextjs): add support for @testing-library/dom in application and library generators
  packages/next/src/generators/application/application.ts
  packages/next/src/generators/library/library.ts
Labels: scope: nextjs

#30192 fix(nextjs): add setup generator for Tailwind CSS fixes absolute pathing
  packages/next/src/generators/application/application.ts
  packages/next/src/generators/setup-tailwind/files/postcss.config.js__tmpl__
  packages/next/src/generators/setup-tailwind/files/tailwind.config.js__tmpl__
  packages/next/src/generators/setup-tailwind/lib/add-tailwind-style-imports.ts
  packages/next/src/generators/setup-tailwind/lib/update-project.ts
  packages/next/src/generators/setup-tailwind/schema.json
  packages/next/src/generators/setup-tailwind/schema.ts
  packages/next/src/generators/setup-tailwind/setup-tailwind.spec.ts
  packages/next/src/generators/setup-tailwind/setup-tailwind.ts
  packages/next/tailwind.ts
Labels: scope: nextjs

#30233 docs(core): remove include command from nx-graph
  docs/generated/cli/graph.md
  docs/generated/packages/nx/documents/dep-graph.md
  packages/nx/src/command-line/examples.ts
Labels: scope: docs
